from typing import Any

def optional_import(module: str) -> ModuleType | None: ...
def require(module: str, *, purpose: str | None = ...) -> ModuleType: ...
def require_attr(module: str, attr: str, *, purpose: str | None = ...) -> Any: ...
