from typing import Any

"""
IRCache: keyed in-memory cache for IR objects.
"""

class IRCache:
    def __init__(self: Any) -> None: ...
    def get(self: Any, ir_hash: str) -> Any | None: ...
    def put(self: Any, ir_hash: str, ir: Any) -> None: ...
    def evict(self: Any, ir_hash: str) -> None: ...
