from typing import Any

"""
PlanCache: keyed in-memory cache for plan objects.
"""

class PlanCache:
    def __init__(self: Any) -> None: ...
    def get(self: Any, plan_hash: str) -> Any | None: ...
    def put(self: Any, plan_hash: str, plan: Any) -> None: ...
    def evict(self: Any, plan_hash: str) -> None: ...
