from typing import Any

"""
SpecCache: keyed in-memory cache for Spec objects (keyed by spec hash).
"""

class SpecCache:
    def __init__(self: Any) -> None: ...
    def get(self: Any, spec_hash: str) -> Any | None: ...
    def put(self: Any, spec_hash: str, spec: Any) -> None: ...
    def evict(self: Any, spec_hash: str) -> None: ...
