from typing import Any

"""
DriftReport: live drift metrics rendered from monitoring artifacts.
"""

class DriftReport:
    job_id: str = ...
    feature_hash: str = ...
    mean_drift_score: float = ...
    max_drift_score: float = ...
    n_triggers: int = ...
    window_start: datetime = ...
    window_end: datetime = ...
    details: dict[str, float] = ...
def render_drift_report(artifact: dict[str, Any]) -> DriftReport: ...
