from typing import Any

"""
GateReport: per-gate pass/fail breakdown rendered from artifacts.
"""

class GateReport:
    job_id: str = ...
    candidate_id: str = ...
    overall_passed: bool = ...
    gate_scores: dict[str, float] = ...
    gate_passed: dict[str, bool] = ...
    dsr: float = ...
    t_stat: float = ...
def render_gate_report(artifact: dict[str, Any]) -> GateReport: ...
