from typing import Any

"""
PromotionReport: record of a promotion event rendered from artifacts.
"""

class PromotionReport:
    job_id: str = ...
    candidate_id: str = ...
    promotion_id: str = ...
    mode: str = ...
    approved_by: str | None = ...
    promoted_at: datetime = ...
    artifact_hash: str = ...
def render_promotion_report(artifact: dict[str, Any]) -> PromotionReport: ...
