from typing import Any

"""
RobustnessReport: stability and regime-robustness metrics rendered from artifacts.
"""

class RobustnessReport:
    job_id: str = ...
    candidate_id: str = ...
    fold_score_variance: float = ...
    stability_score: float = ...
    pbo_score: float | None = ...
    regime_breakdown: dict[str, float] = ...
def render_robustness_report(artifact: dict[str, Any]) -> RobustnessReport: ...
