from typing import Any

"""
TuningReport: summary of a completed tuning run rendered from artifacts.
"""

class TuningReport:
    job_id: str = ...
    spec_hash: str = ...
    best_candidate_id: str = ...
    best_score: float = ...
    n_trials: int = ...
    n_folds: int = ...
    algorithm: str = ...
    gate_passed: bool = ...
    tags: dict[str, str] = ...
def render_tuning_report(artifact: dict[str, Any]) -> TuningReport: ...
