from typing import Any

"""
ValidationReport: per-fold cross-validation results rendered from artifacts.
"""

class FoldResult:
    fold_index: int = ...
    sharpe: float = ...
    max_drawdown: float = ...
    cost_stress_bps: float = ...
class ValidationReport:
    job_id: str = ...
    candidate_id: str = ...
    method: str = ...
    fold_results: tuple[FoldResult, ...] = ...
    mean_sharpe: float = ...
    mean_drawdown: float = ...
def render_validation_report(artifact: dict[str, Any]) -> ValidationReport: ...
