from typing import Any

"""
Dataprep orchestration bridge.

Coordinates data preparation pipelines between Python preprocessing
and Java entry points. Provides typed contracts for cross-runtime
data handoff with deterministic lineage tracking.
"""

class DataprepSpec:
    pipeline_id: str = ...
    config_path: Path = ...
    output_dir: Path = ...
    as_of: str | None = ...
class DataprepResult:
    success: bool = ...
    artifact_paths: Mapping[str, Path] = ...
    lineage_hash: str = ...
    metrics: Mapping[str, float] = ...
class DataprepOrchestrator(ABC):
    def prepare(self: Any, spec: DataprepSpec) -> DataprepResult: ...
    def validate(self: Any, result: DataprepResult) -> bool: ...
    def replay(self: Any, lineage_hash: str) -> DataprepResult: ...
