from typing import Any

class SplitAction:
    symbol: str = ...
    ratio: float = ...
class DividendAction:
    symbol: str = ...
    amount_per_share: float = ...
class SymbolChangeAction:
    old_symbol: str = ...
    new_symbol: str = ...
