from typing import Any

class PositionLot:
    symbol: str = ...
    quantity: float = ...
    average_price: float = ...
class CashBook:
    balance: float = ...
class PositionBook:
    lots: dict[str, PositionLot] = ...
