from typing import Any

class DataLoader:
    def fetch_alpha(symbol: Any, **kwargs: Any) -> Any: ...
class LogisticRegressionStrategy:
    ...
class RandomForestStrategy:
    ...
class ARIMAStrategy:
    ...
class GARCHStrategy:
    ...
class MovingAverageCrossover:
    ...
class RSIStrategy:
    ...
class MACDStrategy:
    ...
class BollingerStrategy:
    ...
strategies: Any
regimes: Any
results: Any
df: Any
