from typing import Any

class ProbSparseAttention(tf.keras.layers.Layer):
    def __init__(self: Any, d_model: Any, n_heads: Any) -> Any: ...
    def call(self: Any, inputs: Any) -> Any: ...
class InformerModel(tf.keras.Model):
    def __init__(self: Any, input_dim: Any, output_dim: Any, seq_len: Any, pred_len: Any, d_model: Any = ..., n_heads: Any = ..., e_layers: Any = ...) -> Any: ...
    def call(self: Any, inputs: Any) -> Any: ...
def build_informer(input_dim: Any, output_dim: Any, seq_len: Any, pred_len: Any) -> Any: ...
