from typing import Any

log: Any
class ClassifierConfig(LSTMConfig):
    num_classes: int = ...
    projection_dim: Optional[int] = ...
    pooling_type: Optional[str] = ...
    def from_marketmind(cls: Any, overrides: Optional[Mapping[str, Any]] = ...) -> 'ClassifierConfig': ...
class LSTMClassifier(nn.Module):
    def __init__(self: Any, config: Optional[ClassifierConfig] = ...) -> Any: ...
    def num_parameters(self: Any, trainable_only: bool = ...) -> int: ...
    def forward(self: Any, x: torch.Tensor, lengths: Optional[torch.Tensor] = ...) -> torch.Tensor: ...
    def predict_proba(self: Any, x: torch.Tensor, lengths: Optional[torch.Tensor] = ...) -> torch.Tensor: ...
    def save(self: Any, path: str) -> None: ...
    def from_pretrained(cls: Any, path: str, map_location: str | torch.device = ...) -> 'LSTMClassifier': ...
