from typing import Any

log: Any
class LSTMConfig:
    input_dim: int = ...
    units: int = ...
    num_layers: int = ...
    zoneout_rate: float = ...
    input_dropout_rate: float = ...
    dropout: float = ...
    bidirectional: bool = ...
    return_sequences: bool = ...
    residual: bool = ...
    pooling_type: Optional[str] = ...
    use_custom_cell: bool = ...
    seed: Optional[int] = ...
    def to_dict(self: Any) -> Any: ...
class BucketBatchSampler(Sampler[List[int]]):
    def __init__(self: Any, dataset: List[Tuple[torch.Tensor, torch.Tensor]], batch_size: int, boundaries: List[int]) -> None: ...
def collate_fn(batch: Any) -> Any: ...
class SharedDropout(nn.Module):
    def __init__(self: Any, p: float) -> Any: ...
    def train(self: Any, mode: bool = ...) -> Any: ...
    def forward(self: Any, x: torch.Tensor) -> torch.Tensor: ...
class NormLSTMCell(nn.Module):
    def __init__(self: Any, inp: int, hid: int, zoneout: float) -> Any: ...
    def forward(self: Any, x: torch.Tensor, state: Tuple[torch.Tensor, torch.Tensor]) -> Tuple[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]: ...
class NormLSTM(nn.Module):
    def __init__(self: Any, inp: int, hid: int, zoneout: float, *, return_seq: bool) -> Any: ...
    def forward(self: Any, x: torch.Tensor, lengths: Optional[torch.Tensor] = ...) -> Any: ...
class BidirectionalNormLSTM(nn.Module):
    def __init__(self: Any, inp: int, hid: int, zoneout: float, *, return_seq: bool) -> Any: ...
    def forward(self: Any, x: torch.Tensor, lengths: Optional[torch.Tensor] = ...) -> Any: ...
class LSTMBlock(nn.Module):
    def __init__(self: Any, cfg: LSTMConfig) -> Any: ...
    def forward(self: Any, x: torch.Tensor, lengths: Optional[torch.Tensor] = ...) -> Any: ...
    def get_config(self: Any) -> Any: ...
    def from_config(cls: Any, config: Any) -> Any: ...
class Model(nn.Module):
    def __init__(self: Any, cfg: LSTMConfig) -> Any: ...
    def forward(self: Any, x: torch.Tensor, lengths: Optional[torch.Tensor] = ...) -> torch.Tensor: ...
