from typing import Any

def register_source(name: str) -> Any: ...
def get_registry() -> Dict[str, Any]: ...
class DataSource:
    async def get_historical(self: Any, *args: Any, **kwargs: Any) -> Any: ...
