from typing import Any

class AlternativeDataManager(AbstractAPIDataManager):
    ...
class TwitterSource(APIDataSource):
    def __init__(self: Any, config: Any) -> Any: ...
class ESGSource(APIDataSource):
    def __init__(self: Any, config: Any) -> Any: ...
class WeatherSource(APIDataSource):
    def __init__(self: Any, config: Any) -> Any: ...
