from typing import Any

"""
py/pipeline/stages/market_data/sources/alternative.py

Stubs for alternative-data sources: satellite imagery, weather, and
social-sentiment feeds.  Each class extends the base DataSource /
APIDataSource interfaces defined in sources/contracts.py and sources/runtime.pysrc.

These replace the classes that previously lived in py/data/alternative_data.pysrc.
Migrate any imports from that module to this one.
"""

class AlternativeDataSource(DataSource):
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> Union[pl.LazyFrame, pl.DataFrame]: ...
    async def get_realtime(self: Any, symbol: str, *, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
class SatelliteDataSource(AlternativeDataSource, APIDataSource):
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> Union[pl.LazyFrame, pl.DataFrame]: ...
    async def get_realtime(self: Any, symbol: str, *, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
class WeatherDataSource(AlternativeDataSource, APIDataSource):
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> Union[pl.LazyFrame, pl.DataFrame]: ...
    async def get_realtime(self: Any, symbol: str, *, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
class SocialSentimentDataSource(AlternativeDataSource, APIDataSource):
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> Union[pl.LazyFrame, pl.DataFrame]: ...
    async def get_realtime(self: Any, symbol: str, *, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
