from typing import Any

class FileSource(DataSource):
    def __init__(self: Any, config: str | os.PathLike[str] | dict[str, Any]) -> Any: ...
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> pl.LazyFrame | pl.DataFrame: ...
    def get_historical_sync(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> pl.LazyFrame | pl.DataFrame: ...
    async def get_realtime(self: Any, symbol: str, *, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
