from typing import Any

class FREDVintageSeam(Protocol):
    def apply(self: Any, frame: pl.DataFrame, *, retrieval_time: datetime) -> pl.DataFrame: ...
class FREDApproximationStub:
    def apply(self: Any, frame: pl.DataFrame, *, retrieval_time: datetime) -> pl.DataFrame: ...
class FREDSource(DataSource):
    def __init__(self: Any, config: dict[str, Any], *, fred_client: Any | None = ..., vintage_seam: FREDVintageSeam | None = ..., retrieval_clock: Callable[[], datetime] | None = ...) -> None: ...
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> pl.LazyFrame | pl.DataFrame: ...
    async def get_realtime(self: Any, symbol: str, *, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
