from typing import Any

class InfluxDBSource(DataSource):
    def __init__(self: Any, config: dict) -> Any: ...
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> Union[pl.LazyFrame, pl.DataFrame]: ...
    async def get_realtime(self: Any, symbol: str, *, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
