from typing import Any

T: Any
class AsyncLRU:
    def __init__(self: Any, maxsize: int = ..., ttl: float = ...) -> Any: ...
    async def get_or_set(self: Any, key: Hashable, coro_factory: Callable[[], Awaitable[T]]) -> T: ...
class SourceRegistry:
    def __init__(self: Any) -> None: ...
    def register(self: Any, name: str, cls: Type[DataSource]) -> None: ...
    def names(self: Any) -> List[str]: ...
    def get(self: Any, name: str) -> Optional[DataSource]: ...
    def create(self: Any, name: str, cfg: Mapping[str, Any]) -> DataSource: ...
    def ensure(self: Any, name: str, cfg: Mapping[str, Any]) -> DataSource: ...
REGISTRY: Any
def register_source(name: str) -> Callable[[Type[DataSource]], Type[DataSource]]: ...
class CompositeSource(DataSource):
    def __init__(self: Any, cfg: Mapping[str, Any]) -> Any: ...
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> pl.LazyFrame: ...
    async def get_realtime(self: Any, symbol: str, *, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
class FailoverSource(DataSource):
    def __init__(self: Any, cfg: Mapping[str, Any]) -> Any: ...
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> pl.LazyFrame: ...
    async def get_realtime(self: Any, symbol: str, *, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
class MarketDataConfig:
    default_source: str = ...
    cache_maxsize: int = ...
    cache_ttl: float = ...
    retry_attempts: int = ...
    retry_base_delay: float = ...
    fanout_concurrency: int = ...
    source_configs: Optional[Mapping[str, Mapping[str, Any]]] = ...
class MarketDataManager:
    def __init__(self: Any, *, config: Optional[MarketDataConfig] = ...) -> None: ...
    def register_instance(self: Any, name: str, src: DataSource) -> None: ...
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, source_name: Optional[str] = ..., eager: bool = ...) -> pl.LazyFrame: ...
    async def get_historical_cached(self: Any, symbol: str, start: str, end: str, *, source_name: Optional[str] = ..., eager: bool = ...) -> pl.LazyFrame: ...
    async def get_historical_many(self: Any, symbols: Iterable[str], start: str, end: str, *, source_name: Optional[str] = ..., eager: bool = ..., use_cache: bool = ...) -> pl.LazyFrame: ...
    async def get_historical_auto(self: Any, symbol: str, start: str, end: str, *, candidates: Optional[List[str]] = ..., eager: bool = ...) -> pl.LazyFrame: ...
    async def get_realtime(self: Any, symbol: str, *, source_name: Optional[str] = ..., interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
    def close(self: Any) -> None: ...
def build_client_from_config(cfg: Mapping[str, Any]) -> MarketDataManager: ...
