from typing import Any

"""
Build one-Parquet-per-day adjusted Massive OHLCV panels.
"""

DEFAULT_RAW_ROOT: Final[Path] = ...
DEFAULT_CORPORATE_ACTIONS_ROOT: Final[Path] = ...
DEFAULT_OUTPUT_ROOT: Final[Path] = ...
MANIFEST_SCHEMA_VERSION: Final[str] = ...
BUILDER_VERSION: Final[str] = ...
SOURCE_ID: Final[str] = ...
LOG: Any
class AdjustedPanelBuildConfig:
    start_date: date = ...
    end_date: date = ...
    raw_root: Path = ...
    corporate_actions_root: Path = ...
    output_root: Path = ...
    splits_path: Path | None = ...
    dividends_path: Path | None = ...
    overwrite: bool = ...
    verbose: bool = ...
class AdjustedPanelFileResult:
    trade_date: str = ...
    path: str = ...
    rows: int = ...
    content_blake2b: str = ...
    status: str = ...
    duration_seconds: float = ...
class AdjustedPanelBuildError(ValueError):
    ...
def build_adjusted_daily_panels(config: AdjustedPanelBuildConfig) -> list[AdjustedPanelFileResult]: ...
def write_manifest(config: AdjustedPanelBuildConfig, results: Sequence[AdjustedPanelFileResult]) -> Path: ...
def parse_args(argv: list[str]) -> AdjustedPanelBuildConfig: ...
def configure_logging(verbose: bool) -> None: ...
def main(argv: list[str]) -> int: ...
