from typing import Any

"""
Massive (formerly Polygon) flat-files loader for US Stocks SIP day aggregates.

Downloads a configurable date range of `us_stocks_sip/day_aggs_v1/YYYY/MM/YYYY-MM-DD.csv.gz`
from the Massive S3-compatible endpoint, converts each file to Parquet partitioned by date,
and emits a per-run manifest for reproducibility.

Endpoint reference: https://massive.com/docs/flat-files/quickstart

Design notes:
- Functional core / imperative shell: pure transform `csv_gz_bytes_to_parquet_table` is
  separated from S3 I/O and disk writes.
- Idempotent resume: skips files whose Parquet output already exists.
- Structured logging only; no print; no bare except.
- Credentials are read from environment variables, never hardcoded.
- Emits a manifest with per-file content hashes (BLAKE2b) and S3 ETags for lineage.
"""

MASSIVE_ENDPOINT: Final[str] = ...
MASSIVE_BUCKET: Final[str] = ...
DATASET_PREFIX: Final[str] = ...
SOURCE_ID: Final[str] = ...
MANIFEST_SCHEMA_VERSION: Final[str] = ...
EXECUTION_PLAN_VERSION: Final[str] = ...
DETERMINISM_TIER: Final[str] = ...
S3_MISSING_OBJECT_CODES: Final[frozenset[str]] = ...
DEFAULT_WORKERS: Final[int] = ...
DEFAULT_OUTPUT_ROOT: Final[Path] = ...
LOADER_VERSION: Final[str] = ...
logger: Any
class LoaderError(Exception):
    ...
class CredentialsMissingError(LoaderError):
    ...
class DownloadError(LoaderError):
    ...
class ParquetConversionError(LoaderError):
    ...
class MissingDependencyError(LoaderError):
    ...
class FileResult:
    trade_date: str = ...
    s3_key: str = ...
    parquet_path: str = ...
    status: str = ...
    rows: int = ...
    bytes_compressed: int = ...
    bytes_parquet: int = ...
    s3_etag: str = ...
    content_blake2b: str = ...
    error: str | None = ...
    duration_seconds: float = ...
    partition_identity: str = ...
    knowledge_time_utc: str | None = ...
class LoaderConfig:
    start_date: date = ...
    end_date: date = ...
    output_root: Path = ...
    workers: int = ...
    overwrite: bool = ...
    verbose: bool = ...
class StreamingBody(Protocol):
    def read(self: Any) -> bytes: ...
class S3ObjectResponse(TypedDict):
    Body: StreamingBody = ...
    ETag: str = ...
class S3Client(Protocol):
    def get_object(self: Any, *, Bucket: str, Key: str) -> S3ObjectResponse: ...
class Boto3Session(Protocol):
    def client(self: Any, service_name: str, *, endpoint_url: str, config: object) -> object: ...
class Boto3SessionFactory(Protocol):
    ...
class Boto3Module(Protocol):
    Session: Boto3SessionFactory = ...
class BotocoreConfigFactory(Protocol):
    ...
class BotocoreConfigModule(Protocol):
    Config: BotocoreConfigFactory = ...
class ArrowTable(Protocol):
    def num_rows(self: Any) -> int: ...
    def column_names(self: Any) -> list[str]: ...
    def column(self: Any, name: str) -> object: ...
    def append_column(self: Any, name: str, column: object) -> ArrowTable: ...
class PyArrowModule(Protocol):
    ArrowInvalid: type[Exception] = ...
    ArrowIOError: type[Exception] = ...
    def array(self: Any, values: object, *, type: object) -> object: ...
    def date32(self: Any) -> object: ...
    def timestamp(self: Any, unit: str, *, tz: str) -> object: ...
class PyArrowCsvModule(Protocol):
    def read_csv(self: Any, source: object) -> ArrowTable: ...
class PyArrowParquetModule(Protocol):
    def write_table(self: Any, table: ArrowTable, where: Path, *, compression: str) -> None: ...
def trading_dates(start: date, end: date) -> Iterator[date]: ...
def s3_key_for(d: date) -> str: ...
def parquet_path_for(output_root: Path, d: date) -> Path: ...
def partition_identity_for(d: date) -> str: ...
def csv_gz_bytes_to_parquet_table(raw_gz: bytes, *, trade_date: date, knowledge_time: datetime) -> ArrowTable: ...
def blake2b_hex(data: bytes) -> str: ...
def atomic_write_json(path: Path, payload: object) -> None: ...
def dependency_versions() -> dict[str, str | None]: ...
def build_s3_client() -> S3Client: ...
def ensure_runtime_dependencies() -> None: ...
def download_and_convert_one(s3: S3Client, d: date, output_root: Path, overwrite: bool) -> FileResult: ...
def run(config: LoaderConfig) -> list[FileResult]: ...
def write_manifest(config: LoaderConfig, results: list[FileResult]) -> Path: ...
def configure_logging(verbose: bool) -> None: ...
def parse_args(argv: list[str]) -> LoaderConfig: ...
def main(argv: list[str]) -> int: ...
