from typing import Any

"""
Massive corporate-actions loader for splits and dividends.
"""

MASSIVE_API_BASE: Final[str] = ...
DEFAULT_OUTPUT_ROOT: Final[Path] = ...
LOADER_VERSION: Final[str] = ...
MANIFEST_SCHEMA_VERSION: Final[str] = ...
SOURCE_ID: Final[str] = ...
ActionKind: Any
LOG: Any
class CorporateActionsLoaderError(Exception):
    ...
class CorporateActionsCredentialsError(CorporateActionsLoaderError):
    ...
class CorporateActionsFetchError(CorporateActionsLoaderError):
    ...
class CorporateActionsConfig:
    start_date: date = ...
    end_date: date = ...
    output_root: Path = ...
    actions: tuple[ActionKind, ...] = ...
    tickers: tuple[str, ...] = ...
    api_key_env: str = ...
    limit: int = ...
    verbose: bool = ...
class CorporateActionsFileResult:
    action: ActionKind = ...
    path: str = ...
    rows: int = ...
    content_blake2b: str = ...
    status: str = ...
    duration_seconds: float = ...
def normalize_split_records(records: Sequence[Mapping[str, object]]) -> pd.DataFrame: ...
def normalize_dividend_records(records: Sequence[Mapping[str, object]]) -> pd.DataFrame: ...
def fetch_corporate_actions(config: CorporateActionsConfig) -> dict[ActionKind, pd.DataFrame]: ...
def write_corporate_actions(config: CorporateActionsConfig, frames: Mapping[ActionKind, pd.DataFrame]) -> list[CorporateActionsFileResult]: ...
def write_manifest(config: CorporateActionsConfig, results: Sequence[CorporateActionsFileResult]) -> Path: ...
def run(config: CorporateActionsConfig) -> list[CorporateActionsFileResult]: ...
def parse_args(argv: list[str]) -> CorporateActionsConfig: ...
def configure_logging(verbose: bool) -> None: ...
def main(argv: list[str]) -> int: ...
