from typing import Any

class YahooFinanceSource(DataSource):
    def __init__(self: Any, config: dict[str, Any] | None = ..., *, fetch_clock: Callable[[], datetime] | None = ...) -> None: ...
    async def get_historical(self: Any, symbol: str, start: str, end: str, *, eager: bool = ...) -> pl.LazyFrame | pl.DataFrame: ...
    async def get_realtime(self: Any, symbol: str, *, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
