from typing import Any

"""
AQ-09 ablation harness for explicit-label vs regime-embedding evidence.

This module provides a repeatable, schema-preserving comparison surface that:

1) evaluates downstream predictive utility per feature path,
2) computes RG-10 style representation diagnostics per path, and
3) reports deltas needed to assess whether ``regime_embedding`` adds evidence
   beyond explicit labels.

It does not reinterpret AQ-09 policy in code and does not make promotion claims.
"""

AQ09_ABLATION_REPORT_SCHEMA_VERSION: Final[str] = ...
EXPLICIT_LABEL_ARM_NAME: Final[str] = ...
REGIME_EMBEDDING_ARM_NAME: Final[str] = ...
COMBINED_ARM_NAME: Final[str] = ...
class AQ09AblationArm:
    name: str = ...
    features: np.ndarray[Any, np.dtype[np.float32]] = ...
def build_aq09_arms_from_tasks(tasks: Sequence[MetaTask], *, include_combined: bool = ...) -> tuple[list[AQ09AblationArm], list[str]]: ...
def run_aq09_ablation_harness(*, arms: Sequence[AQ09AblationArm], regime_labels: Sequence[str], downstream_targets: Sequence[int], seed: int = ..., n_splits: int = ...) -> dict[str, Any]: ...
def write_aq09_ablation_report(path: Path, report: Mapping[str, Any]) -> None: ...
