from typing import Any

"""
MLC-1 governed Phase II context encoder (2-layer MLP, D=64 ``regime_embedding``).

Trains only on contract-shaped :class:`EncoderInputContract` feature tensors (PIT metadata
is validated but not concatenated into the vector unless callers place PIT-safe features
inside ``regime_features`` per upstream policy).

**Contract-lowering shim (Phase II interface):** ``regime_features`` may be 1-D
``(input_dim,)`` or 2-D ``(T, F)``; the latter is flattened in C order to a length
``T * F`` vector that must equal ``input_dim``. This is not a second feature spec; it only
lowers the contract's ndarray into the fixed-width MLP input expected by the baseline
architecture.
"""

REGIME_EMBEDDING_DIM: Final[int] = ...
HIDDEN_DIM: Final[int] = ...
NUM_REGIME_CLASSES: Final[int] = ...
CONTEXT_ENCODER_DEFAULT_INPUT_DIM: Final[int] = ...
class ContextEncoderPretrainSummary:
    initial_loss: float = ...
    final_loss: float = ...
    epochs: int = ...
    n_examples: int = ...
class ContextEncoder:
    def __init__(self: Any, input_dim: int = ..., *, seed: int = ..., device: torch.device | str | None = ...) -> None: ...
    def input_dim(self: Any) -> int: ...
    def is_frozen(self: Any) -> bool: ...
    def freeze(self: Any) -> None: ...
    def unfreeze(self: Any) -> None: ...
    def encode(self: Any, input: EncoderInputContract) -> EncoderOutputContract: ...
    def pretrain_classifier(self: Any, examples: Sequence[tuple[EncoderInputContract, str]], *, epochs: int = ..., lr: float = ..., batch_size: int = ..., seed: int = ...) -> ContextEncoderPretrainSummary: ...
