from typing import Any

"""
MLC-1 encoder coherence diagnostics (RG-10 surfaces A–C, typed report v1).

This module computes the four governed scalar diagnostics and builds the
``encoder_coherence_report.json`` payload. Numeric pass/fail thresholds remain
``⚑ VALIDATE`` per RG-10; this code does not assert promotion decisions.
"""

CROSS_COSINE_RATIO_EPS: Final[float] = ...
ENCODER_COHERENCE_REPORT_SCHEMA_VERSION: Final[str] = ...
class EncoderCoherenceDiagnostics:
    within_cosine: float = ...
    cross_cosine: float = ...
    separation_ratio: float | None = ...
    separation_ratio_note: str | None = ...
    silhouette_score: float = ...
    class_counts: dict[str, int] = ...
def compute_encoder_coherence_diagnostics(embeddings: np.ndarray[Any, np.dtype[np.floating[Any]]], labels: Sequence[str]) -> EncoderCoherenceDiagnostics: ...
def build_encoder_coherence_report_payload(diagnostics: EncoderCoherenceDiagnostics, *, embedding_dim: int, n_tasks: int, producer: str, seed: int, notes: str, artifact_role: str = ...) -> dict[str, Any]: ...
def write_encoder_coherence_report(path: Path, payload: Mapping[str, Any]) -> None: ...
def encoder_coherence_report_from_arrays(embeddings: np.ndarray[Any, np.dtype[np.floating[Any]]], labels: Sequence[str], *, producer: str, seed: int, notes: str) -> dict[str, Any]: ...
