from typing import Any

"""
Append-only in-memory TaskRegistry (MLN-01).
"""

class AppendOnlyTaskRegistry:
    CONTRACT_VERSION: ClassVar[str] = ...
    def __init__(self: Any) -> None: ...
    def append(self: Any, task: MetaTask) -> None: ...
    def get(self: Any, task_id: str) -> MetaTask: ...
    def get_by_stable(self: Any, *, regime_id: str, t0: str) -> MetaTask: ...
    def query(self: Any, regime_id: str | None = ..., since: str | None = ...) -> list[MetaTask]: ...
    def to_records(self: Any) -> list[dict[str, Any]]: ...
