from typing import Any

"""
II-0C MetaTask scaffold helpers.

This module is intentionally narrow: it composes the canonical MLN-01
``build_meta_task`` contract with the existing task-manifest lowering path.
It does not define a new task schema or bypass the canonical support/query,
PIT, purge, embargo, or Dynamic-K checks.
"""

II0C_SCHEMATIC_VERSION: str = ...
class II0CMetaTaskRequest:
    regime_id: str = ...
    regime_class: str = ...
    support_set: Sequence[pd.Timestamp | str] = ...
    query_set: Sequence[pd.Timestamp | str] = ...
    horizon: int = ...
    signal_bindings: Mapping[int, str] = ...
    signal_set_version: str = ...
    regime_embedding: Sequence[float] | None = ...
    purge_window: pd.Timedelta = ...
    embargo_window: pd.Timedelta = ...
    pit_boundary: str | None = ...
    t0: str | None = ...
    t1: str | None = ...
class II0CMetaTaskPayload:
    meta_task: MetaTask = ...
    task_manifest_input: TaskManifestTaskInput = ...
    task_record: dict[str, object] = ...
def build_ii0c_meta_task_payload(request: II0CMetaTaskRequest) -> II0CMetaTaskPayload: ...
def build_ii0c_signal_surface(slot_to_signal_id: Mapping[int, str], *, max_signals: int = ...) -> tuple[tuple[str, ...], tuple[bool, ...]]: ...
def build_ii0c_task_inputs(*, regime_id: str, regime_class: str, regime_embedding: Sequence[float] | None, support_set: Sequence[pd.Timestamp | str], query_set: Sequence[pd.Timestamp | str], horizon: int, slot_to_signal_id: Mapping[int, str], signal_set_version: str, t0: str, t1: str, purge_window: pd.Timedelta, embargo_window: pd.Timedelta, pit_boundary: str | None = ...) -> tuple[MetaTask, TaskManifestTaskInput]: ...
def build_ii0c_meta_task(*, regime_id: str, regime_class: str, regime_embedding: Sequence[float] | None, support_set: Sequence[pd.Timestamp | str], query_set: Sequence[pd.Timestamp | str], horizon: int, slot_to_signal_id: Mapping[int, str], signal_set_version: str, t0: str, t1: str, purge_window: pd.Timedelta, embargo_window: pd.Timedelta, pit_boundary: str | None = ...) -> MetaTask: ...
def build_ii0c_task_manifest_input(*, regime_id: str, regime_class: str, regime_embedding: Sequence[float] | None, support_set: Sequence[pd.Timestamp | str], query_set: Sequence[pd.Timestamp | str], horizon: int, slot_to_signal_id: Mapping[int, str], signal_set_version: str, t0: str, t1: str, purge_window: pd.Timedelta, embargo_window: pd.Timedelta, pit_boundary: str | None = ...) -> TaskManifestTaskInput: ...
