from typing import Any

"""
Frozen II-0C reference inputs for harness drift detection (non-promotable).

This bundle pins one canonical task surface, timestamp, and seed line so repeated runs can
assert stable identities. It proves harness wiring stability only — not encoder validity,
trainer readiness, or promotable Phase II behavior.
"""

II0C_REFERENCE_SEED: Final[int] = ...
II0C_REFERENCE_TIMESTAMP_UTC: Final[str] = ...
II0C_REFERENCE_SIGNAL_SET_VERSION: Final[str] = ...
II0C_REFERENCE_REGIME_ID: Final[str] = ...
def build_ii0c_reference_meta_task_request() -> II0CMetaTaskRequest: ...
def build_ii0c_reference_encoder_config() -> Phase2II0CEncoderConfig: ...
