from typing import Any

"""
II-0C challenger-vs-incumbent comparison plumbing.

This module is intentionally narrow. It builds the comparison payloads that feed the governed
Phase II artifact contract and enforces the baseline boundary:

- incumbent baseline kind is ``xgboost_incumbent``
- RG-09 / strict-H3 / task-validity anchor strings are rejected on the baseline lane
- comparison parity must be explicit and matched across baseline and shared context

Nothing here claims promotability or replaces the governed artifact contract.
"""

XGBOOST_INCUMBENT_BASELINE_KIND: str = ...
NOT_EVALUATED_NON_PROMOTABLE: str = ...
II0C_COMPARISON_LANE: str = ...
GOVERNED_BASELINE_COMPARISON_KEYS: frozenset[str] = ...
class Phase2II0CComparisonError(ValueError):
    ...
class Phase2II0CComparisonSpec:
    challenger_run_id: str = ...
    baseline_run_id: str = ...
    splits_fingerprint: str = ...
    data_fingerprint: str = ...
    cost_assumptions_fingerprint: str = ...
    baseline_kind: str = ...
    data_parity: bool = ...
    split_parity: bool = ...
    cost_parity: bool = ...
    net_result_against_incumbent: str = ...
class Phase2II0CComparisonBundle:
    baseline_comparison: dict[str, Any] = ...
    shared_comparison_context: dict[str, Any] = ...
class II0CComparisonContext:
    baseline_run_id: str = ...
    challenger_run_id: str = ...
    incumbent_data_fingerprint: str = ...
    challenger_data_fingerprint: str = ...
    incumbent_splits_fingerprint: str = ...
    challenger_splits_fingerprint: str = ...
    incumbent_cost_assumptions_fingerprint: str = ...
    challenger_cost_assumptions_fingerprint: str = ...
    baseline_kind: str = ...
    net_result_against_incumbent: str = ...
def validate_phase2_ii0c_comparison_spec(spec: Phase2II0CComparisonSpec) -> None: ...
def build_phase2_ii0c_baseline_comparison(spec: Phase2II0CComparisonSpec) -> dict[str, Any]: ...
def build_phase2_ii0c_shared_comparison_context(spec: Phase2II0CComparisonSpec) -> dict[str, Any]: ...
def build_phase2_ii0c_comparison_bundle(spec: Phase2II0CComparisonSpec) -> Phase2II0CComparisonBundle: ...
def validate_ii0c_governed_baseline_and_shared_context(*, baseline_comparison: Mapping[str, Any], shared_comparison_context: Mapping[str, Any]) -> None: ...
def build_ii0c_comparison_payload(context: II0CComparisonContext) -> Phase2II0CComparisonBundle: ...
