from typing import Any

"""
II-0C encoder stub / reference scaffold.

This module intentionally provides a deterministic, versioned encoder surface without claiming
validated representation quality. It is a scaffold for governed II-0C wiring, not a promoted
encoder path.
"""

II0C_ENCODER_SCHEMA_VERSION: Final[str] = ...
II0C_ENCODER_REPORT_SCHEMA_VERSION: Final[str] = ...
II0C_ENCODER_VERSION: Final[str] = ...
II0C_ENCODER_EMBEDDING_DIM: Final[int] = ...
class Phase2II0CEncoderConfig:
    seed: int = ...
    embedding_dim: int = ...
    schema_version: str = ...
    encoder_version: str = ...
    report_schema_version: str = ...
    ablation_flags: tuple[str, ...] = ...
    scaffold_only: bool = ...
    reference_only: bool = ...
class II0CEncoderTaskOutput:
    embedding: tuple[float, ...] = ...
    metadata: dict[str, Any] = ...
class II0CEncoderStub:
    def __init__(self: Any, config: Phase2II0CEncoderConfig | None = ...) -> None: ...
    def config(self: Any) -> Phase2II0CEncoderConfig: ...
    def is_frozen(self: Any) -> bool: ...
    def encode_task(self: Any, task: MetaTask) -> II0CEncoderTaskOutput: ...
    def encode(self: Any, input: EncoderInputContract) -> EncoderOutputContract: ...
    def build_metadata(self: Any, *, input: EncoderInputContract, output: EncoderOutputContract | None = ...) -> dict[str, Any]: ...
def build_phase2_ii0c_encoder_metadata(*, input: EncoderInputContract, output: EncoderOutputContract | None = ..., config: Phase2II0CEncoderConfig | None = ...) -> dict[str, Any]: ...
