from typing import Any

"""
MLN-02 canonical regime vocabulary and Level-2 projection (single source of truth).

**Identity (Architecture Vision / Resolution Ledger)**

- ``regime_id`` — Level-1 **primary** compositional task identity (e.g. ``trend_*__vol_*__bocpd_*``).
  It is **not** interchangeable with ``regime_class``.
- ``regime_class`` — Level-2 **derived** 5-class projection for curriculum, supervision, diagnostics,
  and reporting only.

**Fixed 5-class vocabulary (no aliases)**

``bull``, ``bear``, ``sideways``, ``high_vol``, ``crisis``.

**Default Level-2 crisis rule (MLN-02-AMD-01)**

``crisis := vol_hi AND severity_flag``, where ``severity_flag`` is a PIT-safe gate on
``vol_score_raw`` vs an expanding-window percentile of strict past history (default **p90** under
assumption **RG09-V12**, configurable via ``BOCPDConfig.crisis_vol_score_percentile``).
**BOCPD is not part of this rule.**

**BOCPD role**

BOCPD remains a Level-1 compositional dimension inside ``regime_id`` and a **segmentation /
reference** primitive. The function :func:`project_regime_class_bocpd_reference` is the **explicit
II-0A empirical reference condition** (``crisis := vol_hi AND bocpd_cp``). It is **not** governed
default truth for Level-2 ``regime_class``.

**Projection-rule versioning (holdout / GATE-II-01 hook)**

Use :func:`projection_rule_version_id` (and optionally :func:`projection_rule_display`) in fixture
summaries and diagnostics so Anti-Goodhart holdout manifests can bind to a **machine-stable** rule
id independent of human-readable text.
"""

RegimeClassLabel: Any
TrendBucket: Any
VolBucket: Any
BocpdState: Any
REGIME_CLASS_BULL: RegimeClassLabel = ...
REGIME_CLASS_BEAR: RegimeClassLabel = ...
REGIME_CLASS_SIDEWAYS: RegimeClassLabel = ...
REGIME_CLASS_HIGH_VOL: RegimeClassLabel = ...
REGIME_CLASS_CRISIS: RegimeClassLabel = ...
REGIME_CLASSES: Final[frozenset[str]] = ...
REGIME_CLASS_ORDER: Final[tuple[str, ...]] = ...
VOL_RISING_REGIME_CLASSES: Final[frozenset[str]] = ...
TREND_STABLE_REGIME_CLASSES: Final[frozenset[str]] = ...
PROJECTION_RULE_LOGIC_ID_DEFAULT: Final[str] = ...
PROJECTION_RULE_REFERENCE_BOCPD_ID: Final[str] = ...
PROJECTION_RULE_EXTENDED_ABLATION_ID: Final[str] = ...
DEFAULT_CRISIS_VOL_SCORE_PERCENTILE: Final[float] = ...
def projection_rule_display(*, severity_percentile: float) -> str: ...
def projection_rule_version_id(*, severity_percentile: float) -> str: ...
def validate_regime_class(value: str) -> RegimeClassLabel: ...
def is_valid_compositional_regime_id(regime_id: str) -> bool: ...
def validate_compositional_regime_id(regime_id: str) -> str: ...
def validate_meta_task_regime_id(regime_id: str) -> str: ...
def validate_row_count_dict_keys(counts: Mapping[str, int]) -> dict[str, int]: ...
def project_regime_class(trend: TrendBucket, vol: VolBucket, bocpd_state: BocpdState, *, severity_flag: bool) -> RegimeClassLabel: ...
def project_regime_class_bocpd_reference(trend: TrendBucket, vol: VolBucket, bocpd_state: BocpdState) -> RegimeClassLabel: ...
def project_regime_class_extended_ablation(trend: TrendBucket, vol: VolBucket, bocpd_state: BocpdState) -> RegimeClassLabel: ...
