from typing import Any

"""
MLN-01 canonical MetaTask construction — single permitted constructor for governed tasks.

A **task** is a regime episode: support/query temporal geometry, signal identity, and PIT boundary
are validated here. Do not instantiate :class:`MetaTask` except via :func:`build_meta_task`.

MLN-02: ``regime_id`` is primary identity (token validation); ``regime_class`` is validated against
the five canonical Level-2 labels via :mod:`pysrc.meta_learning.regime_vocabulary`.

HMAC key contract (frozen for MLN-01 closure)
--------------------------------------------
``task_id = HMAC-SHA256(key, regime_id || t0 || t1 || signal_ids_hash)`` with **SHA-256**.

- **Key version:** :data:`TASK_ID_HMAC_KEY_VERSION`
- **Key material:** :data:`TASK_ID_HMAC_KEY_MATERIAL` is the empty byte string ``b""`` (RG09-V13).

Any change to key material or message format **invalidates all historical** ``task_id`` values
unless a governed migration policy exists. This is intentional: identity is content-addressed,
not secret-dependent.
"""

LOG: Any
TASK_ID_HMAC_KEY_VERSION: Final[str] = ...
TASK_ID_HMAC_KEY_MATERIAL: Final[bytes] = ...
def compute_task_id(*, regime_id: str, t0: str, t1: str, signal_ids_hash: str) -> str: ...
def derive_signal_ids_hash(*, signal_ids: tuple[str, ...], signal_mask: tuple[bool, ...]) -> str: ...
class MetaTask:
    task_id: str = ...
    regime_id: str = ...
    regime_class: str = ...
    regime_embedding: tuple[float, ...] | None = ...
    support_set: tuple[str, ...] = ...
    query_set: tuple[str, ...] = ...
    horizon: int = ...
    signal_ids: tuple[str, ...] = ...
    signal_mask: tuple[bool, ...] = ...
    signal_set_version: str = ...
    signal_ids_hash: str = ...
    pit_boundary: str = ...
    t0: str = ...
    t1: str = ...
    active_k: int = ...
def build_meta_task(*, regime_id: str, regime_class: str, regime_embedding: Sequence[float] | None, support_set: Sequence[pd.Timestamp | str], query_set: Sequence[pd.Timestamp | str], horizon: int, signal_ids: Sequence[str], signal_mask: Sequence[bool], signal_set_version: str, t0: str, t1: str, purge_window: pd.Timedelta, embargo_window: pd.Timedelta, pit_boundary: str | None = ...) -> MetaTask: ...
def meta_task_to_task_manifest_input(task: MetaTask) -> TaskManifestTaskInput: ...
def meta_task_to_record(task: MetaTask) -> dict[str, Any]: ...
def meta_task_from_record(record: Mapping[str, Any]) -> MetaTask: ...
