from typing import Any

def tune(objective_fn: Callable[[ParamPoint], float], space: Union[SearchSpace, Dict[str, Any], List[Dict[str, Any]]], *, engine: str = ..., direction: ObjectiveDirection = ..., budget: int = ..., cv: int = ..., scoring: Optional[str] = ..., seed: Optional[int] = ..., **engine_kwargs: Any) -> TuningResult: ...
def create_tuner(spec: TunerSpec) -> Callable[[SearchSpace, Callable[[ParamPoint], float]], TuningResult]: ...
