from typing import Any

"""
Hyperparameter search coordination.

Typed contracts for search space definition, trial execution,
and result aggregation. Integrates with autotune API and
artifact registry for full lineage tracking.
"""

T: Any
class Trial:
    trial_id: str = ...
    params: Mapping[str, Any] = ...
    metric: float = ...
    metadata: Mapping[str, float] | None = ...
class SearchState:
    completed: int = ...
    best_trial: Trial | None = ...
    history: Sequence[Trial] = ...
class SearchAlgorithm(ABC, Generic[T]):
    def suggest(self: Any, state: SearchState, space: SearchSpace) -> Mapping[str, T]: ...
    def update(self: Any, state: SearchState, trial: Trial) -> SearchState: ...
class HparamSearch(ABC):
    def execute(self: Any, objective: Callable[..., float], space: SearchSpace, algorithm: SearchAlgorithm[Any], *, max_trials: int, early_stop_patience: int = ...) -> TuningResult: ...
    def resume(self: Any, run_id: str) -> TuningResult: ...
