from typing import Any

class SearchSpace:
    def params(self: Any) -> List[_ParamDef]: ...
    def iter_grid(self: Any) -> Iterable[ParamPoint]: ...
    def sample(self: Any, n: int, rng: _random_module.Random) -> List[ParamPoint]: ...
    def to_optuna_space(self: Any) -> Dict[str, List[Any]]: ...
    def to_skopt_space(self: Any) -> List[Any]: ...
def normalize_space(raw: Any) -> SearchSpace: ...
