from typing import Any

ObjectiveDirection: Any
ParamValue: Any
ParamPoint: Any
class TunerSpec:
    engine: str = ...
    direction: ObjectiveDirection = ...
    budget: int = ...
    cv: int = ...
    scoring: Optional[str] = ...
    seed: Optional[int] = ...
    engine_kwargs: Dict[str, Any] = ...
class TrialRecord:
    params: ParamPoint = ...
    score: float = ...
    metadata: Dict[str, Any] = ...
class TuningResult:
    best_params: ParamPoint = ...
    best_score: float = ...
    best_model: Optional[Any] = ...
    trials: List[TrialRecord] = ...
    engine: str = ...
    direction: ObjectiveDirection = ...
    metadata: Dict[str, Any] = ...
class TuningEngine:
    ...
