from typing import Any

"""
Typed API-layer errors and mapping from domain errors to API errors.

Provides a thin translation layer so domain exceptions never leak through the HTTP boundary.
"""

class APIError(Exception):
    status_code: int = ...
    detail: str = ...
    def __init__(self: Any, detail: str, status_code: int = ...) -> None: ...
class JobNotFoundError(APIError):
    status_code: Any
    def __init__(self: Any, detail: str) -> None: ...
class InvalidRequestError(APIError):
    status_code: Any
    def __init__(self: Any, detail: str) -> None: ...
class GateFailedError(APIError):
    status_code: Any
    def __init__(self: Any, detail: str) -> None: ...
def map_domain_error(exc: Exception) -> APIError: ...
