from typing import Any

"""
Pydantic request/response boundary models for the tuning API.

Layer rule: API boundary only — no domain logic.
"""

class TuningJobRequest(BaseModel):
    model_config: Any
    job_id: str = ...
    search_space_ref: str = ...
    objective_ref: str = ...
    validation_ref: str = ...
    promotion_ref: str | None = ...
    max_trials: int = ...
    timeout_seconds: int | None = ...
    tags: dict[str, str] = ...
class TuningJobResponse(BaseModel):
    model_config: Any
    job_id: str = ...
    status: str = ...
    run_id: str | None = ...
class PromotionRequest(BaseModel):
    model_config: Any
    job_id: str = ...
    candidate_id: str = ...
    mode: str = ...
class PromotionResponse(BaseModel):
    model_config: Any
    job_id: str = ...
    candidate_id: str = ...
    promotion_id: str = ...
    status: str = ...
class SearchStatusResponse(BaseModel):
    model_config: Any
    job_id: str = ...
    status: str = ...
    trials_complete: int = ...
    best_score: float | None = ...
class GateResultResponse(BaseModel):
    model_config: Any
    job_id: str = ...
    candidate_id: str = ...
    passed: bool = ...
    gate_scores: dict[str, float] = ...
