from typing import Any

class StreamingIsolationForest:
    def __init__(self: Any, contamination: float, refit_every: int, window_size: int = ..., *, random_state: int = ...) -> Any: ...
    def predict(self: Any, df: pl.DataFrame) -> np.ndarray: ...
class StreamingAnomalyParams(BaseModel):
    model_config: Any
    contamination: float = ...
    refit_every: int = ...
    window_size: int = ...
class StreamingAnomalyNormalizerStep(CleaningStep):
    ...
