from typing import Any

"""
Schema-owned builder for ``meta_validity_report``-shaped dicts (MLC-3).

Every trainer run (PASS or FAIL) must emit a structurally complete JSON-safe
payload. Missing semantics are represented as ``null``, not omitted keys.

``inner_loop_gain`` is a nested object (not a bare float) with nullable slots for
Harvey t and per-regime breakdowns until later gate evidence exists.
"""

REQUIRED_TOP_LEVEL_KEYS: frozenset[str] = ...
INNER_LOOP_GAIN_KEYS: frozenset[str] = ...
TASK_POOL_COUNTS_REQUIRED: frozenset[str] = ...
TASK_POOL_COUNTS_OPTIONAL: frozenset[str] = ...
CONFIDENCE_CALIBRATION_KEYS: frozenset[str] = ...
class MetaValidityReportBuildError(ValueError):
    ...
def validate_inner_loop_gain_block(obj: Any) -> dict[str, Any]: ...
def validate_task_pool_counts_block(obj: Any) -> dict[str, Any]: ...
def validate_confidence_calibration_block(obj: Any) -> dict[str, Any] | None: ...
def validate_meta_validity_report_keys(payload: Mapping[str, Any]) -> None: ...
def scaffold_inner_loop_gain(*, mean_query_ic: float | None = ..., harvey_t: float | None = ..., by_regime_class: dict[str, float] | None = ...) -> dict[str, Any]: ...
def scaffold_task_pool_counts(*, batch_size: int, crisis_count: int, crisis_required: int, bucket_counts: Mapping[str, int], phase: str | None = ...) -> dict[str, Any]: ...
def scaffold_confidence_calibration(*, ece: float | None = ..., note: str | None = ...) -> dict[str, Any]: ...
def build_meta_validity_report(*, schema_version: str, run_id: str, overall_result: str, reporting_gate: str, inner_loop_gain: Mapping[str, Any] | None, shuffle_test_p_value: float | None, proxy_IC_pearson_r: float | None, crisis_holdout_ic: float | None, forgetting_ic_degradation_pct: float | None, task_pool_counts: Mapping[str, Any] | None, confidence_calibration: Mapping[str, Any] | None, fail_reasons: list[str], theta_day_prime_promoted: bool, timestamp_utc: str | None = ...) -> dict[str, Any]: ...
class MetaValidityReportBuilder:
    schema_version: str = ...
    run_id: str = ...
    overall_result: str = ...
    reporting_gate: str = ...
    inner_loop_gain: dict[str, Any] = ...
    shuffle_test_p_value: float | None = ...
    proxy_IC_pearson_r: float | None = ...
    crisis_holdout_ic: float | None = ...
    forgetting_ic_degradation_pct: float | None = ...
    task_pool_counts: dict[str, Any] | None = ...
    confidence_calibration: dict[str, Any] | None = ...
    fail_reasons: list[str] = ...
    theta_day_prime_promoted: bool = ...
    timestamp_utc: str | None = ...
    def build(self: Any) -> dict[str, Any]: ...
