from typing import Any

log: Any
class IBKRConfig(BaseModel):
    host: str = ...
    port: int = ...
    client_id: int = ...
def get_ibkr_config() -> Any: ...
def ibkr_connection() -> Iterator[IBKR]: ...
