from typing import Any

logger: Any
class NoDataError(DataFetchError):
    def __init__(self: Any, symbol: str) -> Any: ...
def create_mock_bars(n: int, start_date: str = ...) -> List[BarData]: ...
def fetch_historical_data(symbol: str, end_date: str = ..., duration: str = ..., bar_size: str = ..., ibkr_client: Optional[IBKR] = ..., use_cache: bool = ..., what_to_show: str = ..., use_rth: bool = ..., format_date: int = ...) -> pd.DataFrame: ...
async def fetch_multiple_historical_data(symbols: List[str], end_date: str = ..., duration: str = ..., bar_size: str = ..., use_cache: bool = ..., what_to_show: str = ..., use_rth: bool = ..., format_date: int = ...) -> Dict[str, pd.DataFrame]: ...
