from typing import Any

pd: Any
def create_mock_bars(n: int, start_date: str = ...) -> Any: ...
class NoDataError(RuntimeError):
    ...
def ib_connection(*args: Any, **kwargs: Any) -> Any: ...
def fetch_historical_data(symbol: str, end_datetime: str, *, duration: str = ..., bar_size: str = ..., what_to_show: str = ..., use_cache: bool = ..., ib_client: Optional[object] = ...) -> Any: ...
