from typing import Any

class IBKROrderExecutor(OrderExecutor):
    def __init__(self: Any, conn_cfg: Any) -> Any: ...
    def submit(self: Any, order: Order) -> str: ...
    def cancel(self: Any, order_id: str) -> None: ...
    def status(self: Any, order_id: str) -> str: ...
