from typing import Any

class HedgeEstimator(str, Enum):
    OLS: Any
    KALMAN: Any
class PairsConfig:
    method: str = ...
    entry_z: float = ...
    exit_z: float = ...
    max_hold_days: int = ...
    beta_window: int = ...
    half_life_window: int = ...
    zscore_window: int = ...
    min_half_life: float = ...
    max_half_life: float = ...
    hedge_estimator: HedgeEstimator = ...
PAIRS_DEFAULT: Any
