from typing import Any

class StatArbRunConfig:
    leg_a: str = ...
    leg_b: str = ...
    start: str = ...
    end: str = ...
    config: PairsConfig = ...
    bundle_dir: Path | None = ...
    prices: pd.DataFrame | None = ...
def run_stat_arb_pairs(leg_a: str, leg_b: str, *, run_cfg: StatArbRunConfig) -> RunBundle: ...
