from typing import Any

class StatArbPairsStrategy(PipelineStrategy):
    def __init__(self: Any, leg_a: str, leg_b: str, config: PairsConfig | None = ..., **params: object) -> None: ...
    def features_plan(self: Any) -> FeaturePlan: ...
    def generate_signal(self: Any, features: Union[pd.DataFrame, object]) -> pd.Series: ...
    def write_artifacts(self: Any, store: 'BundleBacktestArtifactStore', *, signals: pd.Series | None = ..., feats: pd.DataFrame | None = ..., run_id: str | None = ..., evaluation_window: str = ..., **kwargs: object) -> None: ...
