from typing import Any

class Admissibility(str, Enum):
    ADMIT: Any
    REJECT: Any
class FailureClass(str, Enum):
    CONTRACT_VIOLATION: Any
    CAPABILITY_REJECTION: Any
    RETRYABLE_OPERATIONAL_FAILURE: Any
    NON_GOVERNED_COMPATIBILITY_PATH: Any
class DowngradePolicy(str, Enum):
    NONE_ALLOWED: Any
    EXPLICIT_APPROVAL_REQUIRED: Any
class MaterializationPolicy(str, Enum):
    EXACT_DECLARED_ONLY: Any
    EXPLICIT_CHANGE_REQUIRED: Any
class RetryPolicyClass(str, Enum):
    NONE: Any
    SAME_SEMANTICS_ONLY: Any
class GovernanceDecision:
    admissibility: Admissibility = ...
    reasons: tuple[str, ...] = ...
    failure_class: FailureClass | None = ...
    downgrade_policy: DowngradePolicy = ...
    materialization_policy: MaterializationPolicy = ...
    retry_policy: RetryPolicyClass = ...
    governed: bool = ...
    def admit(cls: Any, reason: str, *, governed: bool = ...) -> 'GovernanceDecision': ...
    def reject(cls: Any, reason: str, *, failure_class: FailureClass = ..., governed: bool = ...) -> 'GovernanceDecision': ...
def validate_fail_closed_defaults(decision: GovernanceDecision) -> GovernanceDecision: ...
def require_governed_admissible(decision: GovernanceDecision) -> GovernanceDecision: ...
