from typing import Any

logger: Any
class StepRegistry:
    def register(cls: Any, *args: Any, override: bool = ...) -> None: ...
    def get(cls: Any, stage: str, name: str) -> Type[PipelineStep]: ...
    def load_plugins(cls: Any, entry_point_group: str, stage: str) -> None: ...
