from typing import Any

class PipelineMetricsError(Exception):
    ...
class MLflowUnavailable(PipelineMetricsError):
    ...
ERROR_COUNTER: Any
STEP_EXECUTION_TIME: Any
mlflow: Any
class AsyncMLflowLogger:
    def __init__(self: Any) -> None: ...
    async def log_metrics(self: Any, metrics: Dict[str, float], *, step: Optional[int] = ...) -> None: ...
    async def log_params(self: Any, params: Dict[str, Any]) -> None: ...
    async def set_experiment(self: Any, name: str) -> None: ...
    async def start_run(self: Any, *, run_name: Optional[str] = ..., nested: bool = ..., tags: Optional[Dict[str, str]] = ...) -> Any: ...
    async def end_run(self: Any) -> None: ...
    async def log_artifact(self: Any, local_path: str, *, artifact_path: Optional[str] = ...) -> None: ...
def track_step_execution(step_name: str, *, stage: str = ..., engine: str = ...) -> Any: ...
def wire_streaming_observers(get_buffer_len: Callable[[], int] | None, get_processed_volume: Callable[[], int] | None) -> None: ...
