from typing import Any

"""
Defines PipelineStep ABC (Polars-first), DataError hierarchy, and infra.
"""

pd: Any
pl: Any
InT: Any
OutT: Any
Engine: Any
class PipelineError(Exception):
    code: Any
    def to_dict(self: Any) -> dict: ...
class PipelineGraphError(PipelineError):
    code: Any
class PipelineConfigError(PipelineError):
    code: Any
class ErrorCode(Enum):
    MISSING_DATA: Any
    INVALID_SCHEMA: Any
    OUTLIER_DETECTED: Any
    DRIFT_DETECTED: Any
    PROCESSING_FAILURE: Any
    RESOURCE_EXHAUSTED: Any
class DataError(Exception):
    def __init__(self: Any, message: str, code: ErrorCode, details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def to_dict(self: Any) -> Dict[str, Any]: ...
class MissingDataError(DataError):
    ...
class InvalidSchemaError(DataError):
    ...
class DataSource(ABC):
    def __init__(self: Any, config: Any) -> Any: ...
    async def load_data(self: Any, *args: Any, **kwargs: Any) -> pl.DataFrame: ...
    async def stream_data(self: Any) -> AsyncIterable[pl.DataFrame]: ...
class PipelineStep(Generic[InT, OutT], ABC):
    STEP_NAME: Any
    STEP_VERSION: Any
    requires: Set[str] = ...
    produces: Set[str] = ...
    preferred_engine: Optional[Engine] = ...
    def __init__(self: Any, name: Optional[str] = ..., **_: Any) -> Any: ...
    async def execute(self: Any, data: Any, context: 'PipelineContext') -> Any: ...
    def apply_batch(self: Any, lf: 'pl.LazyFrame', ctx: PipelineContext) -> 'pl.LazyFrame': ...
    def apply_batch_pandas(self: Any, df: 'pd.DataFrame', ctx: PipelineContext) -> 'pd.DataFrame': ...
    async def apply_stream(self: Any, aiter: AsyncIterator[dict], ctx: PipelineContext) -> AsyncIterator[dict]: ...
    def compose(cls: Any, *steps: 'PipelineStep') -> 'CompositeStep': ...
class CompositeStep(PipelineStep):
    def __init__(self: Any, steps: List[PipelineStep], **kwargs: Any) -> Any: ...
    def apply_batch(self: Any, lf: 'pl.LazyFrame', ctx: PipelineContext) -> 'pl.LazyFrame': ...
