from typing import Any

def choose_combo(cfg: Any, ctx: Any, name: str = ...) -> Any: ...
def topo_order(steps: List[str], order_cfg: Dict[str, Dict[str, List[str]]]) -> List[str]: ...
class PipelineBuilder:
    def __init__(self: Any, stage: str, config: Optional[Dict[str, Any]] = ...) -> Any: ...
    def for_stage(cls: Any, stage: str, config: Optional[Dict[str, Any]] = ...) -> 'PipelineBuilder': ...
    def from_preset_and_params(self: Any, preset: Dict[str, Any], params: Dict[str, Any]) -> 'PipelineBuilder': ...
    def add_steps(self: Any, steps: Any) -> Any: ...
    def build(self: Any) -> 'Pipeline': ...
    def validate_contracts(self: Any) -> 'PipelineBuilder': ...
class Pipeline:
    def __init__(self: Any, steps: List[PipelineStep], config: Dict[str, Any]) -> Any: ...
    def fit_transform(self: Any, df: Any) -> Any: ...
