from typing import Any

"""
Manages PipelineContext (e.g., frequency inference, indicator flags).
"""

pd: Any
pl: Any
TimeFreq: Any
class PipelineContext:
    frequency: TimeFreq = ...
    asset_class: str = ...
    latency: Literal['ultra', 'low', 'batch'] = ...
    streaming: bool = ...
    time_col: str = ...
    df: Optional[Union[pl.DataFrame, pl.LazyFrame, pd.DataFrame]] = ...
    assume_sorted: bool = ...
    sample: int = ...
    backend: Optional[str] = ...
    executor: Optional[str] = ...
    optimize: bool = ...
    cache: bool = ...
    def as_lazy(self: Any) -> Optional['pl.LazyFrame']: ...
    def infer_frequency(self: Any) -> TimeFreq: ...
    def refine(self: Any, **kwargs: Any) -> PipelineContext: ...
