from typing import Any

LOG: Any
class BacktestResult:
    total_return: float = ...
    sharpe_ratio: float = ...
    max_drawdown: float = ...
    win_rate: float = ...
    num_trades: int = ...
    def to_dict(self: Any) -> dict[str, float | int]: ...
def run_backtest(df: pl.DataFrame, fast_sma: int = ..., slow_sma: int = ...) -> BacktestResult: ...
class VectorizedBacktestEngine:
    def run(self: Any, plan: BacktestPlan, data: PITSafeDataView | PitUnsafeFrame, store: BundleBacktestArtifactStore | None) -> CoreBacktestResult: ...
