from typing import Any

"""
Pydantic v2 contracts for the entire P2 broad-reset pipeline.
All JSON artifacts must validate against these models (or thin wrappers).
"""

SurfaceStatus: Any
ModelStatus: Any
CandidateStatus: Any
RouterTarget: Any
DecisionRule: Any
NarrowClassification: Any
SplitPolicy: Any
FeaturePolicy: Any
NarrowDataMode: Any
class RunPhase(StrEnum):
    MAP: Any
    MATRIX: Any
    NARROW: Any
    FULL: Any
class RunMetadata(BaseModel):
    model_config: Any
    run_id: str = ...
    timestamp: datetime = ...
    phase: RunPhase = ...
    git_commit: str | None = ...
    python_version: str | None = ...
    random_seed: int = ...
    config_hash: str | None = ...
    notes: str = ...
class PrimaryDataPanelEntry(BaseModel):
    model_config: Any
    surface_id: str = ...
    provider: str = ...
    dataset_name: str = ...
    path: str = ...
    date_start: str = ...
    date_end: str = ...
    row_count: int = ...
    instrument_count: int = ...
    trading_day_count: int = ...
    status: Literal['available_primary', 'blocked_dependency_missing'] = ...
    adjusted_prices_for: list[str] = ...
    raw_prices_volume_for: list[str] = ...
    pit_safe: bool = ...
    reason: str | None = ...
class DerivedSupervisionSurfaceEntry(BaseModel):
    model_config: Any
    surface_id: str = ...
    family: str = ...
    status: SurfaceStatus = ...
    supervision_path: str | None = ...
    bundle_id: str | None = ...
    bundle_surface_id: str | None = ...
    schema_version: str = ...
    derived_from_panel: str = ...
    role: Literal['primary_narrow', 'stress_report_only', 'embedded_features'] = ...
    reason: str | None = ...
    pit_safe: bool = ...
class SurfaceRegistryEntry(BaseModel):
    model_config: Any
    surface_id: str = ...
    family: str = ...
    status: SurfaceStatus = ...
    reason: str | None = ...
    path: str | None = ...
    row_count: int | None = ...
    feature_count: int | None = ...
    available_at_decision_time: bool = ...
    pit_safe: bool = ...
    columns_sample: list[str] = ...
    derived_from_panel: str | None = ...
class ModelFamilyEntry(BaseModel):
    model_config: Any
    name: str = ...
    status: ModelStatus = ...
    reason: str | None = ...
    supported_router_targets: list[RouterTarget] = ...
    supported_decision_rules: list[DecisionRule] = ...
    requires_extra: list[str] = ...
    default_hyperparams: dict[str, Any] = ...
class SignalFamilyEntry(BaseModel):
    model_config: Any
    family: str = ...
    signals: list[str] = ...
    status: SurfaceStatus = ...
    reason: str | None = ...
class ArchitectureMap(BaseModel):
    model_config: Any
    meta: RunMetadata = ...
    primary_panel: PrimaryDataPanelEntry | None = ...
    derived_surfaces: list[DerivedSupervisionSurfaceEntry] = ...
    surfaces: list[SurfaceRegistryEntry] = ...
    summary: dict[str, Any] = ...
class ModelFamilyRegistry(BaseModel):
    model_config: Any
    meta: RunMetadata = ...
    families: list[ModelFamilyEntry] = ...
class SignalFamilyRegistry(BaseModel):
    model_config: Any
    meta: RunMetadata = ...
    families: list[SignalFamilyEntry] = ...
class SurfaceMarketRegistry(BaseModel):
    model_config: Any
    meta: RunMetadata = ...
    primary_panel: PrimaryDataPanelEntry | None = ...
    surfaces: list[SurfaceRegistryEntry] = ...
    blocked_count: int = ...
    available_count: int = ...
    available_primary_count: int = ...
class CandidateSpec(BaseModel):
    model_config: Any
    candidate_id: str = ...
    model_family: str = ...
    router_target: RouterTarget = ...
    decision_rule: DecisionRule = ...
    input_surface: str = ...
    feature_allowlist: list[str] | FeaturePolicy = ...
    forbidden_features: list[str] = ...
    comparators: list[str] = ...
    split_policy: SplitPolicy = ...
    status: CandidateStatus = ...
    reason: str | None = ...
    hyperparams: dict[str, Any] = ...
    created_by: str = ...
    supervision_path: str | None = ...
    feature_policy: FeaturePolicy = ...
class CandidateMatrix(BaseModel):
    model_config: Any
    meta: RunMetadata = ...
    candidates: list[CandidateSpec] = ...
    summary: dict[str, Any] = ...
class SurfaceStressResult(BaseModel):
    model_config: Any
    evaluated: bool = ...
    reason: str | None = ...
    utility: float | None = ...
class BaselineMetrics(BaseModel):
    model_config: Any
    name: str = ...
    test_utility: float = ...
    test_sharpe_like: float | None = ...
    win_rate_vs_cash: float | None = ...
    notes: str = ...
class CandidateResult(BaseModel):
    model_config: Any
    candidate_id: str = ...
    test_utility: float = ...
    best_child_test_utility: float = ...
    delta_vs_best_child: float = ...
    classification: NarrowClassification = ...
    robustness_passed: bool = ...
    stress_surface_c: SurfaceStressResult = ...
    notes: str = ...
    metrics: dict[str, float] = ...
class NarrowingReport(BaseModel):
    model_config: Any
    meta: RunMetadata = ...
    input_surface: str = ...
    n_candidates_evaluated: int = ...
    n_survivors: int = ...
    best_child_baseline: BaselineMetrics = ...
    other_baselines: list[BaselineMetrics] = ...
    results: list[CandidateResult] = ...
    summary: dict[str, Any] = ...
class SurvivorManifest(BaseModel):
    model_config: Any
    meta: RunMetadata = ...
    survivors: list[CandidateResult] = ...
    ready_for_portfolio: bool = ...
    recommendation: str = ...
    next_step: Literal['P2-PORTFOLIO', 'investigate_failures', 'expand_matrix'] = ...
class HumanSummary(BaseModel):
    model_config: Any
    meta: RunMetadata = ...
    markdown: str = ...
    key_findings: list[str] = ...
    survivor_table: str | None = ...
class P2Config(BaseModel):
    model_config: Any
    random_seed: int = ...
    smoke_test: bool = ...
    data_path: str | None = ...
    test_size: float = ...
    min_delta_for_override: float = ...
    confidence_level: float = ...
    output_dir: str = ...
    max_candidates_first_run: int = ...
    panel_root: str = ...
    panel_manifest_path: str | None = ...
    supervision_root: str = ...
    supervision_bundle: str = ...
    supervision_surface: str = ...
    narrow_data_mode: NarrowDataMode = ...
    narrow_workers: int = ...
    sklearn_n_jobs: int = ...
    def default_supervision_path(self: Any) -> str: ...
