from typing import Any

"""
P2-MAP: inventory SIP primary panel, derived W4-A surfaces, and blocked alt data.
"""

LOG: Any
W4A_SUPERVISION_REL: Any
def get_derived_supervision_surfaces(config: P2Config | None = ...) -> list[DerivedSupervisionSurfaceEntry]: ...
def get_blocked_surfaces() -> list[SurfaceRegistryEntry]: ...
def get_known_surfaces(config: P2Config | None = ...) -> list[SurfaceRegistryEntry]: ...
def get_model_families() -> list[ModelFamilyEntry]: ...
def get_signal_families() -> list[SignalFamilyEntry]: ...
def run_p2_map(config: P2Config | None = ...) -> dict[str, Path]: ...
