from typing import Any

"""
P2-NARROW: Evaluate candidate matrix on W4-A / W3-B supervision (date-level, W4-B parity).

Test utility uses W4-B sum semantics over all test date rows (not mean across folds).
"""

LOG: Any
DEFERRED_STRESS: Any
def get_model_instance(candidate: CandidateSpec, random_seed: int, *, sklearn_n_jobs: int = ...) -> RegressorMixin: ...
def train_and_predict(candidate: CandidateSpec, x_train: np.ndarray, y_train: np.ndarray, x_validation: np.ndarray, x_test: np.ndarray, random_seed: int, *, sklearn_n_jobs: int = ...) -> tuple[np.ndarray, np.ndarray, dict[str, float]]: ...
def apply_decision_rule(preds: np.ndarray, candidate: CandidateSpec, best_child_idx_train: int, min_delta_for_override: float, *, override_threshold: float | None = ...) -> np.ndarray: ...
def tune_override_threshold(candidate: CandidateSpec, preds_validation: np.ndarray, y_validation: np.ndarray, *, best_child_idx_train: int, min_delta_for_override: float) -> float: ...
def build_test_prediction_frame(test_rows: pd.DataFrame, chosen_indices: np.ndarray, y_test: np.ndarray, *, model_family: str) -> pd.DataFrame: ...
def train_best_child_index(date_frame: pd.DataFrame, child_policy_ids: tuple[str, ...]) -> int: ...
def w4b_comparators_to_baselines(comparators: dict[str, object]) -> list[BaselineMetrics]: ...
def evaluate_candidate_with_context(candidate: CandidateSpec, ctx: NarrowEvalContext) -> CandidateResult: ...
def run_p2_narrow(config: P2Config | None = ...) -> dict[str, Path]: ...
def generate_human_summary(report: NarrowingReport, manifest: SurvivorManifest, baselines: list[BaselineMetrics]) -> str: ...
