from typing import Any

"""
SIP panel inventory and W4-A supervision path resolution for P2-MAP.
"""

LEDGER_DATE_START: Any
LEDGER_DATE_END: Any
LEDGER_ROW_COUNT: Any
LEDGER_INSTRUMENT_COUNT: Any
LEDGER_TRADING_DAY_COUNT: Any
PRIMARY_PANEL_ID: Any
DEFAULT_MANIFEST_NAME: Any
def default_panel_manifest_path(config: P2Config) -> Path: ...
def panel_root_exists(panel_root: Path) -> bool: ...
def load_panel_stats_from_manifest(manifest_path: Path) -> dict[str, Any] | None: ...
def resolve_primary_panel_entry(config: P2Config) -> PrimaryDataPanelEntry: ...
def resolve_supervision_path(config: P2Config) -> Path: ...
def supervision_artifact_exists(config: P2Config) -> bool: ...
def prerequisite_message(config: P2Config) -> str: ...
