from typing import Any

"""
Process-parallel helpers for P2-NARROW candidate evaluation.
"""

class FoldSlice:
    fold_id: str = ...
    x_train: np.ndarray = ...
    y_train: np.ndarray = ...
    x_validation: np.ndarray = ...
    y_validation: np.ndarray = ...
    x_test: np.ndarray = ...
    y_test: np.ndarray = ...
    test_meta: pd.DataFrame = ...
class NarrowEvalContext:
    fold_slices: tuple[FoldSlice, ...] = ...
    child_policy_ids: tuple[str, ...] = ...
    random_seed: int = ...
    min_delta_for_override: float = ...
    best_child_idx_train: int = ...
    best_child_test_utility: float = ...
    sklearn_n_jobs: int = ...
def resolve_narrow_workers(config: P2Config, *, candidate_count: int) -> int: ...
def resolve_sklearn_n_jobs(config: P2Config, *, narrow_workers: int) -> int: ...
def build_fold_slices(supervision: NarrowSupervisionFrame) -> tuple[FoldSlice, ...]: ...
def build_eval_context(supervision: NarrowSupervisionFrame, config: P2Config, *, best_child_idx_train: int, best_child_test_utility: float, narrow_workers: int) -> NarrowEvalContext: ...
def narrow_worker_entry(candidate_payload: dict[str, Any]) -> dict[str, Any]: ...
def evaluate_candidates_parallel(candidates: list[Any], context: NarrowEvalContext, *, max_workers: int) -> list[dict[str, Any]]: ...
