from typing import Any

"""
Load W4-A supervision into date-level frames for P2-NARROW (W4-B parity).
"""

Grain: Any
class NarrowSupervisionFrame:
    frame: pd.DataFrame = ...
    child_policy_ids: tuple[str, ...] = ...
    feature_names: tuple[str, ...] = ...
    target_columns: tuple[str, ...] = ...
    source_path: str | None = ...
    grain: Grain = ...
    provenance: dict[str, Any] = ...
def generate_synthetic_router_supervision(n_rows: int = ..., n_features: int = ..., n_children: int = ..., random_seed: int = ...) -> pd.DataFrame: ...
def cast_child_policy_ids(date_frame: pd.DataFrame) -> tuple[str, ...]: ...
def extract_allowed_feature_names(date_frame: pd.DataFrame) -> tuple[str, ...]: ...
def load_narrow_supervision_frame(config: P2Config) -> NarrowSupervisionFrame: ...
