from typing import Any

def build_execution_assumptions_payload(*, strategy: str, config: PairsConfig, extra: Mapping[str, Any] | None = ...) -> dict[str, Any]: ...
def build_stat_validity_payload(*, strategy: str, pair: tuple[str, str], config: PairsConfig, evaluation_window: str, half_life_bars: float | None, mean_spread_zscore: float | None, signal_count: int, pit_compliant: bool, validation_profile: str = ...) -> dict[str, Any]: ...
