from typing import Any

def pairs_zscore_column(cols: PairsColumns, window: int) -> str: ...
def require_pairs_feature_columns(available_columns: Iterable[str], *, cols: PairsColumns, zscore_window: int) -> None: ...
