from typing import Any

class PairsColumns:
    leg_a: str = ...
    leg_b: str = ...
    def a_close(self: Any) -> str: ...
    def b_close(self: Any) -> str: ...
    def beta(self: Any) -> str: ...
    def spread(self: Any) -> str: ...
    def half_life(self: Any) -> str: ...
