from typing import Any

T: Any
def run_blocking(func: Callable[..., T], *args: Any, timeout: float | None = ..., **kwargs: Any) -> T: ...
def run_cpu(func: Callable[..., T], *args: Any, timeout: float | None = ..., **kwargs: Any) -> T: ...
