from typing import Any

class StepFactory:
    def register(cls: Any, name: str, step_cls: Type) -> None: ...
    def get(cls: Any, name: str) -> Type: ...
    def create(cls: Any, name: str, cfg: Dict[str, Any]) -> Any: ...
new_step: Any
AVAILABLE_STEPS: Any
