from typing import Any

def canonical_op(op_id: str, aliases: Dict[str, str]) -> str: ...
def normalize_common_keys(o: Dict[str, Any]) -> Dict[str, Any]: ...
def normalize_input(o: Dict[str, Any]) -> Dict[str, Any]: ...
def normalize_clip(o: Dict[str, Any]) -> Dict[str, Any]: ...
def ensure_list(o: Dict[str, Any], key: str) -> Dict[str, Any]: ...
def map_fill_strategy(val: str) -> str: ...
def normalize_lag(o: Dict[str, Any]) -> Dict[str, Any]: ...
def normalize_bucket(o: Dict[str, Any]) -> Dict[str, Any]: ...
def assign_device_hint(o: Dict[str, Any]) -> Dict[str, Any]: ...
