from typing import Any

class AlternativeDataParams(BaseModel):
    model_config: Any
    provider_key: str = ...
    output_columns: tuple[str, ...] = ...
class AlternativeDataNormalizerStep(CleaningStep):
    ...
