from typing import Any

class TimeZoneParams(BaseModel):
    model_config: Any
    target_tz: str = ...
    timestamp_col: str = ...
class TimeZoneNormalizerStep(CleaningStep):
    ...
class GlobalCalendarParams(BaseModel):
    model_config: Any
    countries: tuple[str, ...] = ...
    day_of_week: bool = ...
    is_holiday: bool = ...
    timestamp_col: str = ...
class GlobalCalendarNormalizerStep(CleaningStep):
    ...
