from typing import Any

class MacroFeatureParams(BaseModel):
    model_config: Any
    provider_key: str = ...
    output_columns: tuple[str, ...] = ...
class EconomicIndicatorNormalizerStep(CleaningStep):
    ...
