from typing import Any

class SentimentParams(BaseModel):
    model_config: Any
    provider_key: str = ...
    output_column: str = ...
    text_column: str = ...
class VaderSentimentParams(SentimentParams):
    provider_key: str = ...
class VaderSentimentStep(_ProviderSentimentStep):
    ...
class FinbertSentimentParams(SentimentParams):
    provider_key: str = ...
class FinbertSentimentStep(_ProviderSentimentStep):
    ...
