from typing import Any

class RSIParams(BaseModel):
    model_config: Any
    window: int = ...
    output_column: str = ...
    close_column: str = ...
    fillna_method: str = ...
class RSINormalizerStep(CleaningStep):
    ...
class MACDParams(BaseModel):
    model_config: Any
    fast: int = ...
    slow: int = ...
    signal: int = ...
    close_column: str = ...
    macd_column: str = ...
    signal_column: str = ...
class MACDNormalizerStep(CleaningStep):
    ...
class ATRParams(BaseModel):
    model_config: Any
    window: int = ...
    output_column: str = ...
    high_column: str = ...
    low_column: str = ...
    close_column: str = ...
class ATRNormalizerStep(CleaningStep):
    ...
class VWAPParams(BaseModel):
    model_config: Any
    output_column: str = ...
    high_column: str = ...
    low_column: str = ...
    close_column: str = ...
    volume_column: str = ...
class VWAPNormalizerStep(CleaningStep):
    ...
