from typing import Any

"""
Structured exception classes for the gate runner.

All errors are actionable with: code, message, severity, file, uri, path,
schema_path, and context fields.
"""

class GateError:
    code: str = ...
    message: str = ...
    severity: str = ...
    file: str | None = ...
    uri: str | None = ...
    path: str | None = ...
    schema_path: str | None = ...
    context: dict[str, Any] = ...
    def to_dict(self: Any) -> dict[str, Any]: ...
class GateRunnerError(Exception):
    def __init__(self: Any, error: GateError) -> None: ...
class SchemaValidationError(GateRunnerError):
    def __init__(self: Any, message: str, *, file: str | None = ..., path: str | None = ..., schema_path: str | None = ..., context: dict[str, Any] | None = ...) -> None: ...
class HashMismatchError(GateRunnerError):
    def __init__(self: Any, *, uri: str, path: str | None = ..., declared_hash: str, computed_hash: str) -> None: ...
class URIResolutionError(GateRunnerError):
    def __init__(self: Any, uri: str, reason: str) -> None: ...
class UnsupportedURISchemeError(GateRunnerError):
    def __init__(self: Any, uri: str, scheme: str) -> None: ...
class MissingLockError(GateRunnerError):
    def __init__(self: Any, lock: str, lane: str) -> None: ...
class IncomparableError(GateRunnerError):
    def __init__(self: Any, lock: str, value_a: Any, value_b: Any) -> None: ...
class RankDeltaMismatchError(GateRunnerError):
    def __init__(self: Any, *, candidate_key: str, index: int, lane_a_rank: int, lane_b_rank: int, declared_delta: int, computed_delta: int) -> None: ...
class KValuesMismatchError(GateRunnerError):
    def __init__(self: Any, *, declared_ks: list[int], referenced_ks: list[int], missing_declarations: list[int] | None = ..., missing_metrics: list[int] | None = ...) -> None: ...
class BindingInvalidError(GateRunnerError):
    def __init__(self: Any, message: str, *, mode: str, has_plan_hash_a: bool, has_plan_hash_b: bool, has_run_ids: bool) -> None: ...
class ThresholdViolationError(GateRunnerError):
    def __init__(self: Any, *, metric_name: str, actual: float, expected_min: float | None = ..., expected_max: float | None = ...) -> None: ...
class MissingRequiredArtifactError(GateRunnerError):
    def __init__(self: Any, artifact_type: str, mode: str) -> None: ...
class ConfigurationError(GateRunnerError):
    def __init__(self: Any, message: str, *, context: dict[str, Any] | None = ...) -> None: ...
