from typing import Any

"""
BudgetManager: tracks and enforces trial budget and timeout limits.
"""

class BudgetExhaustedError(RuntimeError):
    ...
class BudgetManager:
    def __init__(self: Any, max_trials: int, timeout_seconds: int | None) -> None: ...
    def consume(self: Any, n: int = ...) -> None: ...
    def remaining(self: Any) -> int: ...
