from typing import Any

"""
CommandBus: typed command dispatch for orchestration events.
"""

class Command:
    name: str = ...
    payload: dict[str, Any] = ...
Handler: Any
class CommandBus:
    def __init__(self: Any) -> None: ...
    def register(self: Any, command_name: str, handler: Handler) -> None: ...
    def dispatch(self: Any, command: Command) -> None: ...
