from typing import Any

"""
Scheduler: determines when and in what order jobs are dispatched.
"""

class ScheduledJob:
    job_id: str = ...
    priority: int = ...
    tags: dict[str, str] = ...
class Scheduler:
    def __init__(self: Any) -> None: ...
    def enqueue(self: Any, job: ScheduledJob) -> None: ...
    def next(self: Any) -> ScheduledJob | None: ...
    def pending(self: Any) -> list[ScheduledJob]: ...
