from typing import Any

"""
LiveTriggerSpec: validated, frozen spec for drift-triggered retraining.
"""

class LiveTriggerSpec:
    name: str = ...
    version: str = ...
    spec_hash: str = ...
    drift_threshold: float = ...
    retrain_cooldown_seconds: int = ...
    latency_budget_ms: int = ...
    min_samples_before_trigger: int = ...
    enable_online_features: bool = ...
