from typing import Any

"""
ObjectiveSpec: validated, frozen spec for an objective function.
"""

class ObjectiveSpec:
    name: str = ...
    version: str = ...
    spec_hash: str = ...
    direction: Literal['maximize', 'minimize'] = ...
    metrics: tuple[str, ...] = ...
    weights: dict[str, float] = ...
    penalty_refs: tuple[str, ...] = ...
    min_sharpe: float | None = ...
    max_turnover: float | None = ...
