from typing import Any

"""
PromotionSpec: validated, frozen spec for a promotion/rollout strategy.
"""

class PromotionSpec:
    name: str = ...
    version: str = ...
    spec_hash: str = ...
    mode: Literal['shadow', 'capped_blend', 'full'] = ...
    shadow_duration_days: int = ...
    rollback_policy: Literal['auto', 'manual', 'none'] = ...
    approval_required: bool = ...
    blend_cap: float | None = ...
