from typing import Any

"""
SearchSpaceSpec: validated, frozen spec for a parameter search space.
"""

class DimensionSpec:
    name: str = ...
    kind: Literal['real', 'int', 'categorical', 'log_real'] = ...
    low: float | None = ...
    high: float | None = ...
    choices: tuple[Any, ...] | None = ...
    prior: Literal['uniform', 'log-uniform'] = ...
class SearchSpaceSpec:
    name: str = ...
    version: str = ...
    model_type: str = ...
    spec_hash: str = ...
    dimensions: tuple[DimensionSpec, ...] = ...
    fixed: dict[str, Any] = ...
