from typing import Any

"""
TuningJobSpec: validated, frozen specification for a tuning job.
"""

class TuningJobSpec:
    job_id: str = ...
    version: str = ...
    search_space_ref: str = ...
    objective_ref: str = ...
    validation_ref: str = ...
    spec_hash: str = ...
    max_trials: int = ...
    determinism_tier: Literal['d0', 'd1', 'd2', 'd3'] = ...
    promotion_ref: str | None = ...
    timeout_seconds: int | None = ...
    crisis_holdout: bool = ...
    tags: dict[str, str] = ...
