from typing import Any

"""
ValidationSpec: validated, frozen spec for a cross-validation strategy.
"""

class ValidationSpec:
    name: str = ...
    version: str = ...
    spec_hash: str = ...
    method: Literal['walkforward', 'purged_cv', 'cpcv', 'crisis_holdout'] = ...
    n_splits: int = ...
    embargo_periods: int = ...
    crisis_holdout: bool = ...
    cost_stress_bps: float = ...
    min_train_periods: int = ...
