from typing import Any

class ExternalFrameContractModel(BaseModel):
    model_config: Any
    required_columns: tuple[str, ...] = ...
    optional_columns: tuple[str, ...] = ...
    schema_payload: Mapping[str, Any] | None = ...
    strict: bool = ...
    unknown_ok: bool = ...
    def to_internal(self: Any) -> FrameContract: ...
class ExternalCleaningStepSpecModel(BaseModel):
    model_config: Any
    step_id: str = ...
    step_type: str = ...
    version: str = ...
    enabled: bool = ...
    params: Mapping[str, Any] = ...
    input_contract: ExternalFrameContractModel = ...
    output_contract: ExternalFrameContractModel = ...
    determinism_tier: CleaningDeterminismTier | None = ...
    governance_mode: GovernanceMode | None = ...
    fallback_policy: Mapping[str, Any] = ...
    def to_internal(self: Any, *, default_governance_mode: GovernanceMode, default_determinism_tier: CleaningDeterminismTier) -> CleaningStepSpec: ...
class ExternalCleaningComboModel(BaseModel):
    model_config: Any
    name: str | None = ...
    when: Mapping[str, Any] = ...
    steps: tuple[ExternalCleaningStepSpecModel, ...] = ...
    order: Mapping[str, Mapping[str, tuple[str, ...]]] = ...
class ExternalCleaningPipelineSpecModel(BaseModel):
    model_config: Any
    steps: tuple[ExternalCleaningStepSpecModel, ...] = ...
    determinism_tier: CleaningDeterminismTier = ...
    governance_mode: GovernanceMode = ...
    seed_lineage: str = ...
    pit_boundary: str = ...
    metadata: Mapping[str, Any] = ...
    def to_internal(self: Any) -> CleaningPipelineSpec: ...
class ExternalCleaningConfigModel(BaseModel):
    model_config: Any
    use: str | None = ...
    determinism_tier: CleaningDeterminismTier = ...
    governance_mode: GovernanceMode = ...
    seed_lineage: str = ...
    pit_boundary: str = ...
    metadata: Mapping[str, Any] = ...
    combos: Mapping[str, ExternalCleaningComboModel] | tuple[ExternalCleaningComboModel, ...] = ...
def pipeline_spec_from_external_cleaning_config(raw: Mapping[str, Any], *, context: PipelineContext | None = ..., metadata: Mapping[str, Any] | None = ..., name: str | None = ...) -> CleaningPipelineSpec: ...
def pipeline_spec_from_external_pipeline_spec(raw: Mapping[str, Any]) -> CleaningPipelineSpec: ...
