from typing import Any

class CleaningDeterminismTier(str, Enum):
    D0: Any
    D1: Any
    D2: Any
    D3: Any
class GovernanceMode(str, Enum):
    GOVERNED: Any
    NONGOVERNED: Any
class FrameContract:
    required_columns: tuple[str, ...] = ...
    optional_columns: tuple[str, ...] = ...
    schema: MarketDataFrameSchema | None = ...
    strict: bool = ...
    unknown_ok: bool = ...
    def from_mapping(cls: Any, raw: Mapping[str, Any] | None) -> 'FrameContract': ...
    def validate(self: Any, df: pl.DataFrame, *, label: str) -> None: ...
    def to_payload(self: Any) -> dict[str, Any]: ...
class CleaningStepSpec:
    step_id: str = ...
    step_type: str = ...
    version: str = ...
    enabled: bool = ...
    params: Mapping[str, Any] = ...
    input_contract: FrameContract = ...
    output_contract: FrameContract = ...
    determinism_tier: CleaningDeterminismTier = ...
    governance_mode: GovernanceMode = ...
    fallback_policy: Mapping[str, Any] = ...
    def from_mapping(cls: Any, raw: Mapping[str, Any], *, default_governance_mode: GovernanceMode = ..., default_determinism_tier: CleaningDeterminismTier = ...) -> 'CleaningStepSpec': ...
    def to_payload(self: Any) -> dict[str, Any]: ...
class CleaningPipelineSpec:
    steps: tuple[CleaningStepSpec, ...] = ...
    determinism_tier: CleaningDeterminismTier = ...
    seed_lineage: str = ...
    pit_boundary: str = ...
    governance_mode: GovernanceMode = ...
    metadata: Mapping[str, Any] = ...
    def from_mapping(cls: Any, raw: Mapping[str, Any]) -> 'CleaningPipelineSpec': ...
    def to_payload(self: Any) -> dict[str, Any]: ...
class CleaningPipelineState:
    step_state: dict[str, Any] = ...
    warnings: list[str] = ...
    fallback_events: list[dict[str, Any]] = ...
    provider_lineage: dict[str, dict[str, Any]] = ...
    validation_failures: list[dict[str, Any]] = ...
class CleaningMutationSummary:
    rows_in: int = ...
    rows_out: int = ...
    rows_removed: int = ...
    rows_with_mutations: int = ...
    cells_mutated: int = ...
    def to_payload(self: Any) -> dict[str, int]: ...
class CleaningRuntimeContext:
    run_id: str = ...
    determinism_tier: CleaningDeterminismTier = ...
    seed_lineage: str = ...
    pit_boundary: str = ...
    governance_mode: GovernanceMode = ...
    providers: MutableMapping[str, Any] = ...
    streaming: bool = ...
    registry_state_hash: str = ...
    def provider(self: Any, key: str) -> Any: ...
    def seed_for(self: Any, material: str) -> int: ...
class CleaningStepResult:
    frame: pl.DataFrame = ...
    state: CleaningPipelineState = ...
    warnings: list[str] = ...
    metrics: dict[str, Any] = ...
    provider_lineage: dict[str, Any] = ...
    validation_failures: list[str] = ...
    fallback_events: list[dict[str, Any]] = ...
    mutation: CleaningMutationSummary = ...
    def apply_to_state(self: Any) -> None: ...
class BuiltCleaningPipeline:
    spec: CleaningPipelineSpec = ...
    steps: tuple[Any, ...] = ...
    plan_hash: str = ...
    registry_state_hash: str = ...
    def run(self: Any, df: Any, *, context: CleaningRuntimeContext | None = ...) -> CleaningStepResult: ...
    def to_plan_payload(self: Any) -> dict[str, Any]: ...
    def to_report_payload(self: Any, result: CleaningStepResult, *, context: CleaningRuntimeContext) -> dict[str, Any]: ...
