from typing import Any

class CleaningMetricsError(Exception):
    ...
class MLflowUnavailable(CleaningMetricsError):
    ...
mlflow: Any
class AsyncMLflowLogger:
    def __init__(self: Any) -> None: ...
    async def log_metrics(self: Any, metrics: Dict[str, float], *, step: Optional[int] = ...) -> None: ...
    async def log_params(self: Any, params: Dict[str, Any]) -> None: ...
    async def set_experiment(self: Any, name: str) -> None: ...
    async def start_run(self: Any, *, run_name: Optional[str] = ..., nested: bool = ..., tags: Optional[Dict[str, str]] = ...) -> Any: ...
    async def end_run(self: Any) -> None: ...
    async def log_artifact(self: Any, local_path: str, *, artifact_path: Optional[str] = ...) -> None: ...
async def log_metric_mlflow(key: str, value: Any) -> None: ...
def record_step_latency_ms(value_ms: float, *, step: str = ...) -> None: ...
def wire_cleaner_observers(*, get_latency: Callable[[], float] | None, get_buffer_len: Callable[[], int] | None, get_data_volume: Callable[[], int] | None) -> None: ...
