from typing import Any

class GovernedColumns:
    frame: pl.DataFrame = ...
    lineage: dict[str, Any] = ...
    warnings: tuple[str, ...] = ...
class GovernedColumnProvider(Protocol):
    provider_name: str = ...
    def materialize(self: Any, df: pl.DataFrame, *, context: Any, params: Any) -> GovernedColumns: ...
class FailClosedProvider:
    def __init__(self: Any, provider_name: str) -> None: ...
    def materialize(self: Any, df: pl.DataFrame, *, context: Any, params: Any) -> GovernedColumns: ...
def default_cleaning_providers() -> dict[str, GovernedColumnProvider]: ...
