from typing import Any

class CleaningStepRegistration:
    step_type: str = ...
    version: str = ...
    step_cls: type[Any] = ...
    params_model: type[BaseModel] = ...
    input_contract: FrameContract = ...
    output_contract: FrameContract = ...
    determinism_tier: CleaningDeterminismTier = ...
    provider_requirements: tuple[str, ...] = ...
    stateful: bool = ...
    def descriptor(self: Any) -> dict[str, Any]: ...
def register_cleaning_step(*, step_type: str, version: str, params_model: type[BaseModel], input_contract: FrameContract | None = ..., output_contract: FrameContract | None = ..., determinism_tier: CleaningDeterminismTier = ..., provider_requirements: tuple[str, ...] = ..., stateful: bool = ...) -> Callable[[type[Any]], type[Any]]: ...
def bootstrap_default_cleaning_registry() -> None: ...
def resolve_cleaning_step(step_type: str, version: str) -> CleaningStepRegistration: ...
def list_registered_cleaning_steps() -> list[CleaningStepRegistration]: ...
def registry_state_hash() -> str: ...
