from typing import Any

class AlphaIR:
    signal: pd.Series = ...
    information_coefficient: float | None = ...
    realized_vol: pd.Series | None = ...
    task_embedding: np.ndarray = ...
    pit_provenance: PitMeta | None = ...
    variant: str = ...
    diagnostics: dict[str, Any] = ...
