from typing import Any

class ComparisonRunResult:
    bundle_dir: Path = ...
    comparison_run_id: str = ...
    variant_runs: dict[str, RunResult] = ...
def run_variant_comparison(ctx: StrategyContext, *, bundle_dir: Path | None = ..., run_registry: RunRegistry | None = ..., cas: LocalCAS | None = ..., commission_bps: float = ..., slippage_bps: float = ..., cost_model_id: str = ..., purge_window: int = ..., embargo_window: int = ..., min_train_size: int = ...) -> ComparisonRunResult: ...
