from typing import Any

class OrchestratorHooks(Protocol):
    def apply_crash_override(self: Any, *, trade_intent: TradeIntent, alpha_ir: AlphaIR, ctx: StrategyContext, strategy: MomentumStrategy) -> TradeIntent | None: ...
    def apply_cost_gate(self: Any, *, trade_intent: TradeIntent, alpha_ir: AlphaIR, ctx: StrategyContext, strategy: MomentumStrategy, execution_assumptions_path: Path, bundle_dir: Path) -> TradeIntent | None: ...
class RunResult:
    trade_intent: TradeIntent = ...
    alpha_ir: AlphaIR = ...
    bundle_dir: Path = ...
    artifacts: dict[str, Path] = ...
def run(ctx: StrategyContext, *, variant: str = ..., orchestrator_hooks: OrchestratorHooks | None = ..., bundle_dir: Path | None = ..., run_id: str | None = ..., run_registry: RunRegistry | None = ..., cas: LocalCAS | None = ..., enable_crash_override: bool = ..., strategy: MomentumStrategy | None = ..., **params: Any) -> RunResult: ...
