from typing import Any

class FeatureFlagError(PipelineError):
    ...
class ConvergenceError(MaterializationError):
    def __init__(self: Any, message: str, *, n_iterations: int | None = ..., asset_id: str | None = ...) -> None: ...
class CostGateRejection(Exception):
    def __init__(self: Any, message: str, *, variant: str, run_id: str, reason_code: str) -> None: ...
class SerializationError(Exception):
    ...
class MissingExecutionAssumptionsError(FileNotFoundError):
    ...
def exception_metadata(exc: Exception) -> dict[str, Any]: ...
