from typing import Any

logger: Any
class AnonymizationConfig(BaseModel):
    enabled: bool = ...
    sensitive_columns: List[str] = ...
    hash_algorithm: str = ...
    salt: Optional[str] = ...
def get_hash_func(algo: str, salt: Optional[str] = ...) -> Callable[[str], str]: ...
class DataAnonymizationStep(PipelineStep):
    def __init__(self: Any, config: AnonymizationConfig) -> Any: ...
    def apply(self: Any, lf: LazyFrame) -> LazyFrame: ...
class RegulatoryFilterConfig(BaseModel):
    enabled: bool = ...
    restricted_symbols: List[str] = ...
    min_volume_threshold: Optional[float] = ...
class RegulatoryFilterStep(PipelineStep):
    def __init__(self: Any, config: RegulatoryFilterConfig) -> Any: ...
    def apply(self: Any, lf: LazyFrame) -> LazyFrame: ...
COMPLIANCE_STEPS: Dict[str, Type[PipelineStep]] = ...
COMPLIANCE_CONFIGS: Dict[str, Type[BaseModel]] = ...
def build_compliance_steps(configs: List[dict]) -> List[PipelineStep]: ...
