from typing import Any

"""
Pure corporate-action adjustment for raw Massive daily bars.
"""

RAW_PRICE_COLUMNS: Final[tuple[str, ...]] = ...
RAW_VOLUME_COLUMN: Final[str] = ...
ADJUSTED_RETURN_PRICE_COLUMN: Final[str] = ...
FORWARD_LABEL_PRICE_COLUMN: Final[str] = ...
FILTER_PRICE_COLUMN: Final[str] = ...
LIQUIDITY_VOLUME_COLUMN: Final[str] = ...
class CorporateActionAdjustmentError(ValueError):
    ...
class CorporateActionAdjustmentConfig:
    extreme_return_threshold: float = ...
def build_adjusted_ohlcv_panel(bars: pd.DataFrame, *, splits: pd.DataFrame, dividends: pd.DataFrame, config: CorporateActionAdjustmentConfig | None = ...) -> pd.DataFrame: ...
