from typing import Any

logger: Any
SOURCE_REGISTRY: Dict[str, LazyFrame] = ...
class JoinSpec(BaseModel):
    source_name: str = ...
    on: List[str] = ...
    how: str = ...
    suffix: Optional[str] = ...
class MultiSourceJoinConfig(BaseModel):
    joins: List[JoinSpec] = ...
class MultiSourceJoinStep(PipelineStep):
    def __init__(self: Any, config: MultiSourceJoinConfig) -> Any: ...
    def apply(self: Any, lf: LazyFrame) -> LazyFrame: ...
AGG_MAP: Dict[str, Callable] = ...
class ResampleConfig(BaseModel):
    freq: str = ...
    group_by: List[str] = ...
    agg: Dict[str, str] = ...
    timestamp_col: str = ...
class ResampleStep(PipelineStep):
    def __init__(self: Any, config: ResampleConfig) -> Any: ...
    def apply(self: Any, lf: LazyFrame) -> LazyFrame: ...
JOIN_STEPS: Dict[str, Type[PipelineStep]] = ...
JOIN_CONFIGS: Dict[str, Type[BaseModel]] = ...
def build_join_steps(configs: List[dict]) -> List[PipelineStep]: ...
