from typing import Any

logger: Any
class ColumnRenameConfig(BaseModel):
    mapping: Dict[str, str] = ...
class ColumnRenameStep(PipelineStep):
    def __init__(self: Any, config: ColumnRenameConfig) -> Any: ...
    def apply(self: Any, lf: LazyFrame) -> LazyFrame: ...
class TypeCastConfig(BaseModel):
    model_config: Any
    dtypes: Dict[str, pl.DataType] = ...
class TypeCastStep(PipelineStep):
    def __init__(self: Any, config: TypeCastConfig) -> Any: ...
    def apply(self: Any, lf: LazyFrame) -> LazyFrame: ...
TRANSFORM_STEPS: Dict[str, Type[PipelineStep]] = ...
TRANSFORM_CONFIGS: Dict[str, Type[BaseModel]] = ...
def build_steps(configs: List[dict], step_registry: Dict[str, Type[PipelineStep]], config_registry: Dict[str, Type[BaseModel]]) -> List[PipelineStep]: ...
def build_transform_steps(configs: List[dict]) -> List[PipelineStep]: ...
