from typing import Any

"""
Gate framework for validating backtest bundles.
"""

class GateStatus(Enum):
    PASS: Any
    FAIL: Any
class GateResult:
    gate_id: str = ...
    status: GateStatus = ...
    reason: Optional[str] = ...
    evidence: Optional[dict[str, Any]] = ...
class ValidationResult:
    bundle_path: Path = ...
    overall_status: GateStatus = ...
    gates: List[GateResult] = ...
    def to_dict(self: Any) -> dict[str, Any]: ...
def gate_files_exist(bundle_path: Path) -> GateResult: ...
def gate_json_valid(bundle_path: Path) -> GateResult: ...
def gate_sharpe_threshold(bundle_path: Path, min_sharpe: float = ...) -> GateResult: ...
def gate_max_drawdown(bundle_path: Path, max_allowed: float = ...) -> GateResult: ...
def validate_bundle(bundle_path: Path) -> ValidationResult: ...
