from typing import Any

"""
Artifact integrity verification via hash comparison.

Per spec §7.3, for every manifest entry in artifact_index:
1. Resolve uri → bytes
2. Parse JSON → dict/list
3. Canonicalize (RFC8785) and compute content_hash
4. Compare against manifest content_hash
5. Mismatch → FAIL with HASH_MISMATCH error
"""

class ArtifactRef:
    artifact_type: str = ...
    uri: str = ...
    content_hash: str = ...
    def to_dict(self: Any) -> dict[str, str]: ...
class IntegrityResult:
    valid: bool = ...
    errors: list[GateError] = ...
    artifact_refs: list[ArtifactRef] = ...
    artifacts: dict[str, Any] = ...
def verify_artifact_integrity(bundle_dir: Path, artifact_index: dict[str, Any]) -> IntegrityResult: ...
def verify_single_artifact(uri: str, declared_hash: str, bundle_dir: Path) -> tuple[bool, dict[str, Any] | None, GateError | None]: ...
