from typing import Any

"""
Transfer report invariant verification.

Per spec §10, verifies:
1. rank_delta invariant: lane_b_rank - lane_a_rank == declared_rank_delta
2. k_values consistency: metrics reference exactly the declared k_values
3. Binding invariant: promote mode requires plan_hash_a and plan_hash_b
4. Comparability locks: Lane A and Lane B must have matching locks
"""

class InvariantResult:
    valid: bool = ...
    errors: list[GateError] = ...
def verify_rank_delta_invariant(transfer_report: dict[str, Any]) -> InvariantResult: ...
def verify_k_values_consistency(transfer_report: dict[str, Any]) -> InvariantResult: ...
def verify_transfer_binding(transfer_report: dict[str, Any], mode: str, allow_run_ids: bool = ...) -> InvariantResult: ...
def verify_comparability_locks(transfer_report: dict[str, Any], required_locks: list[str]) -> InvariantResult: ...
def verify_transfer_invariants(transfer_report: dict[str, Any], mode: str, required_locks: list[str], allow_run_ids: bool = ...) -> InvariantResult: ...
