from typing import Any

"""
Non-evaluating gate shell for Phase II ML scaffold artifacts (not ML-6).
"""

class MetaLearnerScaffoldStatus(str, Enum):
    SCAFFOLD_INCOMPLETE: Any
EXPECTED_TASK_MANIFEST_PREFIX: Final[str] = ...
EXPECTED_META_VALIDITY_PREFIX: Final[str] = ...
EXPECTED_EXEC_ASSUMPTIONS_PREFIX: Final[str] = ...
REQUIRED_ARTIFACTS: Final[tuple[str, ...]] = ...
ARTIFACT_SURFACE_ROLES: Final[tuple[tuple[str, str], ...]] = ...
REASON_MISSING_ARTIFACTS: Final[str] = ...
REASON_SCHEMA_PREFIX_MISMATCH: Final[str] = ...
REASON_META_VALIDITY_OVERALL_ABSENT: Final[str] = ...
REASON_META_VALIDITY_OVERALL_SCAFFOLD: Final[str] = ...
REASON_META_VALIDITY_OVERALL_REDACTED: Final[str] = ...
REASON_GOVERNED_CONTRACT_MISMATCH: Final[str] = ...
REASON_GOVERNED_SCHEMA_INVALID: Final[str] = ...
SCHEMA_FILES: Final[dict[str, str]] = ...
class MetaLearnerScaffoldGateResult:
    status: MetaLearnerScaffoldStatus = ...
    artifacts_present: dict[str, bool] = ...
    schema_ok: dict[str, bool] = ...
    overall_result: str | None = ...
    incomplete_reason_codes: tuple[str, ...] = ...
    evidence: dict[str, Any] = ...
    def to_json_dict(self: Any) -> dict[str, Any]: ...
def evaluate_meta_learner_scaffold(run_dir: Path) -> MetaLearnerScaffoldGateResult: ...
