from typing import Any

"""
Non-evaluating Phase II-0B ML evidence shell.

This shell checks whether the governed artifact triple is mechanically usable as
II-0B evidence. It does not evaluate trainer, allocator, rollout, or execution
readiness.
"""

class Phase2MLEvidenceShellStatus(str, Enum):
    EVIDENCE_INCOMPLETE: Any
    EVIDENCE_STRUCTURALLY_USABLE: Any
REQUIRED_ARTIFACTS: Final[tuple[str, ...]] = ...
SCHEMA_FILES: Final[dict[str, str]] = ...
class Phase2MLEvidenceShellResult:
    status: Phase2MLEvidenceShellStatus = ...
    artifacts_present: dict[str, bool] = ...
    schema_ok: dict[str, bool] = ...
    binding_ok: dict[str, bool] = ...
    promotable_claim_emitted: bool = ...
    reason_codes: tuple[str, ...] = ...
    evidence: dict[str, Any] = ...
    def to_json_dict(self: Any) -> dict[str, Any]: ...
def evaluate_phase2_ml_evidence_shell(run_dir: Path) -> Phase2MLEvidenceShellResult: ...
