from typing import Any

"""
JSON Schema validation with multi-dialect support (Draft-07 and 2020-12).

Deep closed-world validation ensures all object nodes have additionalProperties: false.
This prevents nested "unknown field" smuggling per spec §8.1.
"""

class ValidationResult:
    valid: bool = ...
    errors: list[GateError] = ...
def validate_against_schema(instance: dict[str, Any], schema: dict[str, Any], *, file: str | None = ...) -> ValidationResult: ...
def load_schema(schema_path: Path) -> dict[str, Any]: ...
def assert_all_objects_closed(schema: dict[str, Any], path: str = ...) -> None: ...
