from typing import Any

"""
Download governed RG-09 multi-instrument daily closes via yfinance.

Acquisition is separate from fixture generation: parquet outputs are frozen and hashed
before ``scripts.generate_rg09_fixture`` consumes them (no network at fixture build time).
"""

LOG: Any
REQUIRED_ROWS: Final[int] = ...
def ticker_safe_filename(ticker: str) -> str: ...
def sha256_file(path: Path) -> str: ...
def normalize_close_frame(raw: pd.DataFrame, *, ticker: str) -> pd.DataFrame: ...
def download_ticker_to_parquet(*, ticker: str, start: str, end: str, output_path: Path) -> dict[str, object]: ...
def main(output_dir: Path, start: str, end: str, tickers: str) -> None: ...
