from typing import Any

LOG: Any
AMENDMENT: Any
FIXTURE_FILENAME_V1: Any
FIXTURE_FILENAME_V2: Any
SUMMARY_FILENAME: Any
METADATA_FILENAME: Any
FIXTURE_FILENAME: Any
SUMMARY_CLASS_ORDER: tuple[str, ...] = ...
CANONICAL_COLUMNS: tuple[str, ...] = ...
FIXTURE_COLUMNS: tuple[str, ...] = ...
REQUIRED_INPUT_COLUMNS: tuple[str, ...] = ...
FloatArray: Any
class MultiManifestSettings:
    uniform_calendar_day_index: bool = ...
    calendar_overlap_policy: str = ...
    apply_diversification_perturbation: bool = ...
    temporal_folds: int = ...
class FixtureSegmentSpec:
    entity_id: str = ...
    input_path: Path = ...
    date_start: str | None = ...
    date_end: str | None = ...
    close_scale: float = ...
class MetaTaskSizingParams:
    n_support: int = ...
    n_query: int = ...
    horizon: int = ...
    embargo: int = ...
    def l_min(self: Any) -> int: ...
def load_bocpd_config(path: Path, *, repo_root: Path) -> BOCPDConfig: ...
def stagger_multi_instrument_timestamps(rows: list[dict[str, object]], *, entity_ids_sorted: Sequence[str]) -> None: ...
def validate_rg09_fixture_fold_geometry(fixture_frame: pd.DataFrame, fold_construction: dict[str, Any], *, temporal_folds: int, min_entities_per_fold: int = ..., max_entity_share: float = ...) -> None: ...
def load_multi_manifest(path: Path, *, repo_root: Path) -> tuple[list[FixtureSegmentSpec], MultiManifestSettings]: ...
def generate_fixture(*, input_path: Path, config_path: Path, output_dir: Path, entity_id: str) -> dict[str, Any]: ...
def generate_fixture_multi(*, segments: Sequence[FixtureSegmentSpec], config_path: Path, output_dir: Path, source_dataset_id: str | None = ..., multi_settings: MultiManifestSettings | None = ...) -> dict[str, Any]: ...
def main(input_path: Path | None, config_path: Path, output_dir: Path, entity_id: str, multi_manifest_path: Path | None) -> None: ...
