from typing import Any

"""
RG09-DIAG-002: severity-stratified high-vol diagnostic (standalone; reads basket parquets only).
"""

REQUIRED_COLS: Any
class SeverityDiagnosticError(RuntimeError):
    ...
class HighVolEpisodeRow:
    start_idx: int = ...
    end_idx: int = ...
    entity_id: str = ...
    peak_log_rv: float = ...
    mean_log_rv: float = ...
    mean_return: float = ...
    episode_length: int = ...
    episode_start: pd.Timestamp = ...
    episode_end: pd.Timestamp = ...
def extract_high_vol_episodes(df: pd.DataFrame, *, entity_id: str | None = ...) -> list[HighVolEpisodeRow]: ...
def pit_safe_threshold(vol_series: pd.Series, k: int, percentile: float) -> float: ...
def episode_eligible_for_pit(ep: HighVolEpisodeRow, *, cold_start_burn_in: int) -> bool: ...
def classify_episode_severity(ep: HighVolEpisodeRow, vol_series: pd.Series, percentile: float, *, cold_start_burn_in: int) -> tuple[bool, float] | None: ...
def cohens_d_two_sample(a: list[float], b: list[float]) -> float: ...
def parse_thresholds_arg(value: str) -> tuple[int, ...]: ...
def discover_fixture_parquets(basket_dir: Path) -> list[Path]: ...
def run_severity_diagnostic(basket_dir: Path, *, thresholds: tuple[int, ...] = ..., dedup_window_days: int = ..., cold_start_burn_in: int = ..., sizing: MetaTaskSizingParams | None = ...) -> dict[str, Any]: ...
def main(basket_dir: Path, output_path: Path, thresholds_raw: str, dedup_window_days: int, cold_start_burn_in: int) -> None: ...
