from typing import Any

"""
Emit baseline + ordered boundary-recovery feasibility artifacts (evidence-only lane).
"""

DEFAULT_FIXTURE: Final[Path] = ...
DEFAULT_SUMMARY: Final[Path] = ...
DEFAULT_METADATA: Final[Path] = ...
DEFAULT_CONFIG: Final[Path] = ...
DEFAULT_OUT_DIR: Final[Path] = ...
LANE_RUNS: Final[tuple[tuple[str, RG09BoundaryRecoverySpec | None, bool], ...]] = ...
def cli(fixture_path: Path, fixture_summary_path: Path, fixture_metadata_path: Path, config_path: Path, output_dir: Path) -> None: ...
