from typing import Any

logger: Any
def robust_scaler_cudf(ir: Any, gdf: Any, group_by: Any = ..., **_: Any) -> Any: ...
class CuDFExecutor(Executor):
    def __init__(self: Any, *, pool_size: Any = ..., to_torch: Any = ...) -> Any: ...
    def read_parquet(self: Any, path: Any, columns: Any = ..., byte_range: Any = ...) -> Any: ...
    def execute(self: Any, compiled_plan: Any, df: Any) -> Any: ...
def feature_returns_cudf(ir: Any, gdf: Any, **_: Any) -> Any: ...
def feature_sma_cudf(ir: Any, gdf: Any, **_: Any) -> Any: ...
def feature_rsi_cudf(ir: Any, gdf: Any, **_: Any) -> Any: ...
def data_load_csv_cudf(ir: Any, gdf: Any, **_: Any) -> Any: ...
