from typing import Any

logger: Any
get_lowering: Any
Engine: Any
def get(*args: Any) -> Any: ...
def register(*args: Any, **kwargs: Any) -> Any: ...
def list_ops(*args: Any) -> Any: ...
def scaling_robust_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def feature_returns_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def feature_sma_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def feature_rsi_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def technical_sma_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def stats_rolling_std_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def scaling_zscore_roll_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def technical_ema_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def technical_rsi_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def technical_macd_line_signal_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def technical_bollinger_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def technical_atr_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def technical_obv_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def technical_vwap_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
def data_load_csv_polars(ir: Any, lf: Any, *, group_by: Any = ...) -> Any: ...
class PolarsExecutor(Executor):
    def __init__(self: Any, engine_pref: Engine = ..., to_torch: Any = ...) -> Any: ...
    def execute(self: Any, compiled_plan: Any, df: Any) -> Any: ...
