from typing import Any

logger: Any
def register(backend: str, op: str, fn: Any) -> Any: ...
def get(backend: str, op: str) -> Any: ...
def list_ops(backend: str = ...) -> list[str]: ...
def auto_register_from_utils() -> Any: ...
