from typing import Any

class InvariantViolation(ValueError):
    ...
def assert_fill_timestamps_within_window(fills: list[dict[str, Any]], start: datetime, end: datetime) -> None: ...
def assert_position_cash_directionality(before_cash: float, after_cash: float, fills: list[dict[str, Any]]) -> None: ...
