from typing import Any

np: Any
pl: Any
logger: Any
ANONYMIZERS: Dict[str, type['Anonymizer']] = ...
def register_anonymizer(anon_type: str) -> Any: ...
class Anonymizer(ABC):
    def apply(self: Any, df: Union[pl.DataFrame, pl.LazyFrame], columns: List[str]) -> Union[pl.DataFrame, pl.LazyFrame]: ...
class AnonymizationManager:
    def __init__(self: Any, config: Any, max_workers: int = ...) -> Any: ...
    def add_anonymizer(self: Any, anon_type: str, anonymizer: Anonymizer) -> Any: ...
    def anonymize(self: Any, data: Any, columns: Optional[Dict[str, List[str]]] = ..., eager: bool = ...) -> Any: ...
class MaskingAnonymizer(Anonymizer):
    def __init__(self: Any, config: Optional[Dict] = ...) -> Any: ...
    def apply(self: Any, df: Union[pl.DataFrame, pl.LazyFrame], columns: List[str]) -> Union[pl.DataFrame, pl.LazyFrame]: ...
class HashingAnonymizer(Anonymizer):
    def __init__(self: Any, config: Optional[Dict] = ...) -> Any: ...
    def apply(self: Any, df: Union[pl.DataFrame, pl.LazyFrame], columns: List[str]) -> Union[pl.DataFrame, pl.LazyFrame]: ...
class DPAnonymizer(Anonymizer):
    def __init__(self: Any, config: Optional[Dict] = ...) -> Any: ...
    def apply(self: Any, df: Union[pl.DataFrame, pl.LazyFrame], columns: List[str]) -> Union[pl.DataFrame, pl.LazyFrame]: ...
