from typing import Any

pl: Any
logger: Any
COMPLIANCE_CHECKS: Dict[str, type['ComplianceCheck']] = ...
def register_compliance_check(check_type: str) -> Any: ...
class ComplianceCheck(ABC):
    def apply(self: Any, df: Union[pl.DataFrame, pl.LazyFrame], sample_size: Optional[int] = ...) -> Union[pl.DataFrame, pl.LazyFrame]: ...
class ComplianceManager:
    def __init__(self: Any, config: Any, max_workers: int = ...) -> Any: ...
    def add_check(self: Any, check: ComplianceCheck) -> Any: ...
    def enforce(self: Any, data: Any, eager: bool = ..., sample_size: Optional[int] = ...) -> Any: ...
class SchemaCompliance(ComplianceCheck):
    def __init__(self: Any, config: Optional[Dict] = ...) -> Any: ...
    def apply(self: Any, df: Union[pl.DataFrame, pl.LazyFrame], sample_size: Optional[int] = ...) -> Union[pl.DataFrame, pl.LazyFrame]: ...
class GDPRCompliance(ComplianceCheck):
    def __init__(self: Any, config: Optional[Dict] = ...) -> Any: ...
    def apply(self: Any, df: Union[pl.DataFrame, pl.LazyFrame], sample_size: Optional[int] = ...) -> Union[pl.DataFrame, pl.LazyFrame]: ...
class DriftCompliance(ComplianceCheck):
    def __init__(self: Any, config: Optional[Dict] = ...) -> Any: ...
    def apply(self: Any, df: Union[pl.DataFrame, pl.LazyFrame], sample_size: Optional[int] = ...) -> Union[pl.DataFrame, pl.LazyFrame]: ...
