from typing import Any

class Bar:
    timestamp: pl.Datetime = ...
    open: float = ...
    high: float = ...
    low: float = ...
    close: float = ...
    volume: float = ...
    metadata: Mapping[str, Any] = ...
class Tick:
    timestamp: pl.Datetime = ...
    price: float = ...
    size: float = ...
    side: str = ...
    metadata: Mapping[str, Any] = ...
class MarketDataFrameSchema:
    required_columns: Mapping[str, pl.DataType] = ...
    optional_columns: Mapping[str, pl.DataType] = ...
    strict: bool = ...
    unknown_ok: bool = ...
    def from_mapping(cls: Any, raw: Mapping[str, Any]) -> 'MarketDataFrameSchema': ...
    def validate(self: Any, df: pl.DataFrame, *, strict: bool | None = ..., unknown_ok: bool | None = ...) -> tuple[bool, list[str]]: ...
    def assert_valid(self: Any, df: pl.DataFrame, *, strict: bool | None = ..., unknown_ok: bool | None = ..., label: str = ...) -> None: ...
    def to_payload(self: Any) -> dict[str, Any]: ...
