from typing import Any

class BaseDriftTest:
    def compute(self: Any, current: np.ndarray, reference: np.ndarray) -> tuple[float, float]: ...
class KSTest(BaseDriftTest):
    def compute(self: Any, current: np.ndarray, reference: np.ndarray) -> tuple[float, float]: ...
class DriftDetectionParams(BaseModel):
    model_config: Any
    enabled: bool = ...
    threshold: float = ...
    columns: tuple[str, ...] = ...
    strict: bool = ...
    reference_frame: Any | None = ...
class DriftDetectionStep(CleaningStep):
    ...
