from typing import Any

class FSInterface:
    def get_size(self: Any, path: str) -> int: ...
class LocalFS(FSInterface):
    def get_size(self: Any, path: str) -> int: ...
class IOValidationParams(BaseModel):
    model_config: Any
    file_path: str = ...
    format: str | None = ...
    max_size_bytes: int = ...
    fs: FSInterface | None = ...
class IOValidationStep(CleaningStep):
    ...
