from typing import Any

"""
Configuration objects for W3-B technical-indicator experiments.
"""

class IndicatorLibraryConfig:
    lag_bars: int = ...
    redundancy_rank_corr_threshold: float = ...
    panel_float32: bool = ...
    save_long_indicator_rows: bool = ...
    save_selected_rows_only: bool = ...
    robust_indicator_scaling: bool = ...
    robust_scale_iqr_multiplier: float = ...
    robust_scale_min_iqr: float = ...
class W3BPandasTAConfig:
    output_dir: Path = ...
    surfaces: tuple[str, ...] = ...
    xgboost_train_row_cap: int = ...
    xgboost_predict_batch_rows: int = ...
    use_xgboost: bool = ...
    loader_backend: Literal['polars', 'pandas'] = ...
    workers: int = ...
    xgboost_n_jobs: int = ...
    seed: int = ...
    timestamp_utc: str = ...
    indicator_library: IndicatorLibraryConfig = ...
class PenaltyMultiplierSpec:
    formula: str = ...
    reference_liquidity: float = ...
    penalty_term_cap: float = ...
    strength: float = ...
    min_multiplier: float = ...
    calibration: dict[str, float] = ...
    def from_mapping(cls: Any, payload: Mapping[str, object]) -> PenaltyMultiplierSpec: ...
class W3CLiquidityChildConfig:
    output_dir: Path = ...
    surfaces: tuple[str, ...] = ...
    surface_d_audit_path: Path = ...
    w3_b_report_path: Path = ...
    penalty_multiplier_spec: PenaltyMultiplierSpec | None = ...
    xgboost_train_row_cap: int = ...
    xgboost_predict_batch_rows: int = ...
    use_xgboost: bool = ...
    workers: int = ...
    xgboost_n_jobs: int = ...
    seed: int = ...
    timestamp_utc: str = ...
    indicator_library: IndicatorLibraryConfig = ...
    def with_penalty_spec(self: Any, spec: PenaltyMultiplierSpec) -> W3CLiquidityChildConfig: ...
    def require_penalty_spec(self: Any) -> PenaltyMultiplierSpec: ...
