from typing import Any

"""
Diagnostics, orientation, and redundancy pruning for W3-B indicators.
"""

class IndicatorDiagnosticsResult:
    diagnostics: dict[str, dict[str, object]] = ...
    orientations: dict[str, int] = ...
    active_indicators: tuple[str, ...] = ...
    redundancy: dict[str, object] = ...
def build_indicator_diagnostics(rows: pd.DataFrame, *, surface_id: str, indicator_columns: Sequence[str], redundancy_rank_corr_threshold: float, indicator_scales: Mapping[str, Mapping[str, object]] | None = ...) -> IndicatorDiagnosticsResult: ...
def lag_outcome_diagnostic_by_horizon(rows: pd.DataFrame, *, value_column: str, horizon: int) -> pd.Series: ...
def prune_redundant_indicators(rows: pd.DataFrame, *, indicator_columns: Sequence[str], train_validation_scores: Mapping[str, float], threshold: float) -> dict[str, object]: ...
def diagnostics_summary_markdown(report: Mapping[str, object]) -> str: ...
def cast_mapping(value: object) -> Mapping[str, object]: ...
def cast_list(value: object) -> list[str]: ...
