from typing import Any

"""
pandas-ta-classic provider for compact W3-B indicator feature panels.
"""

class IndicatorProviderResult:
    features: pd.DataFrame = ...
    indicator_columns: tuple[str, ...] = ...
    provider_mappings: dict[str, dict[str, object]] = ...
    warmup: dict[str, int] = ...
def compute_pandas_ta_classic_features(panel: pd.DataFrame, config: IndicatorLibraryConfig | None = ..., *, workers: int = ...) -> IndicatorProviderResult: ...
