from typing import Any

"""
Indicator registry for the W3-B pandas-ta-classic library.
"""

class IndicatorDefinition:
    indicator_id: str = ...
    category: IndicatorCategory = ...
    source: str = ...
    parameters: dict[str, int | float | str] = ...
def indicator_definitions() -> tuple[IndicatorDefinition, ...]: ...
def indicator_ids() -> tuple[str, ...]: ...
def indicator_category_map() -> dict[str, IndicatorCategory]: ...
def indicator_config_payload() -> dict[str, object]: ...
