from typing import Any

"""
Robust winsorization and scaling for W3-B indicator diagnostics and scoring.
"""

class IndicatorRobustScale:
    indicator_id: str = ...
    median: float = ...
    iqr: float = ...
    mad: float = ...
    lower_clip: float = ...
    upper_clip: float = ...
    scale_denominator: float = ...
    train_validation_fit_only: bool = ...
    iqr_multiplier: float = ...
    def as_metadata(self: Any) -> dict[str, object]: ...
def sanitize_indicator_series(values: pd.Series) -> pd.Series: ...
def fit_robust_indicator_scales(rows: pd.DataFrame, indicator_columns: Sequence[str], *, iqr_multiplier: float = ..., min_iqr: float = ...) -> dict[str, IndicatorRobustScale]: ...
def apply_robust_indicator_scales(rows: pd.DataFrame, scales: Mapping[str, IndicatorRobustScale], *, copy: bool = ...) -> pd.DataFrame: ...
def robust_scale_metadata_payload(scales: Mapping[str, IndicatorRobustScale]) -> dict[str, dict[str, object]]: ...
