from typing import Any

"""
Schema constants for the W3-B pandas-ta-classic indicator surface.
"""

W3B_INDICATOR_SCHEMA_VERSION: Final[str] = ...
W3B_PROVIDER_NAME: Final[str] = ...
IndicatorCategory: Any
IndicatorClassification: Any
REQUIRED_PROVIDER_INPUT_COLUMNS: Final[tuple[str, ...]] = ...
W3B_INDICATOR_IDS: Final[tuple[str, ...]] = ...
W3B_TA_CHILD_POLICY_IDS: Final[tuple[str, ...]] = ...
W3B_CANONICAL_XGB_IDS: Final[tuple[str, str, str]] = ...
W3B_REFERENCE_CHILD_POLICY_IDS: Final[tuple[str, ...]] = ...
W3B_ALLOWED_CLASSIFICATIONS: Final[tuple[str, ...]] = ...
W3C_SURFACE_D_AUDIT_SCHEMA_VERSION: Final[str] = ...
W3C_LIQUIDITY_CHILD_REPORT_SCHEMA_VERSION: Final[str] = ...
W3C_LIQUIDITY_CHILD_POLICY_REPORT_SCHEMA_VERSION: Final[str] = ...
W3C_CANONICAL_XGB_POLICY_ID: Final[str] = ...
W3C_D_RECOVERY_UTILITY_ANCHOR: Final[float] = ...
W3C_B_RETENTION_GUARDRAIL: Final[float] = ...
W3C_MIN_TEST_DATE_PARTICIPATION_RATE: Final[float] = ...
W3C_LIQUIDITY_CHILD_POLICY_IDS: Final[tuple[str, ...]] = ...
W3C_CLASSIFICATIONS: Final[tuple[str, ...]] = ...
