from typing import Any

"""
Signal catalog with stable slot_index at registration (Phase I-E).

Signal ABC: __call__(data, params) -> pl.Series; signal_embedding placeholder;
slot_index assigned at registration, immutable. SignalCatalog maintains monotonic
slot assignment; register() is idempotent by spec_hash (re-registration returns
existing slot_index). No slot reuse in Phase I.
"""

class SignalProtocol(Protocol):
    def signal_embedding(self: Any) -> Optional[np.ndarray[Any, np.dtype[np.floating]]]: ...
    def slot_index(self: Any) -> int: ...
class RegisteredSignal:
    def __init__(self: Any, impl: SignalProtocol, slot_index: int, spec_hash: str, signal_name: str) -> None: ...
    def signal_embedding(self: Any) -> Optional[np.ndarray[Any, np.dtype[np.floating]]]: ...
    def slot_index(self: Any) -> int: ...
    def spec_hash(self: Any) -> str: ...
    def signal_name(self: Any) -> str: ...
class SignalCatalog:
    def __init__(self: Any) -> None: ...
    def register(self: Any, signal: SignalProtocol, spec_hash: str | None = ..., signal_name: str = ...) -> int: ...
    def get_by_spec_hash(self: Any, spec_hash: str) -> RegisteredSignal | None: ...
    def get_by_slot(self: Any, slot_index: int) -> RegisteredSignal | None: ...
def create_starter_spread_zscore() -> _StubSignal: ...
def create_starter_hedge_ratio() -> _StubSignal: ...
def create_starter_TSMOM() -> _StubSignal: ...
def create_starter_XSMOM() -> _StubSignal: ...
def create_starter_RSI_baseline() -> _StubSignal: ...
def get_catalog() -> SignalCatalog: ...
