from typing import Any

class BacktraderEngineAdapter:
    def __init__(self: Any, config: dict[str, Any] | None = ...) -> None: ...
    def run(self: Any, plan: Any, data: Any, store: Any) -> Any: ...
class Backtester(BacktraderEngineAdapter):
    ...
