from typing import Any

"""
FeatureAdapterRegistry: versioned registry for feature pipeline adapters.
"""

class FeatureAdapterProtocol(Protocol):
    def transform(self: Any, data: pd.DataFrame, params: dict[str, Any]) -> pd.DataFrame: ...
def register(name: str, version: str) -> Callable[[type[FeatureAdapterProtocol]], type[FeatureAdapterProtocol]]: ...
def get(name: str, version: str = ...) -> type[FeatureAdapterProtocol]: ...
def list_registered() -> list[tuple[str, str]]: ...
