from typing import Any

"""
ModelRegistry: versioned registry for trainable model factories.
"""

class ModelFactory(Protocol):
    ...
def register(name: str, version: str) -> Callable[[ModelFactory], ModelFactory]: ...
def get(name: str, version: str = ...) -> ModelFactory: ...
def list_registered() -> list[tuple[str, str]]: ...
