from typing import Any

pd: Any
pl: Any
dd: Any
np: Any
yaml: Any
pynvml: Any
psutil: Any
BackendLiteral: Any
def expand_grid(base: Mapping[str, Iterable[Any]], constraints: Optional[List[Callable[[Dict[str, Any]], bool]]] | None = ...) -> Any: ...
def stage(name: Optional[str] = ..., timeout_s: Optional[int] = ...) -> Any: ...
class DataFrameAdapter:
    def __init__(self: Any, df: Any) -> Any: ...
    def shape(self: Any) -> Any: ...
    def columns(self: Any) -> Any: ...
    def hash(self: Any) -> Any: ...
class ConfigProxy:
    def __init__(self: Any, data: Any) -> Any: ...
    def get(self: Any, path: Any, default: Any = ...) -> Any: ...
class BackendManager:
    HAS_POLARS: Any
    HAS_PANDAS: Any
    HAS_DASK: Any
    def require_polars(cls: Any) -> Any: ...
class Evolver:
    def __init__(self: Any, cache: Any, version_tag: Any, code_id: Any) -> Any: ...
    def load(self: Any, context_hash: Any) -> Any: ...
    def save(self: Any, context_hash: Any, trials: Any) -> Any: ...
    def shrink_grid(self: Any, grid: Any, prior_trials: Any, quantile: Any = ...) -> Any: ...
logger: Any
run_cfg: Any
class DataPrepError(Exception):
    ...
class ConfigError(DataPrepError):
    ...
class DataValidationError(DataPrepError):
    ...
class OrchestratorConfig:
    per_symbol_parallelism: Union[int, str] = ...
    gpu_slots: Union[int, str] = ...
    lazy: bool = ...
    date_chunk_size: Optional[str] = ...
    cache_version_tag: str = ...
    cache_checkpoints: bool = ...
    search_mode: str = ...
    n_trials: int = ...
    metric_name: str = ...
class DataPrepOrchestrator:
    run_id: Optional[str] = ...
    cfg: Dict[str, Any] = ...
    run_cfg: Dict[str, Any] = ...
    run_cfg_raw: Dict[str, Any] = ...
    code_id: Optional[str] = ...
    ocfg: OrchestratorConfig = ...
    cache: Any = ...
    backtest_metric: Optional[Callable[[Any, Any, Mapping[str, Any], Mapping[str, Any]], float]] = ...
    def __init__(self: Any, run_cfg: Mapping[str, Any] | Any, cache: Any = ..., backtest_metric: Optional[Callable[[Any, Any, Mapping[str, Any], Mapping[str, Any]], float]] = ..., entry_point_groups: Optional[List[Tuple[str, str]]] = ...) -> None: ...
    def run(self: Any) -> Union['pd.DataFrame', 'pl.DataFrame', Dict[str, Any]]: ...
    def preprocess_multi_symbol(self: Any, clean_df: Union['pl.DataFrame', 'pd.DataFrame'], preset: Mapping[str, Any], params: Mapping[str, Any]) -> Dict[str, Tuple[Any, Any, Mapping[str, Any]]]: ...
    def adaptive_map(self: Any, fn: Any, items: Any, kind: str = ..., max_workers: int | None = ...) -> Any: ...
def run_dataprep(run_cfg: Mapping[str, Any] | Any, backtest_metric: Optional[Callable[[Any, Any, Mapping[str, Any], Mapping[str, Any]], float]] = ...) -> Any: ...
def run_dataprep_from_path(run_cfg_path: Union[str, Path], backtest_metric: Callable[[Any, Any, Mapping[str, Any], Mapping[str, Any]], float]) -> Dict[str, Any]: ...
class Cache:
    def save_df(self: Any, key: str, df: Any) -> None: ...
