from typing import Any

II0C_GOVERNED_SUMMARY_FILENAME: Final[str] = ...
II0C_GOVERNED_SUMMARY_SCHEMA: Final[str] = ...
II0C_WRAPPED_PHASE: Final[str] = ...
II0C_SCAFFOLD_PHASE: Final[str] = ...
class II0CGovernedArtifactError(PhaseIIArtifactError):
    ...
class II0CGovernedArtifactResult:
    output_dir: Path = ...
    wrapper_summary_path: Path = ...
    shell_result: Phase2MLEvidenceShellResult = ...
    wrapper_summary: dict[str, Any] = ...
def emit_ii0c_governed_artifacts(*, run_context: PhaseIIRunContext) -> II0CGovernedArtifactResult: ...
