from typing import Any

LOG: Any
def run_dataprep(*args: Any, **kwargs: Any) -> Any: ...
def run_dataprep_from_path(*args: Any, **kwargs: Any) -> Any: ...
class OrchestratorConfig:
    input_path: Path = ...
    fast_sma: int = ...
    slow_sma: int = ...
    bundle_dir: Path | None = ...
def run_orchestration(config: OrchestratorConfig) -> tuple[int, dict[str, Any]]: ...
def run(strategy_id: str, ctx: StrategyContext, strategy_kwargs: dict[str, Any], bundle_dir: Path, *, pit_input: PITSafeDataView | DataViewAsOfAdapter | None = ..., knowledge_dates: List[datetime] | None = ..., source_prices: pd.DataFrame | None = ..., run_metadata: dict[str, Any] | None = ..., strategy_instance: Any | None = ..., run_id: str | None = ..., run_registry: RunRegistry | None = ..., cas: LocalCAS | None = ..., splits_manifest_override: dict[str, Any] | None = ...) -> RunBundle: ...
