from typing import Any

PHASE2_II0C_EVIDENCE_SUBDIR: Any
II0C_DRY_RUN_SUMMARY_FILENAME: Any
II0C_DRY_RUN_SUMMARY_LEGACY_FILENAME: Any
II0C_PILOT_REPORT_FILENAME: Any
PHASE2_II0C_SUMMARY_FILENAME: Any
II0C_DRY_RUN_REPORT_SCHEMA: Any
II0C_PILOT_REPORT_SCHEMA: Any
PHASE2_II0C_SUMMARY_SCHEMA: Any
PHASE2_II0C_PHASE: Any
PHASE2_II0C_GATE_II_STATUS: Any
II0C_PILOT_SEMANTIC_OUTCOME_OK: Any
II0C_FAIL_CLOSED_CHECKS: tuple[str, ...] = ...
UNAVAILABLE_II0C_PROOF_SURFACES: tuple[str, ...] = ...
class II0CTaskProvider(Protocol):
    ...
class II0CEncoderProvider(Protocol):
    ...
class II0CComparisonProvider(Protocol):
    ...
class II0CGovernedArtifactEmitter(Protocol):
    ...
class Phase2II0CRunRequest:
    bundle_dir: Path = ...
    seed: int = ...
    strategy_id: str = ...
    source_prices: Any | None = ...
    run_metadata: Mapping[str, Any] | None = ...
class Phase2II0CComparisonPack:
    dataset_manifest: Mapping[str, Any] = ...
    baseline_comparison: Mapping[str, Any] = ...
    shared_comparison_context: Mapping[str, Any] = ...
    cost_model: Mapping[str, Any] = ...
    slippage_model: Mapping[str, Any] = ...
    borrow_funding: Mapping[str, Any] = ...
    latency_fill: Mapping[str, Any] = ...
    inner_loop_gain_by_regime: Mapping[str, Any] = ...
    harvey_t_statistic: float | int = ...
    encoder_coherence_score: float | int = ...
    crisis_episode_ic: float | int = ...
    forgetting_metric: float | int = ...
    plasticity_metric: float | int = ...
    entry_conditions: Mapping[str, Any] = ...
    confidence_calibration: Mapping[str, Any] = ...
    overall_result: str = ...
    run_seed_root: str | None = ...
    seed_derivations: Sequence[tuple[str, str]] = ...
class Phase2II0CProviders:
    task_provider: Callable[[Phase2II0CRunRequest], II0CMetaTaskPayload] | None = ...
    encoder_provider: Callable[[Phase2II0CRunRequest, II0CMetaTaskPayload], II0CEncoderTaskOutput] | None = ...
    comparison_provider: Callable[[Phase2II0CRunRequest, II0CMetaTaskPayload, II0CEncoderTaskOutput], Phase2II0CComparisonPack] | None = ...
class Phase2II0CRunResult:
    phase: str = ...
    scaffold: bool = ...
    non_promotable: bool = ...
    gate_ii_deferred: bool = ...
    run_mode: str = ...
    pilot_semantic_outcome: str = ...
    governed_evidence_dir: Path = ...
    governed_artifact_summary: dict[str, Any] = ...
    pilot_report_path: Path = ...
    pilot_report: dict[str, Any] = ...
    task: TaskManifestTaskInput = ...
    task_payload: II0CMetaTaskPayload = ...
    encoder_output: II0CEncoderTaskOutput = ...
    comparison_pack: Phase2II0CComparisonPack = ...
class II0CRunResult:
    phase: str = ...
    non_promotable: bool = ...
    scaffold_only: bool = ...
    gate_ii_status: str = ...
    run_mode: str = ...
    dry_run_semantic_outcome: str = ...
    summary_path: Path = ...
    governed_evidence_dir: Path = ...
    governed_result: II0CGovernedArtifactResult = ...
    summary: dict[str, Any] = ...
def default_ii0c_task_provider(*, seed: int, timestamp_utc: str) -> II0CMetaTaskPayload: ...
def default_ii0c_encoder_provider(*, task_payload: II0CMetaTaskPayload, seed: int) -> II0CEncoderTaskOutput: ...
def default_ii0c_comparison_provider(*, task_payload: II0CMetaTaskPayload, seed: int) -> Phase2II0CComparisonBundle: ...
def run_phase2_ii0c_pilot(request: Phase2II0CRunRequest, *, providers: Phase2II0CProviders | None = ...) -> Phase2II0CRunResult: ...
def run_phase2_ii0c_dry_run(*, output_dir: Path, seed: int, timestamp_utc: str, task_provider: II0CTaskProvider = ..., encoder_provider: II0CEncoderProvider = ..., comparison_provider: II0CComparisonProvider = ..., artifact_emitter: II0CGovernedArtifactEmitter = ...) -> II0CRunResult: ...
