from typing import Any

pl: Any
class BacktestingSplitNormalizerStep(PipelineStep):
    is_fast: Any
    def __init__(self: Any, cfg: Any) -> Any: ...
    def apply_batch(self: Any, lf: 'pl.LazyFrame', ctx: PipelineContext) -> 'pl.LazyFrame': ...
    def apply_batch_pandas(self: Any, df: pd.DataFrame, ctx: PipelineContext) -> pd.DataFrame: ...
