from typing import Any

"""
EventRouter: routes typed tuning events to registered handlers.
"""

class TuningEvent:
    kind: str = ...
    payload: dict[str, Any] = ...
Handler: Any
class EventRouter:
    def __init__(self: Any) -> None: ...
    def register(self: Any, kind: str, handler: Handler) -> None: ...
    def route(self: Any, event: TuningEvent) -> None: ...
