from typing import Any

"""
OnlineFeatureBuffer: accumulates streaming observations for online feature computation.
"""

class OnlineFeatureBuffer:
    def __init__(self: Any, capacity: int) -> None: ...
    def push(self: Any, observation: dict[str, Any]) -> None: ...
    def snapshot(self: Any) -> list[dict[str, Any]]: ...
    def size(self: Any) -> int: ...
