from typing import Any

"""
RuntimeState: mutable snapshot of the live system's active model and configuration.
"""

class RuntimeState:
    job_id: str = ...
    active_artifact_hash: str = ...
    activated_at: datetime = ...
    shadow_candidate_id: str | None = ...
    last_drift_score: float = ...
    last_retrain_at: datetime | None = ...
    tags: dict[str, str] = ...
    def update_drift(self: Any, score: float) -> None: ...
    def record_retrain(self: Any, now: datetime) -> None: ...
