from typing import Any

"""
StreamListener: consumes a real-time data stream and emits typed events.
"""

EventCallback: Any
class StreamListener:
    def __init__(self: Any) -> None: ...
    def subscribe(self: Any, callback: EventCallback) -> None: ...
    def start(self: Any) -> None: ...
    def stop(self: Any) -> None: ...
