from typing import Any

"""
TriggerCapture: detects drift events and emits retrain triggers.
"""

class DriftTrigger:
    job_id: str = ...
    drift_score: float = ...
    threshold: float = ...
    detected_at: datetime = ...
    feature_hash: str = ...
class TriggerCapture:
    def __init__(self: Any, threshold: float, job_id: str) -> None: ...
    def evaluate(self: Any, drift_score: float, feature_hash: str, now: datetime) -> DriftTrigger | None: ...
