from typing import Any

"""
CachePlan: which intermediate results should be cached and at which granularity.
"""

class CacheEntry:
    key: str = ...
    scope: Literal['spec', 'ir', 'plan', 'feature', 'artifact'] = ...
    ttl_seconds: int | None = ...
class CachePlan:
    job_id: str = ...
    entries: tuple[CacheEntry, ...] = ...
    default_ttl_seconds: int | None = ...
