from typing import Any

"""
ExecutionPlan: fully resolved plan for a complete tuning job.
"""

class ExecutionPlan:
    job_id: str = ...
    search_plan: SearchPlan = ...
    n_folds: int = ...
    n_candidates_per_step: int = ...
    feature_hash: str = ...
    meta: PlanMetadata = ...
