from typing import Any

"""
PartitionPlan: how a job is split across symbols, time windows, folds, and tasks.
"""

class TimePartition:
    name: str = ...
    start: datetime = ...
    end: datetime = ...
class PartitionPlan:
    job_id: str = ...
    symbols: tuple[str, ...] = ...
    time_partitions: tuple[TimePartition, ...] = ...
    n_folds: int = ...
    n_total_tasks: int = ...
