from typing import Any

"""
Base plan types and execution budget model.
"""

class ExecutionBudget:
    max_trials: int = ...
    timeout_seconds: int | None = ...
    max_parallel: int = ...
    priority: Literal['throughput', 'latency', 'cost'] = ...
class PlanMetadata:
    plan_hash: str = ...
    spec_hash: str = ...
    created_at_ns: int = ...
    determinism_tier: str = ...
