from typing import Any

"""
SearchPlan: executable plan derived from SearchIR + budget.
"""

class SearchStep:
    step_index: int = ...
    n_candidates: int = ...
    algorithm_snapshot: str = ...
    partition_id: str = ...
class SearchPlan:
    job_id: str = ...
    space_hash: str = ...
    steps: tuple[SearchStep, ...] = ...
    budget: ExecutionBudget = ...
    meta: PlanMetadata = ...
