from typing import Any

class OutlierParams(BaseModel):
    model_config: Any
    method: Literal['zscore', 'iqr'] = ...
    threshold: float = ...
    factor: float = ...
class OutlierNormalizerStep(CleaningStep):
    ...
