from typing import Any

"""
Context encoder contract stubs for Phase II meta-learning surfaces.
"""

TASK_EPISODE_ENCODER_FEATURE_SCHEMA_VERSION: Final[str] = ...
TASK_EPISODE_BOUNDARY_FLAG_ORDER: Final[tuple[str, ...]] = ...
TASK_EPISODE_ENCODER_FEATURE_NAMES: Final[tuple[str, ...]] = ...
class EncoderInputContract:
    regime_features: np.ndarray[Any, Any] = ...
    pit_boundary: datetime = ...
    signal_set_version: int = ...
    schema_version: str = ...
class EncoderOutputContract:
    regime_embedding: np.ndarray[Any, np.dtype[np.float32]] = ...
    schema_version: str = ...
def build_task_episode_encoder_input(*, regime_label: RegimeLabelRecord, pit_boundary: datetime, signal_set_version: int) -> EncoderInputContract: ...
class ContextEncoderProtocol(Protocol):
    def encode(self: Any, input: EncoderInputContract) -> EncoderOutputContract: ...
    def is_frozen(self: Any) -> bool: ...
