from typing import Any

"""
TaskRegistry contract stubs for Phase II meta-learning surfaces.
"""

class TaskRegistryError(Exception):
    def __init__(self: Any, message: str, *, details: dict[str, object] | None = ...) -> None: ...
class TaskNotFoundError(TaskRegistryError):
    def __init__(self: Any, message: str, *, details: dict[str, object] | None = ...) -> None: ...
class TaskRegistryDuplicateError(TaskRegistryError):
    def __init__(self: Any, message: str, *, details: dict[str, object] | None = ...) -> None: ...
class TaskRegistryProtocol(Protocol):
    CONTRACT_VERSION: ClassVar[str] = ...
    def append(self: Any, task: MetaTask) -> None: ...
    def get(self: Any, task_id: str) -> MetaTask: ...
    def query(self: Any, regime_id: str | None = ..., since: str | None = ...) -> list[MetaTask]: ...
