from typing import Any

class CPCVConfig:
    n_splits: int = ...
    n_test_paths: int = ...
class ProductionValidationProfile:
    profile_id: str = ...
    dsr_p_value_max: float = ...
    min_trl_target_confidence: float = ...
    pbo_max: float = ...
    cpcv: CPCVConfig = ...
    def to_dict(self: Any) -> dict[str, object]: ...
PRODUCTION_V1_PROFILE: Any
