from typing import Any

logger: Any
class MarketCalendar(ABC):
    def is_open_at(self: Any, ts: datetime) -> bool: ...
    def next_open(self: Any, ts: datetime) -> datetime: ...
    def next_close(self: Any, ts: datetime) -> datetime: ...
class FallbackCalendar(MarketCalendar):
    def is_open_at(self: Any, ts: datetime) -> bool: ...
    def next_open(self: Any, ts: datetime) -> datetime: ...
    def next_close(self: Any, ts: datetime) -> datetime: ...
def profile_calendar(func: Callable) -> Callable: ...
class MarketCalendarFactory:
    def get_calendar(exchange: str = ..., governed: bool = ...) -> MarketCalendar: ...
def is_session(ts: Optional[datetime] = ..., cal: Optional[MarketCalendar] = ...) -> bool: ...
def next_session(ts: Optional[datetime] = ..., cal: Optional[MarketCalendar] = ...) -> datetime: ...
def time_bucket(ts: datetime, seconds: int) -> datetime: ...
def resample_ohlcv(df: Any, ts_col: str, seconds: int, engine: Optional[str] = ...) -> Any: ...
