from typing import Any

"""
Core financial metrics used in objective scoring.
"""

def sharpe_ratio(returns: pd.Series, ann_factor: float = ...) -> float: ...
def max_drawdown(returns: pd.Series) -> float: ...
def turnover_ratio(positions: pd.DataFrame) -> float: ...
def calmar_ratio(returns: pd.Series, ann_factor: float = ...) -> float: ...
