from typing import Any

class ErrorCodeEnum(str, Enum):
    GENERIC: Any
    DATA_FETCH: Any
    API_CONNECTION: Any
    STREAM_CONNECTION: Any
    DATA_TIMEOUT: Any
    DATA_VALIDATION: Any
    SCHEMA_VALIDATION: Any
    FILE_FORMAT: Any
    STATISTICAL_TEST: Any
    DATA_DRIFT: Any
    NO_DATA: Any
    CONFIG_VALIDATION: Any
    PREPROCESSING: Any
    MODEL_TRAINING: Any
    TRADING_EXECUTION: Any
    INVALID_INPUT: Any
    DATA_PRECONDITION: Any
    MODEL_CHECKPOINT: Any
    MODEL_INFERENCE: Any
    UNSUPPORTED_PLAN: Any
    PIT_VIOLATION: Any
    STALENESS: Any
class BaseError(RuntimeError):
    def __init__(self: Any, msg: str, *, code: Optional[str] = ..., details: Optional[Dict[str, Any]] = ..., cause: Optional[BaseException] = ...) -> Any: ...
    def to_dict(self: Any) -> Dict[str, Any]: ...
class UnsupportedPlan(BaseError):
    def __init__(self: Any, msg: str = ..., **kwargs: Any) -> Any: ...
class DataError(BaseError, ABC):
    def __init__(self: Any, message: str, details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class GenericDataError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class ExceptionRegistry:
    def register(cls: Any, error_type: str, exception_class: Type[DataError]) -> None: ...
    def get_exception(cls: Any, error_type: str, message: str, details: Optional[Dict[str, Any]] = ...) -> DataError: ...
class AggregateError(DataError):
    def __init__(self: Any, message: str = ..., errors: Optional[List[DataError]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
    def add_error(self: Any, error: DataError) -> None: ...
class DataFetchError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class APIConnectionError(DataFetchError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class StreamConnectionError(DataFetchError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class DataTimeoutError(DataFetchError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class DataValidationError(DataError):
    def __init__(self: Any, message: str = ..., codes: Optional[List['DataValidationError.Code']] = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class SchemaValidationError(DataValidationError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class FileFormatError(DataValidationError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class PITViolationError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class StalenessError(PITViolationError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class StatisticalTestError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class DataDriftError(StatisticalTestError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class IBKRConnectionError(StreamConnectionError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class NoDataError(DataFetchError):
    def __init__(self: Any, symbol: str, details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class ConfigValidationError(DataError):
    def __init__(self: Any, message: str = ..., validation_errors: Optional[List[str]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class PreprocessingError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class ModelTrainingError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class TradingExecutionError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class InvalidInputError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class DataPreconditionError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class ModelCheckpointError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
class ModelInferenceError(DataError):
    def __init__(self: Any, message: str = ..., details: Optional[Dict[str, Any]] = ...) -> Any: ...
    def get_error_code(self: Any) -> str: ...
