from typing import Any

def atomic_write_bytes(target_path: Path, data: bytes, *, fsync: bool = ...) -> None: ...
def atomic_write_json(target_path: Path, obj: Any, *, fsync: bool = ...) -> None: ...
