from typing import Any

class BundleBacktestArtifactStore:
    def __init__(self: Any, writer: BundleWriter) -> None: ...
    def bundle_dir(self: Any) -> Path: ...
    def put_json(self: Any, role: str, payload: dict[str, Any]) -> ArtifactRef: ...
    def put_bytes(self: Any, role: str, payload: bytes, media_type: str) -> ArtifactRef: ...
    def get_json(self: Any, ref: ArtifactRef | str) -> dict[str, Any]: ...
