from typing import Any

class HashRefLike(Protocol):
    domain: str = ...
    algo: str = ...
    digest: str = ...
    def to_id_string(self: Any) -> str: ...
class LocalCASProtocol(Protocol):
    def put_json(self: Any, payload: Mapping[str, Any]) -> Any: ...
    def put_bytes(self: Any, payload: bytes, *, media_type: str) -> Any: ...
class ArtifactHashPair:
    cas: HashRefLike = ...
    attest: HashRefLike = ...
    canonical_bytes: bytes = ...
class ArtifactEntry:
    path: str = ...
    cas: HashRefLike = ...
    attest: HashRefLike = ...
    media_type: str = ...
    size: int = ...
    def to_manifest_dict(self: Any) -> dict[str, Any]: ...
class ArtifactAttestor:
    cas: LocalCASProtocol = ...
    def attest_json(self: Any, payload: Mapping[str, Any], *, bundle_path: str, media_type: str = ...) -> ArtifactEntry: ...
    def attest_bytes(self: Any, payload: bytes, *, bundle_path: str, media_type: str) -> ArtifactEntry: ...
    def to_gate_content_hash(self: Any, attest: HashRefLike) -> str: ...
class BundleManifestWriter:
    output_root: Path = ...
    hash_policy: Mapping[str, str] = ...
    def write(self: Any, *, artifacts: Mapping[str, ArtifactEntry], created_at: datetime | None = ..., schema_version: str = ..., filename: str = ..., extra: Mapping[str, Any] | None = ...) -> Path: ...
def build_artifact_entry(*, path: str, cas: HashRefLike, attest: HashRefLike, media_type: str, size: int) -> ArtifactEntry: ...
def bundle_entries_from_sequence(entries: Sequence[tuple[str, ArtifactEntry]]) -> dict[str, ArtifactEntry]: ...
