from typing import Any

"""
Canonical Appendix C bundle writer owned by ``pysrc.artifact_registry``.
"""

BUNDLE_SCHEMA_VERSION: Any
class BundleWriter:
    SCHEMA_VERSION: Any
    def __init__(self: Any, output_dir: Path, *, cas: LocalCAS | None = ..., run_registry: RunRegistry | None = ..., run_id: str | None = ...) -> None: ...
    def write_plan(self: Any, plan_hash: str, config_hash: str, as_of_time: str, config: dict[str, Any]) -> None: ...
    def write_env_fingerprint(self: Any) -> None: ...
    def write_dataset_manifest(self: Any, dataset_id: str, symbols: list[str], row_count: int, time_range: dict[str, str], *, pit_compliant: bool = ..., knowledge_time_column: str = ..., content_hash: str | None = ..., download_timestamp: str | None = ..., content_hash_expected: str | None = ...) -> None: ...
    def write_preprocessing_report(self: Any, steps: list[dict[str, Any]], timings: dict[str, float], warnings: list[str]) -> None: ...
    def write_splits_manifest(self: Any, splits: list[dict[str, Any]], split_method: str, purge_window: int, embargo_window: int) -> None: ...
    def write_stat_validity_report(self: Any, report: dict[str, Any]) -> None: ...
    def write_screening_report(self: Any, payload: dict[str, Any]) -> None: ...
    def write_cleaning_plan(self: Any, payload: dict[str, Any]) -> None: ...
    def write_cleaning_report(self: Any, payload: dict[str, Any]) -> None: ...
    def missing_required(self: Any) -> list[str]: ...
    def compute_config_hash(config: dict[str, Any]) -> str: ...
    def write_bundle_manifest(self: Any) -> None: ...
    def read_plan(self: Any) -> 'PlanRecord': ...
    def read_env_fingerprint(self: Any) -> 'EnvFingerprintRecord': ...
    def read_dataset_manifest(self: Any) -> 'DatasetManifestRecord': ...
    def read_preprocessing_report(self: Any) -> 'PreprocessingReportRecord': ...
    def read_splits_manifest(self: Any) -> 'SplitsManifestRecord': ...
