from typing import Any

class HashRefs:
    cas: HashRef = ...
    attest: HashRef | None = ...
    size: int = ...
    media_type: str | None = ...
    canonical_bytes: bytes = ...
    def to_lineage_dict(self: Any, *, schema_version: str | None = ..., determinism_tier: str | None = ...) -> dict[str, str]: ...
class LocalCAS:
    CAS_DIR_NAME: Any
    ATTEST_INDEX_NAME: Any
    def __init__(self: Any, root: Path) -> None: ...
    def put_json(self: Any, obj: dict[str, Any] | list[Any], media_type: str = ...) -> HashRefs: ...
    def put_bytes(self: Any, data: bytes, media_type: str, logical_name: str | None = ...) -> HashRefs: ...
    def get_bytes(self: Any, cas: HashRef | str) -> bytes: ...
    def materialize(self: Any, cas: HashRef | str, path: Path) -> None: ...
    def exists(self: Any, cas: HashRef | str) -> bool: ...
    def verify(self: Any, cas: HashRef | str) -> bool: ...
    def verify_or_raise(self: Any, cas: HashRef | str) -> None: ...
    def resolve_attest(self: Any, attest: HashRef | str) -> HashRef | None: ...
