from typing import Any

def store_model_snapshot_manifest(cas: LocalCAS, run_registry: RunRegistry, run_id: str, manifest: dict[str, Any]) -> HashRefs: ...
def store_task_manifest(cas: LocalCAS, run_registry: RunRegistry, run_id: str, manifest: dict[str, Any]) -> HashRefs: ...
