from typing import Any

LOG: Any
class RunStatus(str, Enum):
    REGISTERING: Any
    COMPLETE: Any
    FAILED: Any
class RunArtifact:
    role: str = ...
    cas: HashRef = ...
    attest: HashRef | None = ...
    media_type: str | None = ...
    size: int = ...
class RunRecord:
    run_id: str = ...
    status: RunStatus = ...
    created_at: str = ...
    updated_at: str = ...
    artifacts: list[RunArtifact] = ...
    metadata: dict[str, Any] = ...
class RunRegistry:
    INDEX_FILENAME: Any
    TRIAL_COUNTERS_FILENAME: Any
    def __init__(self: Any, root: Path) -> None: ...
    def begin_run(self: Any, metadata: dict[str, Any] | None = ...) -> str: ...
    def add_artifact(self: Any, run_id: str, role: str, hashes: HashRefs) -> None: ...
    def finalize_run(self: Any, run_id: str, status: RunStatus = ...) -> None: ...
    def get_run(self: Any, run_id: str, *, include_incomplete: bool = ..., include_failed: bool = ...) -> RunRecord | None: ...
    def iter_runs(self: Any, *, status_filter: Iterable[RunStatus] | None = ...) -> Iterator[RunRecord]: ...
    def record_trial(self: Any, family: str = ...) -> int: ...
    def get_trial_count(self: Any, family: str = ...) -> int: ...
