from typing import Any

logger: Any
class ColumnOp(ABC):
    def apply(self: Any, df: Any, cols: Iterable[str], **kwargs: Any) -> Any: ...
    def validate(self: Any, df: Any, cols: Iterable[str]) -> None: ...
def profile_op(func: Callable) -> Callable: ...
class CastNumeric(ColumnOp):
    def apply(self: Any, df: Any, cols: Iterable[str], dtype: Any = ..., governed: bool = ...) -> Any: ...
class PromoteCategorical(ColumnOp):
    def apply(self: Any, df: Any, cols: Iterable[str], ordered: bool = ..., governed: bool = ..., **kwargs: Any) -> Any: ...
class ColumnOpFactory:
    registry: Dict[str, Callable[..., ColumnOp]] = ...
    def register(cls: Any, name: str, op_class: Callable[..., ColumnOp]) -> Any: ...
    def build(cls: Any, name: str, **kwargs: Any) -> ColumnOp: ...
def op_chain(*op_names: str, **kwargs: Any) -> Callable: ...
def live_after(cols: Iterable[str]) -> List[str]: ...
def ensure_unique(cols: Iterable[str], sep: str = ...) -> List[str]: ...
def save_metrics(file: str = ...) -> Any: ...
