from typing import Any

"""
Fixed-shape masks, slot masks, and active-k masks for candidate selection.
"""

class SlotMask:
    mask: NDArray[np.bool_] = ...
    n_active: int = ...
    def from_k(cls: Any, total_slots: int, k: int) -> SlotMask: ...
    def active_indices(self: Any) -> NDArray[np.intp]: ...
