from typing import Any

"""
Primitive IR node/value types shared across all IR objects.
"""

class Scalar:
    name: str = ...
    value: float = ...
    units: str = ...
class HParam:
    name: str = ...
    value: Any = ...
class IRMetadata:
    spec_hash: str = ...
    created_at_ns: int = ...
    determinism_tier: str = ...
    tags: dict[str, str] = ...
