from typing import Any

"""
ObjectiveIR: canonical IR for a composite objective function.
"""

class PenaltySpec:
    name: str = ...
    coefficient: float = ...
class ObjectiveIR:
    job_id: str = ...
    direction: Literal['maximize', 'minimize'] = ...
    metrics: tuple[str, ...] = ...
    weights: dict[str, float] = ...
    penalties: tuple[PenaltySpec, ...] = ...
    constraints: tuple[Scalar, ...] = ...
    meta: IRMetadata = ...
