from typing import Any

"""
PromotionIR: canonical IR for a promotion/rollout workflow.
"""

class PromotionIR:
    job_id: str = ...
    candidate_id: str = ...
    mode: Literal['shadow', 'capped_blend', 'full'] = ...
    shadow_duration_days: int = ...
    rollback_policy: Literal['auto', 'manual', 'none'] = ...
    approval_required: bool = ...
    meta: IRMetadata = ...
    blend_cap: float | None = ...
