from typing import Any

"""
SearchIR: canonical IR for the search algorithm state.
"""

class Trial:
    trial_id: str = ...
    params: tuple[HParam, ...] = ...
    scores: dict[str, float] = ...
    feasible: bool = ...
class SearchIR:
    job_id: str = ...
    algorithm: str = ...
    space_hash: str = ...
    meta: IRMetadata = ...
    trials: tuple[Trial, ...] = ...
    best_trial_id: str | None = ...
    n_pending: int = ...
