from typing import Any

"""
TaskIR: canonical IR for a single tuning task (one fold + one candidate).
"""

class FoldBoundary:
    fold_index: int = ...
    train_start: datetime = ...
    train_end: datetime = ...
    test_start: datetime = ...
    test_end: datetime = ...
class TaskIR:
    task_id: str = ...
    job_id: str = ...
    candidate_id: str = ...
    fold: FoldBoundary = ...
    params: tuple[HParam, ...] = ...
    feature_hash: str = ...
    meta: IRMetadata = ...
    symbol: str = ...
    regime_label: str = ...
