from typing import Any

"""
ValidationIR: canonical IR for a cross-validation configuration.
"""

class EmbargoSpec:
    periods: int = ...
    unit: Literal['bars', 'days'] = ...
class ValidationIR:
    job_id: str = ...
    method: Literal['walkforward', 'purged_cv', 'cpcv', 'crisis_holdout'] = ...
    n_splits: int = ...
    embargo: EmbargoSpec = ...
    crisis_holdout: bool = ...
    cost_stress_bps: float = ...
    min_train_periods: int = ...
    meta: IRMetadata = ...
