from typing import Any

class CleanerPipeline:
    def __init__(self: Any, pipeline: BuiltCleaningPipeline | CleaningPipelineSpec | Mapping[str, Any]) -> None: ...
    def run(self: Any, df: Any, *, context: CleaningRuntimeContext | None = ..., return_result: bool = ...) -> Any: ...
    def last_result(self: Any) -> CleaningStepResult | None: ...
