from typing import Any

pd: Any
pl: Any
class CleaningPipelineRunner:
    def __init__(self: Any, pipeline: BuiltCleaningPipeline, *, state: CleaningPipelineState | None = ...) -> None: ...
    def default_context(self: Any, *, streaming: bool = ...) -> CleaningRuntimeContext: ...
    def run(self: Any, df: Any, *, context: CleaningRuntimeContext | None = ...) -> CleaningStepResult: ...
