from typing import Any

"""
LiveTriggerConfig: declarative spec for drift-triggered retraining.
"""

class LiveTriggerConfig(BaseModel):
    model_config: Any
    name: str = ...
    version: str = ...
    drift_threshold: float = ...
    retrain_cooldown_seconds: int = ...
    latency_budget_ms: int = ...
    min_samples_before_trigger: int = ...
    enable_online_features: bool = ...
