from typing import Any

"""
ObjectiveConfig: declarative spec for a tuning objective.
"""

class ObjectiveConfig(BaseModel):
    model_config: Any
    name: str = ...
    version: str = ...
    direction: Literal['maximize', 'minimize'] = ...
    metrics: list[str] = ...
    weights: dict[str, float] = ...
    penalty_refs: list[str] = ...
    min_sharpe: float | None = ...
    max_turnover: float | None = ...
