from typing import Any

"""
PromotionConfig: declarative spec for a rollout/promotion strategy.
"""

class PromotionConfig(BaseModel):
    model_config: Any
    name: str = ...
    version: str = ...
    mode: Literal['shadow', 'capped_blend', 'full'] = ...
    blend_cap: float | None = ...
    shadow_duration_days: int = ...
    rollback_policy: Literal['auto', 'manual', 'none'] = ...
    approval_required: bool = ...
