from typing import Any

"""
SearchSpaceConfig: declarative spec for a parameter search space.
"""

class DimensionConfig(BaseModel):
    model_config: Any
    name: str = ...
    kind: Literal['real', 'int', 'categorical', 'log_real'] = ...
    low: float | None = ...
    high: float | None = ...
    choices: list[Any] | None = ...
    prior: Literal['uniform', 'log-uniform'] = ...
class SearchSpaceConfig(BaseModel):
    model_config: Any
    name: str = ...
    version: str = ...
    model_type: str = ...
    dimensions: list[DimensionConfig] = ...
    fixed: dict[str, Any] = ...
