from typing import Any

"""
TuningJobConfig: top-level declarative spec for a tuning job.
"""

class TuningJobConfig(BaseModel):
    model_config: Any
    job_id: str = ...
    version: str = ...
    search_space_ref: str = ...
    objective_ref: str = ...
    validation_ref: str = ...
    promotion_ref: str | None = ...
    max_trials: int = ...
    timeout_seconds: int | None = ...
    determinism_tier: Literal['d0', 'd1', 'd2', 'd3'] = ...
    tags: dict[str, str] = ...
    crisis_holdout: bool = ...
