from typing import Any

"""
ValidationConfig: declarative spec for cross-validation strategy.
"""

class ValidationConfig(BaseModel):
    model_config: Any
    name: str = ...
    version: str = ...
    method: Literal['walkforward', 'purged_cv', 'cpcv', 'crisis_holdout'] = ...
    n_splits: int = ...
    embargo_periods: int = ...
    crisis_holdout: bool = ...
    cost_stress_bps: float = ...
    min_train_periods: int = ...
