from typing import Any

"""
Search space constraints: feasibility checks applied before trial submission.
"""

class ConstraintViolationError(ValueError):
    ...
def check_bounds(name: str, value: float, low: float, high: float) -> None: ...
def check_no_nan(params: dict[str, Any]) -> None: ...
def validate_params(params: dict[str, Any], bounds_map: dict[str, tuple[float, float]]) -> None: ...
