from typing import Any

"""
SearchSpace: runtime representation of a parameter search space.
"""

class SearchSpace:
    spec_hash: str = ...
    model_type: str = ...
    dimensions: tuple[DimensionSpec, ...] = ...
    fixed: dict[str, object] = ...
    def from_spec(cls: Any, spec: SearchSpaceSpec) -> SearchSpace: ...
    def dim_names(self: Any) -> tuple[str, ...]: ...
