from typing import Any

class BackendAwareOp(Op):
    def __init__(self: Any, **params: Any) -> Any: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class OpFactory:
    def create(op_symbol: str, **params: Any) -> Op: ...
def op(op_symbol: str, backend_hint: Optional[str] = ..., **params: Any) -> Op: ...
def sequence(*ops: Union[Op, str, Dict[str, Any]]) -> Graph: ...
def parallel(*subgraphs: Union[Graph, Op, str, Dict[str, Any]]) -> Graph: ...
def combine_ops(name: str, *sub_ops: Op, backend_selector: Callable[[List[Op]], str] = ...) -> type[Op]: ...
