from typing import Any

logger: Any
Engine: Any
class Executor(abc.ABC):
    def __init__(self: Any, backend: str, cache_size: int = ...) -> Any: ...
    def execute(self: Any, plan: List[Dict[str, Any]], data: Any, group_by: List[str]) -> Any: ...
    def evolve(self: Any, threshold: float = ...) -> Optional[str]: ...
class PolarsExecutor(Executor):
    def __init__(self: Any, engine_pref: Engine = ...) -> Any: ...
    def execute(self: Any, plan: List[Dict[str, Any]], data: Any, group_by: List[str]) -> Any: ...
class CuDFExecutor(Executor):
    def __init__(self: Any, pool_size: str = ...) -> Any: ...
    def execute(self: Any, plan: List[Dict[str, Any]], data: Any, group_by: List[str]) -> Any: ...
class ExecutorFactory:
    def register(cls: Any, backend: str, executor_cls: type[Executor]) -> None: ...
    def create(cls: Any, backend: str = ..., **kwargs: Any) -> Executor: ...
