from typing import Any

logger: Any
def register_expr(op: str, builder: Callable[..., 'Expr']) -> None: ...
class ExprMeta(ABCMeta):
    ...
class Expr(ABC):
    op: Optional[str] = ...
    args: Sequence['Expr'] = ...
    params: Dict[str, Any] = ...
    def __init__(self: Any, args: Sequence['Expr'] = ..., params: Optional[Dict[str, Any]] = ...) -> Any: ...
    def validate(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
    def optimize(self: Any) -> 'Expr': ...
class Column(Expr):
    op: Any
    def __init__(self: Any, name: str) -> Any: ...
    def validate(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class Literal(Expr):
    op: Any
    def __init__(self: Any, value: Any) -> Any: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class OpExpr(Expr):
    def __init__(self: Any, op: str, args: Sequence[Union[Expr, Any]], params: Optional[Dict[str, Any]] = ...) -> Any: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
    def optimize(self: Any) -> Expr: ...
def expr_factory(op: str, *args: Union[Expr, Any], **params: Any) -> Expr: ...
def optimize(expr: Expr) -> Expr: ...
def register_builtin_builders() -> None: ...
def create_sequence_lag(col: str, k: int, prefix: str = ...) -> Expr: ...
def create_rolling_mean(col: str, window: int) -> Expr: ...
def create_rolling_std(col: str, window: int) -> Expr: ...
def fuse_expressions(exprs: Sequence[Expr], fused_name: Optional[str] = ...) -> Expr: ...
def register_polars_lowering(op_name: str, fn: Callable[..., object]) -> None: ...
def get_polars_lowering(op_name: str) -> Optional[Callable[..., object]]: ...
