from typing import Any

logger: Any
ExprFactory: Any
TransformFactory: Any
class OpSpec:
    name: str = ...
    params: Dict[str, Any] = ...
def register(name: str, op_cls: Type[Op]) -> None: ...
def register_alias(alias: str, target: str) -> None: ...
def resolve_name(name: str) -> str: ...
def build_graph(ops: List[str], params: Dict[str, List[Dict[str, Any]]]) -> Graph: ...
def registry_snapshot() -> Tuple[Dict[str, str], Dict[str, str]]: ...
def register_builtin_ops() -> None: ...
