from typing import Any

class Node(ABC):
    def __init__(self: Any, op: Op) -> Any: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class SimpleNode(Node):
    def to_ir(self: Any) -> Dict[str, Any]: ...
class FusedNode(Node):
    def __init__(self: Any, sub_ops: List[Op], fused_kind: OpKind) -> Any: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
def register_node_factory(key: str, factory: Callable[[Op], Node]) -> None: ...
class Graph:
    def __init__(self: Any) -> Any: ...
    def add_op(self: Any, op: Op) -> Node: ...
    def merge(self: Any, other: 'Graph') -> None: ...
    def optimize(self: Any) -> None: ...
    def topological_sort(self: Any) -> List[Node]: ...
    def has_cycle(self: Any) -> bool: ...
    def shortest_path(self: Any, start: Node, end: Node) -> List[Node]: ...
    def connected_components(self: Any) -> List[Set[Node]]: ...
def serialize(graph: Graph) -> Dict[str, Any]: ...
def deserialize(data: Dict[str, Any]) -> Graph: ...
