from typing import Any

class OpKind(str, Enum):
    elementwise: Any
    rolling: Any
    sequence: Any
    scaling: Any
    external: Any
class Op(ABC):
    NAME: str | None = ...
    KIND: OpKind = ...
    def __init__(self: Any, **params: Any) -> Any: ...
    def name(self: Any) -> str: ...
    def validate_params(self: Any) -> None: ...
    def requires(self: Any) -> Set[str]: ...
    def provides(self: Any) -> Set[str]: ...
    def is_fittable(self: Any) -> bool: ...
    def state_dict(self: Any) -> Dict[str, Any]: ...
    def load_state_dict(self: Any, state: Dict[str, Any]) -> 'Op': ...
    def clone(self: Any) -> 'Op': ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class ElementwiseOp(Op):
    KIND: Any
    def to_ir(self: Any) -> Dict[str, Any]: ...
class RollingOp(Op):
    KIND: Any
    def to_ir(self: Any) -> Dict[str, Any]: ...
class SequenceOp(Op):
    KIND: Any
    def to_ir(self: Any) -> Dict[str, Any]: ...
class ScalingOp(Op):
    KIND: Any
    def is_fittable(self: Any) -> bool: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class ExternalOp(Op):
    KIND: Any
    def to_ir(self: Any) -> Dict[str, Any]: ...
def get_registry() -> set: ...
