from typing import Any

class RSI(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class SMA(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class EMA(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class MACDLineSignal(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class Bollinger(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class ATR(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class OBV(_ProvidesMixin, ElementwiseOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class VWAP(_ProvidesMixin, ElementwiseOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class RollingStd(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class Lags(SequenceOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
class ZScore(ScalingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def state_dict(self: Any) -> Dict[str, Any]: ...
class RobustScaler(ScalingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def state_dict(self: Any) -> Dict[str, Any]: ...
class SentimentLexicon(ElementwiseOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
class PairBeta(RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
class PairSpread(ElementwiseOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
class HalfLife(RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
class RollingZ(_ProvidesMixin, ScalingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class RollingVol(RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
class XSecRank(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class VolScale(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class ResidualOLS(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class ResidualKF(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
class IndustryScore(_ProvidesMixin, RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
    def to_ir(self: Any) -> Dict[str, Any]: ...
def lower_pairs_beta_polars(ir: Dict[str, Any], lf: pl.LazyFrame | pl.DataFrame, *, group_by: Any = ...) -> pl.LazyFrame | pl.DataFrame: ...
def lower_pairs_spread_polars(ir: Dict[str, Any], lf: pl.LazyFrame | pl.DataFrame, *, group_by: Any = ...) -> pl.LazyFrame | pl.DataFrame: ...
def lower_half_life_polars(ir: Dict[str, Any], lf: pl.LazyFrame | pl.DataFrame, *, group_by: Any = ...) -> pl.LazyFrame | pl.DataFrame: ...
def lower_rolling_vol_polars(*args: Any, **kwargs: Any) -> pl.LazyFrame | pl.DataFrame: ...
def lower_xsec_rank_polars(ir: Dict[str, Any], lf: pl.LazyFrame | pl.DataFrame, *, group_by: Any = ...) -> pl.LazyFrame | pl.DataFrame: ...
def lower_vol_scale_polars(ir: Dict[str, Any], lf: pl.LazyFrame | pl.DataFrame, *, group_by: Any = ...) -> pl.LazyFrame | pl.DataFrame: ...
def lower_residual_ols_polars(ir: Dict[str, Any], lf: pl.LazyFrame | pl.DataFrame, *, group_by: Any = ...) -> pl.LazyFrame | pl.DataFrame: ...
def lower_residual_kf_polars(ir: Dict[str, Any], lf: pl.LazyFrame | pl.DataFrame | None, *, group_by: Any = ...) -> pl.LazyFrame | pl.DataFrame: ...
def lower_industry_score_polars(ir: Dict[str, Any], lf: pl.LazyFrame | pl.DataFrame, *, group_by: Any = ...) -> pl.LazyFrame | pl.DataFrame: ...
lower_rsi_polars: Any
lower_sma_polars: Any
lower_ema_polars: Any
lower_macd_line_signal_polars: Any
lower_bollinger_polars: Any
lower_atr_polars: Any
lower_obv_polars: Any
lower_vwap_polars: Any
lower_zscore_roll_polars: Any
lower_rolling_std_polars: Any
class FeatureReturns(ElementwiseOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
class FeatureSMA(RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
class FeatureRSI(RollingOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
class DataLoadCSV(ElementwiseOp):
    NAME: Any
    def validate_params(self: Any) -> None: ...
