from typing import Any

class Planner(BasePlanner):
    def __init__(self: Any) -> Any: ...
    def plan(self: Any, graph: Graph, group_by: List[str]) -> List[Dict[str, Any]]: ...
    def update_from_history(self: Any, records: List[Dict[str, Any]]) -> None: ...
