from typing import Any

"""
Deterministic W1 anti-signal autopsy for governed Phase II artifacts.

The autopsy operates on serialized artifacts only. It never mutates original W1
bundles and does not retrain the challenger. Missing serialized incumbent task
scores are surfaced explicitly instead of being silently reconstructed.
"""

ALERT_DUPLICATE_TASK_ID_IN_EVAL: Final[str] = ...
ALERT_MISSING_QUERY_TARGET: Final[str] = ...
ALERT_MISSING_CHALLENGER_SCORE: Final[str] = ...
ALERT_MISSING_BASELINE_SCORE: Final[str] = ...
ALERT_TRAIN_EVAL_OVERLAP: Final[str] = ...
ALERT_SUPPORT_END_AFTER_QUERY_START: Final[str] = ...
ALERT_TASK_ID_JOIN_MISMATCH: Final[str] = ...
ALERT_FOLD_ID_JOIN_MISMATCH: Final[str] = ...
ALERT_MANY_TO_ONE_JOIN_EXPANSION: Final[str] = ...
PRIMARY_INVALID_ALIGNMENT: Final[str] = ...
PRIMARY_INCONCLUSIVE: Final[str] = ...
PRIMARY_SIGN_INVERSION: Final[str] = ...
PRIMARY_SUPPORT_QUERY_REVERSAL: Final[str] = ...
PRIMARY_COST_INVERSION: Final[str] = ...
PRIMARY_UNCLASSIFIED: Final[str] = ...
class AutopsyContext:
    repo_root: Path = ...
    phase_ii_root: Path = ...
    run_root: Path = ...
    comparison_run_root: Path | None = ...
    output_root: Path = ...
    agent_output_root: Path = ...
    task_manifest: dict[str, object] = ...
    meta_validity_report: dict[str, object] = ...
    execution_assumptions: dict[str, object] = ...
    baseline_report: dict[str, object] = ...
    challenger_surface: dict[str, object] = ...
    close_by_day: dict[str, float] = ...
class CanonicalTaskTable:
    rows: tuple[dict[str, object], ...] = ...
    schema: dict[str, object] = ...
    missing_fields: tuple[str, ...] = ...
def choose_latest_governed_w1_run(phase_ii_root: Path | None = ...) -> Path: ...
def load_autopsy_context(run_root: Path | None = ...) -> AutopsyContext: ...
def build_canonical_task_table(ctx: AutopsyContext) -> CanonicalTaskTable: ...
def run_alignment_audit(ctx: AutopsyContext, table: CanonicalTaskTable) -> dict[str, object]: ...
def assemble_final_report(agent_payloads: Mapping[str, Mapping[str, object]]) -> tuple[dict[str, object], str, dict[str, object]]: ...
def run_lane(lane: str, run_root: Path | None = ...) -> dict[str, object]: ...
def main(argv: Sequence[str] | None = ...) -> int: ...
