from typing import Any

"""
Adams & MacKay BOCPD (log-space) + orchestrator regime service (AQ-04).
"""

class NIGPrior:
    mu0: float = ...
    kappa0: float = ...
    alpha0: float = ...
    beta0: float = ...
class SufficientStats:
    mu: NDArray[np.float64] = ...
    kappa: NDArray[np.float64] = ...
    alpha: NDArray[np.float64] = ...
    beta: NDArray[np.float64] = ...
def nig_update_obs(mu: float, kappa: float, alpha: float, beta: float, x: float) -> tuple[float, float, float, float]: ...
def merge_nig_tail(mus: NDArray[np.float64], kappas: NDArray[np.float64], alphas: NDArray[np.float64], betas: NDArray[np.float64], prior: NIGPrior) -> tuple[float, float, float, float]: ...
def predictive_logpdf(x: float, mu: float, kappa: float, alpha: float, beta: float, observation_model: Literal['student_t', 'gaussian']) -> float: ...
def bocpd_update(x: float, log_posterior: NDArray[np.float64], sufficient_stats: SufficientStats, config: BOCPDConfig, prior: NIGPrior) -> tuple[NDArray[np.float64], SufficientStats, float]: ...
class ServiceSnapshot:
    log_posterior: NDArray[np.float64] = ...
    sufficient_stats: SufficientStats = ...
    observation_count: int = ...
    config_hash: str = ...
    prior: NIGPrior = ...
def state_snapshot_id(snapshot: ServiceSnapshot) -> str: ...
class RegimeLabelRecord:
    entity_id: str = ...
    decision_ts: datetime = ...
    regime_id: str = ...
    regime_label: str = ...
    effective_at: datetime = ...
    state_snapshot_id: str = ...
    input_snapshot_id: str = ...
    config_version: str = ...
    change_probability: float = ...
    boundary_flag: Literal['cold_start', 'change_point', 'transition', 'stable'] = ...
    regime_class: RegimeClassLabel = ...
    diag_regime_class_bocpd_gated: RegimeClassLabel = ...
    diag_regime_class_extended: RegimeClassLabel = ...
    run_length_mode: int = ...
    run_length_expectation: float = ...
    transition_probability: float = ...
    posterior_entropy: float = ...
    trend_score_raw: float = ...
    vol_score_raw: float = ...
    cold_start: bool = ...
class BOCPDRegimeService:
    def __init__(self: Any, config: BOCPDConfig) -> None: ...
    def initialize(self: Any, historical_log_rv: NDArray[np.float64]) -> None: ...
    def update(self: Any, decision_ts: datetime, log_rv: float, *, log_return: float, entity_id: str = ..., pit_boundary_idx: int, log_rv_history: NDArray[np.float64], returns_history: NDArray[np.float64]) -> RegimeLabelRecord: ...
    def snapshot(self: Any) -> ServiceSnapshot: ...
    def from_snapshot(cls: Any, snapshot: ServiceSnapshot, config: BOCPDConfig) -> BOCPDRegimeService: ...
