from typing import Any

"""
MLC-2 governed five-bucket curriculum sampler.

This module owns sampling policy over already-built :class:`MetaTask` objects:
five-bucket bootstrap batches, PER-like external-priority sampling, per-batch
crisis floor enforcement, sufficiency checks, and the single authoritative
training holdout exclusion surface for MLC-2.
"""

LOG: Any
CurriculumPhase: Any
PriorityResolver: Any
class CurriculumSufficiencyError(DataPreconditionError):
    ...
def governed_v2_task_pool_bucket_minimums() -> dict[str, int]: ...
class HoldoutExclusionSurface:
    task_ids: frozenset[str] = ...
    def allows(self: Any, task: MetaTask) -> bool: ...
class CurriculumSamplerConfig:
    batch_size: int = ...
    crisis_floor_fraction: float = ...
    bucket_minimums: Mapping[str, int] = ...
    priority_alpha: float = ...
    importance_beta: float = ...
    seed: int = ...
class CurriculumBatch:
    tasks: tuple[MetaTask, ...] = ...
    phase: CurriculumPhase = ...
    bucket_counts: Mapping[str, int] = ...
    priority_alpha: float = ...
    importance_beta: float = ...
    importance_weights: tuple[float, ...] = ...
class CurriculumSampler:
    def __init__(self: Any, tasks: Iterable[MetaTask], *, config: CurriculumSamplerConfig, holdouts: HoldoutExclusionSurface | None = ...) -> None: ...
    def trainable_tasks(self: Any) -> tuple[MetaTask, ...]: ...
    def bucket_governance_minimums(self: Any) -> Mapping[str, int]: ...
    def sample_bootstrap(self: Any) -> CurriculumBatch: ...
    def sample_per_like(self: Any, *, priority_resolver: PriorityResolver) -> CurriculumBatch: ...
