from typing import Any

"""
MLC-6 EWC forgetting harness: functional core + governed JSON emission.
"""

LOG: Any
def compute_diagonal_fisher(theta: NDArray[np.float64], tasks: Sequence[MetaTask], inner_cfg: Any, rng: np.random.Generator) -> NDArray[np.float64]: ...
def apply_ewc_correction(theta: NDArray[np.float64], theta_anchor: NDArray[np.float64], fisher: NDArray[np.float64], lambda_ewc: float) -> NDArray[np.float64]: ...
def pretrain_theta_meta(config: EWCSweepConfig, historical_tasks: Sequence[MetaTask], rng: np.random.Generator) -> NDArray[np.float64]: ...
def run_from_scratch_arm(config: EWCSweepConfig, all_available_tasks_by_step: Sequence[Sequence[MetaTask]], heldout_tasks: Sequence[MetaTask], fresh_tasks: Sequence[MetaTask], rng: np.random.Generator) -> EWCArmResult: ...
def run_ewc_arm(lambda_ewc: float, theta_initial: NDArray[np.float64], fisher: NDArray[np.float64], theta_anchor: NDArray[np.float64], config: EWCSweepConfig, update_task_batches: Sequence[Sequence[MetaTask]], heldout_tasks: Sequence[MetaTask], fresh_tasks: Sequence[MetaTask], rng: np.random.Generator) -> EWCArmResult: ...
def run_ewc_sweep(config: EWCSweepConfig) -> EWCForgettingReport: ...
def emit_ewc_forgetting_report_json(path: Path, report: EWCForgettingReport) -> None: ...
def load_ewc_forgetting_report_json(path: Path) -> dict[str, Any]: ...
def recompute_content_hash_from_document(doc: Mapping[str, Any]) -> str: ...
