from typing import Any

"""
MLC-6 immutable EWC forgetting config and report contracts (II-C evidence).
"""

THR_MLC6_FD01: Final[str] = ...
THR_MLC6_NG01: Final[str] = ...
THR_MLC6_LM01: Final[str] = ...
MLC6_CONTENT_HASH_CANONICALIZATION: Final[str] = ...
ArmLabel: Any
class EWCUpdateRecord:
    arm_label: str = ...
    update_step: int = ...
    heldout_ic: float | None = ...
    heldout_ic_delta: float | None = ...
    fresh_task_gain: float | None = ...
    theta_l2_drift_from_anchor: float | None = ...
    def to_json_obj(self: Any) -> dict[str, Any]: ...
class EWCArmResult:
    arm_label: str = ...
    arm_kind: Literal['from_scratch', 'warm_start'] = ...
    lambda_ewc: float | None = ...
    forgetting_delta: float | None = ...
    forgetting_pct: float | None = ...
    mean_fresh_task_gain: float | None = ...
    final_theta_l2_drift: float | None = ...
    arm_status: Literal['COMPLETED', 'FAILED'] = ...
    failure_code: str | None = ...
    update_records: tuple[EWCUpdateRecord, ...] = ...
    final_theta_meta: tuple[float, ...] = ...
    def to_json_obj(self: Any) -> dict[str, Any]: ...
class EWCForgettingReport:
    schema_version: str = ...
    run_id: str = ...
    seed_lineage: dict[str, Any] = ...
    determinism_tier: str = ...
    n_pretrain_steps: int = ...
    n_update_steps: int = ...
    lambda_ewc_values: list[float] = ...
    from_scratch_result: EWCArmResult = ...
    warm_start_arm_results: list[EWCArmResult] = ...
    anchor_regime_counts: dict[str, int] = ...
    config_hash: str = ...
    mlc_scope: str = ...
    gate_ii_status: str = ...
    promotion_evidence: bool = ...
    content_hash: dict[str, str] = ...
    reproducibility: dict[str, Any] = ...
    def to_json_document(self: Any) -> dict[str, Any]: ...
class EWCSweepConfig:
    lambda_ewc_values: tuple[float, ...] = ...
    n_pretrain_steps: int = ...
    n_update_steps: int = ...
    anchor_set_size_per_bucket: int = ...
    trainer_seed: int = ...
    historical_partition_seed: int = ...
    outer_step_size: float = ...
    base_trainer_config: ReptileTrainerConfig = ...
    def config_hash(self: Any) -> str: ...
    def default_mlc6_bounded(*, trainer_seed: int = ..., historical_partition_seed: int = ...) -> EWCSweepConfig: ...
