from typing import Any

"""
Scaffold and governed execution-assumptions emitters.
"""

SCHEMA_VERSION: Final[str] = ...
GOVERNED_SCHEMA_VERSION: Final[str] = ...
CONTENT_HASH_ALGORITHM: Final[str] = ...
CONTENT_HASH_CANONICALIZATION: Final[str] = ...
GOVERNED_CONTENT_HASH_ALGORITHM: Final[str] = ...
GOVERNED_CONTENT_HASH_CANONICALIZATION: Final[str] = ...
class ExecutionAssumptionsReport:
    document: dict[str, Any] = ...
    content_hash: str = ...
    schema_version: str = ...
    def to_json_document(self: Any) -> dict[str, Any]: ...
def build_execution_assumptions_document(*, run_identity: Phase2ScaffoldRunIdentity) -> dict[str, Any]: ...
def emit_execution_assumptions(output_path: Path, *, seed: int) -> dict[str, Any]: ...
def recompute_execution_assumptions_content_hash_from_document(document: Mapping[str, Any]) -> str: ...
def emit_governed_execution_assumptions(config: ExecutionAssumptionsConfig) -> ExecutionAssumptionsReport: ...
def build_governed_execution_assumptions_document(config: ExecutionAssumptionsConfig) -> dict[str, Any]: ...
def validate_governed_execution_assumptions_document(document: Mapping[str, Any]) -> None: ...
