from typing import Any

"""
Config surface for governed execution-assumptions emission.
"""

DEFAULT_OUTPUT_DIR: Any
GOVERNED_SCHEMA_VERSION: Any
class ExecutionParityDeclaration:
    cost_assumptions_match_baseline: bool = ...
    split_assumptions_match_baseline: bool = ...
    data_assumptions_match_baseline: bool = ...
    parity_note: str = ...
    def to_json_obj(self: Any) -> dict[str, object]: ...
class ExecutionAssumptionsConfig:
    run_id: str = ...
    cost_bps: float = ...
    slippage_model: str = ...
    slippage_bps_estimate: float = ...
    borrow_rate_annual_bps: float | None = ...
    latency_model: str = ...
    fill_assumption: str = ...
    parity: ExecutionParityDeclaration = ...
    schema_version: str = ...
    output_dir: str = ...
    def with_updates(self: Any, **changes: Unpack[_ExecutionAssumptionsConfigUpdates]) -> ExecutionAssumptionsConfig: ...
