from typing import Any

"""
MLN-06 Phase II artifact contract: single fail-closed emission path for governed evidence.

MLN-03 adds a required ``confidence_calibration`` block on ``meta_validity_report.json`` (calibration /
ECE / routing-pilot boundary). See :mod:`pysrc.meta_learning.confidence_contract`.
"""

PHASE2_ARTIFACT_CONTRACT_VERSION: Final[str] = ...
PHASE2_GOVERNED_PHASE: Final[str] = ...
PROMOTABLE_CLAIM_EMITTED: Final[bool] = ...
GOVERNED_ARTIFACT_CONTRACT: Final[bool] = ...
CONTENT_HASH_ALGORITHM: Final[str] = ...
CONTENT_HASH_CANONICALIZATION: Final[str] = ...
GOVERNED_SIGNAL_SURFACE_KIND: Final[str] = ...
ENTRY_CONDITION_KEYS: Final[tuple[str, ...]] = ...
SCHEMA_FILES: Final[dict[str, str]] = ...
VALID_OVERALL_RESULTS: Final[frozenset[str]] = ...
class PhaseIIArtifactError(Exception):
    def __init__(self: Any, message: str, *, details: dict[str, Any] | None = ...) -> None: ...
def pit_compliance_from_dataset_manifest(data: Mapping[str, Any]) -> bool: ...
def canonical_json_bytes(payload: Mapping[str, Any]) -> bytes: ...
def canonical_content_hash(payload: Mapping[str, Any]) -> str: ...
def derive_phase2_task_pool_identity_hash(tasks: Sequence[TaskManifestTaskInput]) -> str: ...
def derive_phase2_task_pool_identity_hash_from_manifest_rows(tasks: Sequence[Mapping[str, Any]]) -> str: ...
def canonical_artifact_content_hash(payload: Mapping[str, Any]) -> str: ...
def validate_artifact_content_hash(payload: Mapping[str, Any], *, label: str) -> None: ...
W1_CHALLENGER_SURFACE_SUMMARY_REQUIRED_KEYS_V1: Final[tuple[str, ...]] = ...
def validate_phase2_artifact_triple(*, task_doc: Mapping[str, Any], meta_doc: Mapping[str, Any], exec_doc: Mapping[str, Any]) -> None: ...
class PhaseIIRunContext:
    output_dir: Path = ...
    seed: int = ...
    timestamp_utc: str = ...
    tasks: Sequence[TaskManifestTaskInput] = ...
    dataset_manifest: Mapping[str, Any] = ...
    inner_loop_gain_by_regime: Mapping[str, Any] = ...
    harvey_t_statistic: float | int = ...
    encoder_coherence_score: float | int = ...
    crisis_episode_ic: float | int = ...
    forgetting_metric: float | int = ...
    plasticity_metric: float | int = ...
    baseline_comparison: Mapping[str, Any] = ...
    cost_model: Mapping[str, Any] = ...
    slippage_model: Mapping[str, Any] = ...
    borrow_funding: Mapping[str, Any] = ...
    latency_fill: Mapping[str, Any] = ...
    shared_comparison_context: Mapping[str, Any] = ...
    task_manifest_result: TaskManifestReport | None = ...
    execution_assumptions_result: ExecutionAssumptionsReport | None = ...
    w1_baseline_result: W1BaselineResult | None = ...
    entry_conditions: Mapping[str, Any] = ...
    threshold_references: Sequence[Mapping[str, Any]] = ...
    run_seed_root: str | None = ...
    seed_derivations: Sequence[tuple[str, str]] = ...
    confidence_calibration: Mapping[str, Any] = ...
    overall_result: str = ...
    inference_boundary_audit: Mapping[str, Any] | None = ...
def emit_phase2_artifacts(run_context: PhaseIIRunContext) -> None: ...
