from typing import Any

"""
Compositional regime_id strings + 5-class projection (Architecture Vision §4.2).
"""

class RegimeLabeler:
    def __init__(self: Any, config: BOCPDConfig) -> None: ...
    def compute_trend_regime(self: Any, returns: NDArray[np.float64], pit_boundary_idx: int) -> Literal['hi', 'lo', 'flat']: ...
    def compute_vol_regime(self: Any, log_rv_history: NDArray[np.float64], pit_boundary_idx: int) -> Literal['hi', 'med', 'lo']: ...
    def compute_regime_id(self: Any, trend: Literal['hi', 'lo', 'flat'], vol: Literal['hi', 'med', 'lo'], bocpd_state: Literal['stable', 'transition', 'cp']) -> str: ...
    def compute_severity_flag_vol_score_raw(self: Any, vol_score_history: NDArray[np.float64], pit_boundary_idx: int) -> bool: ...
    def project_regime_class(self: Any, trend: Literal['hi', 'lo', 'flat'], vol: Literal['hi', 'med', 'lo'], bocpd_state: Literal['stable', 'transition', 'cp'], *, severity_flag: bool) -> Literal['bull', 'bear', 'sideways', 'high_vol', 'crisis']: ...
    def project_regime_class_bocpd_gated_reference(trend: Literal['hi', 'lo', 'flat'], vol: Literal['hi', 'med', 'lo'], bocpd_state: Literal['stable', 'transition', 'cp']) -> Literal['bull', 'bear', 'sideways', 'high_vol', 'crisis']: ...
    def project_regime_class_extended(self: Any, trend: Literal['hi', 'lo', 'flat'], vol: Literal['hi', 'med', 'lo'], bocpd_state: Literal['stable', 'transition', 'cp']) -> Literal['bull', 'bear', 'sideways', 'high_vol', 'crisis']: ...
def validate_regime_id(regime_id: str) -> bool: ...
def annualized_log_rv_from_returns(returns: NDArray[np.float64], pit_idx: int, vol_window: int) -> float: ...
