from typing import Any

"""
Typed BOCPD + regime labeling configuration (RG-09 §5.2).
"""

class BOCPDConfig:
    hazard_rate: float = ...
    observation_model: Literal['student_t', 'gaussian'] = ...
    prior_mu0: float | None = ...
    prior_kappa0: float = ...
    prior_alpha0: float = ...
    prior_beta0: float | None = ...
    max_run_length: int = ...
    vol_window: int = ...
    trend_window: int = ...
    trend_flat_epsilon: float = ...
    vol_bucket_method: Literal['tercile', 'quintile'] = ...
    cp_threshold: float = ...
    transition_threshold: float = ...
    transition_max_rl: int = ...
    cold_start_burn_in: int = ...
    crisis_vol_score_percentile: float = ...
    config_version: str = ...
    def to_dict(self: Any) -> dict[str, Any]: ...
    def content_hash(self: Any) -> str: ...
