from typing import Any

"""
MLC-3 governed Reptile outer-loop trainer.

Inner-loop training objective (committed proxy-loss family)
------------------------------------------------------------
**Pairwise logistic ranking surrogate** over support-set scores: for each pair
``(i, j)`` with ``y_i > y_j``, contribute ``softplus(-(pred_i - pred_j))`` where
``pred_i = w @ x_i``. This is the scaffold's differentiable ranking surrogate;
exact IC alignment and Pearson gates are **not** enforced at MLC-3 runtime (Tier-1
promotion lives in later gate logic).

``MetaTask.regime_embedding`` is concatenated as a **fixed conditioning vector**
per row (AQ-09: conditioning / control input only; no representation claim).

EWC is an **explicit no-op seam** (``lambda_EWC`` is not applied here).
"""

LOG: Any
def reptile_outer_update(theta_meta: NDArray[np.float32], adapted_stack: NDArray[np.float32], outer_lr: float) -> NDArray[np.float32]: ...
def collect_inner_adapted_thetas_d0(*, theta_meta: NDArray[np.float32], tasks: Sequence[MetaTask], config: ReptileTrainerConfig, seed: int) -> tuple[NDArray[np.float32], ...]: ...
class TrainerRunResult:
    theta_meta: NDArray[np.float32] = ...
    theta_day_prime: NDArray[np.float32] | None = ...
    meta_validity_report: dict[str, Any] = ...
    theta_day_prime_promoted: bool = ...
    inner_loop_gain: float | None = ...
    observability: tuple[dict[str, Any], ...] = ...
class GovernedCurriculumSuccess:
    tasks: tuple[MetaTask, ...] = ...
    counts: dict[str, Any] = ...
class GovernedCurriculumFailure:
    reasons: tuple[str, ...] = ...
    counts: dict[str, Any] | None = ...
    log_context: dict[str, Any] | None = ...
def prepare_governed_curriculum_batch(sampler: Any, config: ReptileTrainerConfig) -> GovernedCurriculumSuccess | GovernedCurriculumFailure: ...
class ReptileTrainer:
    def __init__(self: Any, config: ReptileTrainerConfig, sampler: CurriculumSampler, *, seed: int = ..., context_encoder: Optional[Any] = ...) -> None: ...
    def theta_day_prime_promoted(self: Any) -> NDArray[np.float32] | None: ...
    def apply_ewc_seam(self: Any, theta: NDArray[np.float32], *, lambda_ewc: float) -> NDArray[np.float32]: ...
    def run_batch(self: Any, *, theta_meta: NDArray[np.float32], theta_day_prime_prior: NDArray[np.float32] | None = ..., seed: int | None = ...) -> TrainerRunResult: ...
class TaskPoolSufficiencyError(DataPreconditionError):
    ...
