from typing import Any

"""
MLC-4 K-sweep compute kernel: query-gain evidence, deterministic arms, typed failures.
"""

LOG: Any
def saturation_from_adjacent_means(prev_mean: float | None, mean_delta: float, *, epsilon: float) -> bool: ...
def run_k_sweep(config: KSweepConfig) -> KSweepReport: ...
def emit_reptile_k_sweep_report_json(path: Path, report: KSweepReport) -> None: ...
def load_k_sweep_report_json(path: Path) -> dict[str, Any]: ...
def recompute_content_hash_from_document(doc: Mapping[str, Any]) -> str: ...
