from typing import Any

"""
MLC-3 frozen runtime configuration for the governed Reptile trainer.
"""

class ReptileTrainerConfig:
    K: int = ...
    outer_lr: float = ...
    lambda_TC: float = ...
    lambda_EWC: float = ...
    crisis_floor_pct: float = ...
    task_failure_abort_threshold: int = ...
    algorithm: Literal['reptile', 'anil', 'fomaml'] = ...
    determinism_tier: str = ...
    task_pool_bucket_minimums: Mapping[str, int] | None = ...
