from typing import Any

"""
MLC-5 proxy–IC alignment harness: functional core, partition, and governed JSON emission.
"""

LOG: Any
def partition_training_and_heldout(pool: Sequence[MetaTask], *, heldout_partition_seed: int) -> tuple[tuple[MetaTask, ...], tuple[MetaTask, ...]]: ...
def compute_proxy_loss(proxy_kind: str, theta_adapted: NDArray[np.float32], task: MetaTask, *, soft_rank_temperature: float | None = ...) -> float: ...
def run_alignment_arm(config: ProxyAlignmentConfig, arm: ArmLabel, theta_initial: NDArray[np.float32], training_tasks: Sequence[MetaTask], heldout_tasks: Sequence[MetaTask], rng: np.random.Generator) -> ProxyAlignmentAggregateResult: ...
def run_proxy_alignment(config: ProxyAlignmentConfig) -> ProxyAlignmentReport: ...
def emit_proxy_alignment_report_json(path: Path, report: ProxyAlignmentReport) -> None: ...
def load_proxy_alignment_report_json(path: Path) -> dict[str, Any]: ...
def recompute_content_hash_from_document(doc: Mapping[str, Any]) -> str: ...
