from typing import Any

"""
MLC-4 immutable K-sweep configuration and typed report contracts (II-C evidence).
"""

THR_MLC4_QG01: Final[str] = ...
THR_MLC4_KS01: Final[str] = ...
THR_MLC4_WC01: Final[str] = ...
GOVERNED_K_VALUES: Final[tuple[int, ...]] = ...
ArmStatus: Any
class KSweepArmResult:
    k: int = ...
    aggregate_mean_delta_ic: float | None = ...
    aggregate_harvey_t: float | None = ...
    wall_clock_s: float = ...
    saturation_detected: bool = ...
    arm_status: ArmStatus = ...
    failure_code: str | None = ...
    def to_json_obj(self: Any) -> dict[str, Any]: ...
class KSweepRegimeResult:
    k: int = ...
    regime_class: str = ...
    mean_delta_ic: float | None = ...
    harvey_t: float | None = ...
    task_count: int = ...
    def to_json_obj(self: Any) -> dict[str, Any]: ...
class KSweepTaskKRecord:
    task_id: str = ...
    regime_class: str = ...
    batch_position: int = ...
    k: int = ...
    ic_meta: float = ...
    ic_adapted: float = ...
    delta_ic: float = ...
    def to_json_obj(self: Any) -> dict[str, Any]: ...
class KSweepReport:
    schema_version: str = ...
    run_id: str = ...
    seed_lineage: dict[str, Any] = ...
    determinism_tier: str = ...
    k_values: tuple[int, ...] = ...
    arm_results: tuple[KSweepArmResult, ...] = ...
    regime_results: tuple[KSweepRegimeResult, ...] = ...
    per_task_records: tuple[KSweepTaskKRecord, ...] = ...
    k_sweep_config_hash: str = ...
    mlc_scope: str = ...
    gate_ii_status: str = ...
    promotion_evidence: bool = ...
    content_hash: dict[str, str] = ...
    reproducibility: dict[str, Any] = ...
    def to_json_document(self: Any) -> dict[str, Any]: ...
class KSweepConfig:
    k_values: tuple[int, ...] = ...
    trainer_seed: int = ...
    curriculum_sampler_seed: int = ...
    base_trainer_config: ReptileTrainerConfig = ...
    saturation_epsilon: float = ...
    def k_sweep_config_hash(self: Any) -> str: ...
    def default_mlc4_bounded(*, trainer_seed: int = ..., curriculum_sampler_seed: int = ..., saturation_epsilon: float = ...) -> KSweepConfig: ...
