from typing import Any

"""
MLC-5 immutable proxy–IC alignment configuration and typed report contracts (II-C evidence).
"""

THR_MLC5_PA01: Final[str] = ...
THR_MLC5_PA02: Final[str] = ...
THR_MLC5_EP01: Final[str] = ...
MLC5_CONTENT_HASH_CANONICALIZATION: Final[str] = ...
ChallengerProxy: Any
ControlProxy: Any
ArmLabel: Any
InnerProxyKind: Any
class ProxyEpochRecord:
    epoch: int = ...
    proxy_type: ArmLabel = ...
    proxy_loss: float | None = ...
    held_out_ic: float | None = ...
    proxy_loss_delta: float | None = ...
    held_out_ic_delta: float | None = ...
    def to_json_obj(self: Any) -> dict[str, Any]: ...
class ProxyAlignmentAggregateResult:
    proxy_type: ArmLabel = ...
    pearson_r: float | None = ...
    pearson_p_value: float | None = ...
    n_epochs_measured: int = ...
    divergence_detected: bool = ...
    divergence_window_count: int = ...
    epoch_records: tuple[ProxyEpochRecord, ...] = ...
    final_theta_meta: tuple[float, ...] = ...
    def to_json_obj(self: Any) -> dict[str, Any]: ...
class ProxyAlignmentReport:
    schema_version: str = ...
    run_id: str = ...
    seed_lineage: dict[str, Any] = ...
    determinism_tier: str = ...
    n_outer_epochs: int = ...
    challenger_result: ProxyAlignmentAggregateResult = ...
    control_result: ProxyAlignmentAggregateResult = ...
    config_hash: str = ...
    mlc_scope: str = ...
    gate_ii_status: str = ...
    promotion_evidence: bool = ...
    content_hash: dict[str, str] = ...
    reproducibility: dict[str, Any] = ...
    def to_json_document(self: Any) -> dict[str, Any]: ...
class ProxyAlignmentConfig:
    n_outer_epochs: int = ...
    challenger_proxy: ChallengerProxy = ...
    control_proxy: ControlProxy = ...
    trainer_seed: int = ...
    curriculum_sampler_seed: int = ...
    heldout_partition_seed: int = ...
    divergence_window: int = ...
    outer_step_size: float = ...
    soft_rank_temperature: float = ...
    base_trainer_config: ReptileTrainerConfig = ...
    def config_hash(self: Any) -> str: ...
    def default_mlc5_bounded(*, trainer_seed: int = ..., curriculum_sampler_seed: int = ..., heldout_partition_seed: int = ..., n_outer_epochs: int = ..., divergence_window: int = ..., outer_step_size: float = ..., soft_rank_temperature: float = ..., challenger_proxy: ChallengerProxy = ...) -> ProxyAlignmentConfig: ...
