from typing import Any

"""
OI-59 diagnostic audit for corrected-surface segment feasibility.
"""

LOG: Any
OI59_FEASIBILITY_AUDIT_SCHEMA: Final[str] = ...
OI59_FEASIBILITY_AUDIT_FILENAME: Final[str] = ...
OI59_FEASIBILITY_DIAGNOSTIC_FILENAME: Final[str] = ...
def build_oi59_feasibility_audit(*, fixture_path: Path, fixture_summary_path: Path, fixture_metadata_path: Path, config_path: Path, output_json_path: Path, output_markdown_path: Path) -> dict[str, Any]: ...
