from typing import Any

"""
Typed corrected-geometry contract for governed RG-09 multi-instrument fixtures.
"""

CORRECTED_MULTI_INSTRUMENT_SCOPE: Any
INDEPENDENT_INSTRUMENTS_POLICY: Any
CALENDAR_TIME_METHOD: Any
TRADING_DAY_ORDINAL_COLUMN: Any
class RG09FixtureGeometryContractError(ValueError):
    def __init__(self: Any, message: str, *, breaches: Collection[str]) -> None: ...
class RG09FoldTimeRange:
    fold_id: int = ...
    date_start: str = ...
    date_end: str = ...
    def to_pair(self: Any) -> list[str]: ...
class RG09CorrectedFoldConstruction:
    method: str = ...
    uniform_calendar_day_index: bool = ...
    temporal_folds: int = ...
    time_ranges: tuple[RG09FoldTimeRange, ...] = ...
    def to_dict(self: Any) -> dict[str, Any]: ...
class RG09CorrectedFixtureGeometryContract:
    fixture_scope: str = ...
    entity_ids: tuple[str, ...] = ...
    uniform_calendar_day_index: bool = ...
    calendar_overlap_policy: str = ...
    fold_construction: RG09CorrectedFoldConstruction = ...
    def to_summary_fields(self: Any) -> dict[str, Any]: ...
class RG09MultiManifestGeometryPolicy:
    uniform_calendar_day_index: bool = ...
    calendar_overlap_policy: str = ...
    temporal_folds: int = ...
def is_governed_multi_instrument_summary(summary: Mapping[str, Any]) -> bool: ...
def requires_corrected_geometry_contract(summary: Mapping[str, Any]) -> bool: ...
def parse_corrected_fixture_geometry_contract(summary: Mapping[str, Any], *, available_columns: Collection[str] | None = ...) -> RG09CorrectedFixtureGeometryContract: ...
def parse_multi_manifest_geometry_policy(manifest: Mapping[str, Any]) -> RG09MultiManifestGeometryPolicy: ...
def validate_corrected_contract_matches_manifest(contract: RG09CorrectedFixtureGeometryContract, manifest_policy: RG09MultiManifestGeometryPolicy) -> None: ...
