from typing import Any

"""
Deterministic null generators for the RG-09 II-0A harness.
"""

AUTHORIZED_NULL_FAMILIES: Final[tuple[str, str, str]] = ...
def make_null_rng(namespace: str, family: str, fixture_sha256: str, *, draw_index: int = ...) -> np.random.Generator: ...
def shuffled_regime_null(episodes: pd.DataFrame, *, namespace: str, fixture_sha256: str, draw_index: int = ...) -> pd.DataFrame: ...
def shuffled_label_null(episodes: pd.DataFrame, *, namespace: str, fixture_sha256: str, draw_index: int = ...) -> pd.DataFrame: ...
def matched_exchangeable_window_null(episodes: pd.DataFrame, *, namespace: str, fixture_sha256: str, draw_index: int = ...) -> pd.DataFrame: ...
