from typing import Any

"""
Advisory-only prospective power analysis for RG-09.
"""

PRODUCER_VERSION: Final[str] = ...
SCHEMA_VERSION: Final[str] = ...
MANIFEST_SCHEMA_VERSION: Final[str] = ...
ARTIFACT_CLASS: Final[str] = ...
EPISODE_SCENARIOS: Final[tuple[int, ...]] = ...
INSTRUMENT_SCENARIOS: Final[tuple[int, ...]] = ...
TARGET_POWER_LEVELS: Final[tuple[tuple[str, float], ...]] = ...
Z_95_ONE_SIDED: Final[float] = ...
MAX_EPISODE_TARGET_SEARCH: Final[int] = ...
MAX_REASONABLE_INSTRUMENTS: Final[int] = ...
DEFAULT_GATE_SPEC: Final[str] = ...
DEFAULT_BASELINE_CONFIG: Final[str] = ...
DEFAULT_FIXTURE_CONFIG: Final[str] = ...
DEFAULT_POWER_A_COMPARISON_DOC: Final[str] = ...
DEFAULT_MULTI_FIXTURE_MANIFEST: Final[str] = ...
REQUIRED_RUN_FILENAMES: Final[tuple[str, ...]] = ...
ALLOWED_RECOMMENDATIONS: Final[frozenset[str]] = ...
FAMILY_ORDER: Final[tuple[str, ...]] = ...
class RG09PowerAnalysisResult:
    output_dir: Path = ...
    advisory_recommendation: str = ...
def run_rg09_power_analysis(*, baseline_run_dir: Path, comparison_run_dirs: Sequence[Path], output_dir: Path, gate_spec_path: Path | None = ..., baseline_config_path: Path | None = ..., comparison_config_paths: Sequence[Path] | None = ..., fixture_config_path: Path | None = ..., power_comparison_doc_path: Path | None = ..., multi_fixture_manifest_path: Path | None = ...) -> RG09PowerAnalysisResult: ...
