from typing import Any

"""
OI-59 Experiment 2: merge-only segmentation redesign on the corrected surface.
"""

LOG: Any
OI59_SEGMENTATION_REDESIGN_SCHEMA: Final[str] = ...
OI59_SEGMENTATION_REDESIGN_REPORT_FILENAME: Final[str] = ...
OI59_SEGMENTATION_REDESIGN_DIAGNOSTIC_FILENAME: Final[str] = ...
THR_RG09_V20_ID: Final[str] = ...
OI59_HOLD_PENDING_THRESHOLD_REVIEW: Final[str] = ...
def build_oi59_segmentation_redesign_report(*, fixture_path: Path, fixture_summary_path: Path, fixture_metadata_path: Path, config_path: Path, baseline_reference_path: Path, output_dir: Path) -> dict[str, Any]: ...
