from typing import Any

"""
Transition-anchored RG-09 episode construction (BOCPD boundary clusters).
"""

class TransitionAnchor:
    entity_id: str = ...
    transition_start_ts: pd.Timestamp = ...
    transition_end_ts: pd.Timestamp = ...
    src_regime_class: str = ...
    dest_regime_class: str = ...
    stable_bars_before: int = ...
    stable_bars_after: int = ...
def derive_transition_anchored_episodes(frame: pd.DataFrame, config: RG09PilotConfig, *, fold_construction: dict[str, Any] | None = ..., require_strict_geometry: bool = ...) -> tuple[pd.DataFrame, dict[str, int]]: ...
