from typing import Any

"""
RG-09 empirical closure lane (Phase II-0, non-promotable).

Builds on the bounded II-0A harness: same base evaluation, plus reference-condition
comparison, held-out crisis slices, and research-only scaffolds for II-0B / MLN-01.
"""

LOG: Any
EMPIRICAL_PRODUCER_VERSION: Final[str] = ...
META_VALIDITY_SCHEMA: Final[str] = ...
TASK_MANIFEST_RESEARCH_SCHEMA: Final[str] = ...
TASK_MANIFEST_RESEARCH_FILENAME: Final[str] = ...
META_VALIDITY_RESEARCH_FILENAME: Final[str] = ...
EMPIRICAL_WRAPPER_MANIFEST_FILENAME: Final[str] = ...
BOCPD_REGIME_COLUMN: Final[str] = ...
ALLOWED_SUCCESSOR_IDS: Final[frozenset[str]] = ...
SUCCESSOR_BLOCK_ALLOWED_KEYS: Final[frozenset[str]] = ...
DEFAULT_SUCCESSOR_HYPOTHESES: Final[dict[str, Any]] = ...
def projection_rule_version_from_bundle_summary(summary: Mapping[str, Any]) -> str: ...
class RG09EmpiricalClosureResult:
    output_dir: Path = ...
    base_decision: str | None = ...
    fail_closed: bool = ...
    fail_codes: tuple[str, ...] = ...
class RG09EmpiricalClosureError(RuntimeError):
    def __init__(self: Any, message: str, *, fail_codes: list[str]) -> None: ...
def load_run_config_overlay(config_path: Path) -> dict[str, Any]: ...
def validate_successor_hypotheses_overlay(overlay: dict[str, Any]) -> tuple[dict[str, Any] | None, list[str]]: ...
def run_rg09_empirical_closure(*, fixture_path: Path, fixture_summary_path: Path, fixture_metadata_path: Path, config_path: Path, output_dir: Path, boundary_recovery: RG09BoundaryRecoverySpec | None = ...) -> RG09EmpiricalClosureResult: ...
