from typing import Any

"""
RG-09 boundary-treatment primitives for precondition-feasibility recovery lanes.

These helpers operate only on regime *segmentation* prior to support/query geometry.
They do not alter pilot thresholds, null families, or split formulas.
"""

RG09BoundaryRecoveryMode: Any
BASELINE_MODE: Final[RG09BoundaryRecoveryMode] = ...
V1_HYSTERESIS: Final[RG09BoundaryRecoveryMode] = ...
V2_DWELL: Final[RG09BoundaryRecoveryMode] = ...
V3_BURST: Final[RG09BoundaryRecoveryMode] = ...
EPISODE_GROUP_REGIME_COL: Final[str] = ...
class RG09BoundaryRecoverySpec:
    mode: RG09BoundaryRecoveryMode = ...
    max_burst_merge_bars: int = ...
    def enforce_min_dwell(self: Any) -> bool: ...
    def apply_burst_merge(self: Any) -> bool: ...
    def apply_hysteresis(self: Any) -> bool: ...
def causal_hysteresis_labels(regime_ids: list[str], *, confirm_bars: int) -> list[str]: ...
def merge_tiny_transition_bursts(regime_ids: list[str], *, max_burst_bars: int) -> tuple[list[str], int, int]: ...
def build_entity_local_time_block_frame(non_cold: pd.DataFrame) -> pd.DataFrame: ...
def attach_episode_group_regime(non_cold: pd.DataFrame, config: Any, spec: RG09BoundaryRecoverySpec) -> tuple[pd.DataFrame, dict[str, Any]]: ...
