from typing import Any

"""
RG-09 Phase II-0A bounded falsification harness.
"""

SUCCESSOR_IDS: Final[tuple[str, str, str]] = ...
NULL_DISTRIBUTION_INVALID_FAIL_CODE: Final[str] = ...
FIXTURE_GEOMETRY_CONTRACT_FAIL_CODE: Final[str] = ...
NULL_RANGE_TOLERANCE: Final[float] = ...
REGIME_SEPARABILITY_DENOMINATOR_FLOOR: Final[float] = ...
class RG09PilotConfig:
    schema_version: str = ...
    config_id: str = ...
    p_value_threshold: float = ...
    null_draw_count: int = ...
    structural_separability_ratio_threshold: float = ...
    structural_direction_score_threshold: float = ...
    functional_harvey_t_threshold: float = ...
    embargo_gap_bars_daily: int = ...
    embargo_gap_fraction_intraday: float = ...
    min_support_rows: int = ...
    min_query_rows: int = ...
    label_confidence_threshold: float = ...
    min_admissible_episode_count: int = ...
    min_regime_transition_count: int = ...
    min_support_query_mass_per_regime: int = ...
    min_regime_class_count_per_fold: int = ...
    min_temporal_folds: int = ...
    min_dwell_time_bars: int = ...
    label_horizon_bars: int = ...
    low_confidence_boundary_policy: str = ...
    functional_model_default: str = ...
    functional_model_fallback: str = ...
    null_seed_namespace: str = ...
    min_episode_regime_class_purity: float = ...
    episode_construction: str = ...
    threshold_ids: dict[str, str] = ...
class RG09HarnessResult:
    output_dir: Path = ...
    decision: str | None = ...
class RG09HarnessRunData:
    output_dir: Path = ...
    decision: str | None = ...
    config: RG09PilotConfig = ...
    summary: dict[str, Any] = ...
    metadata: dict[str, Any] = ...
    fixture_sha256: str = ...
    config_version: str = ...
    generation_timestamp: str = ...
    frame: pd.DataFrame = ...
    base_episodes: pd.DataFrame = ...
    exclusion_counts: dict[str, int] = ...
    gate_result: dict[str, Any] = ...
    fixture_validation_fail_codes: list[str] = ...
def validate_successor_request(requested_successor_ids: Sequence[str] | None) -> str | None: ...
def load_rg09_config(config_path: Path) -> RG09PilotConfig: ...
def run_rg09_harness_internal(*, fixture_path: Path, fixture_summary_path: Path, fixture_metadata_path: Path, config_path: Path, output_dir: Path, boundary_recovery: RG09BoundaryRecoverySpec | None = ...) -> RG09HarnessRunData: ...
def run_rg09_harness(*, fixture_path: Path, fixture_summary_path: Path, fixture_metadata_path: Path, config_path: Path, output_dir: Path, boundary_recovery: RG09BoundaryRecoverySpec | None = ...) -> RG09HarnessResult: ...
def build_rg09_candidate_episode_groups(frame: pd.DataFrame, config: RG09PilotConfig, *, boundary_recovery: RG09BoundaryRecoverySpec | None = ...) -> list[pd.DataFrame]: ...
