from typing import Any

"""
Artifact builders and deterministic writers for the RG-09 II-0A harness.
"""

GATE_RESULT_FILENAME: Final[str] = ...
RG09_SURFACE_MANIFEST_FILENAME: Final[str] = ...
TASK_MANIFEST_FILENAME: Final[str] = ...
DIAGNOSTICS_FILENAME: Final[str] = ...
MACHINE_MANIFEST_FILENAME: Final[str] = ...
PRODUCER_VERSION: Final[str] = ...
ASSUMPTION_IDS: Final[tuple[str, ...]] = ...
def build_task_manifest(*, fixture_sha256: str, summary: dict[str, Any], admissible_row_count: int, admissible_episode_count: int, exclusion_counts: dict[str, int]) -> dict[str, Any]: ...
def build_gate_result(*, decision: str | None, decision_reason: str, gate_executed: bool, fixture_sha256: str, fixture_config_version: str, generation_timestamp: str, evidence: dict[str, Any], fail_codes: list[str], successor_hypotheses: dict[str, Any], hypothesis_id: str = ...) -> dict[str, Any]: ...
def build_diagnostics(*, summary: dict[str, Any], exclusion_counts: dict[str, int], null_summaries: dict[str, Any], admissible_episode_count: int, threshold_governance_preflight: dict[str, Any] | None = ...) -> dict[str, Any]: ...
def build_machine_manifest(*, version: str, output_dir: Path, fixture_sha256: str, decision: str | None, producer_version: str, changes: list[dict[str, Any]], tests: list[dict[str, Any]], risks: list[dict[str, str]]) -> dict[str, Any]: ...
def write_rg09_artifacts(output_dir: Path, *, gate_result: dict[str, Any], task_manifest: dict[str, Any], diagnostics: dict[str, Any], machine_manifest: dict[str, Any]) -> None: ...
