from typing import Any

"""
Threshold IDs for RG-09 pilot config (ThresholdGovernanceRegister §4 migration).
"""

VALIDATE_NOTE: Final[str] = ...
THR_RG09_V01: Final[str] = ...
THR_RG09_V02: Final[str] = ...
THR_RG09_V03: Final[str] = ...
THR_RG09_V04: Final[str] = ...
THR_RG09_V05: Final[str] = ...
THR_RG09_V06: Final[str] = ...
THR_RG09_V07: Final[str] = ...
THR_RG09_V08: Final[str] = ...
THR_RG09_V09: Final[str] = ...
THR_RG09_V10: Final[str] = ...
THR_RG09_V11: Final[str] = ...
THR_RG09_V12: Final[str] = ...
THR_RG09_V13: Final[str] = ...
THR_RG09_V14: Final[str] = ...
THR_RG09_V15: Final[str] = ...
THR_RG09_V16: Final[str] = ...
THR_RG09_V17: Final[str] = ...
THR_RG09_V18: Final[str] = ...
THR_RG09_V19: Final[str] = ...
class RG09ThresholdFieldSpec:
    threshold_id: str = ...
    gate_critical: bool = ...
RG09_CONFIG_THRESHOLD_SPECS: Final[dict[str, RG09ThresholdFieldSpec]] = ...
RG09_CONFIGURED_THRESHOLD_PRECHECK_SPECS: Final[dict[str, ConfiguredThresholdSpec]] = ...
def threshold_value_record(value: _ThresholdValue, threshold_id: str, *, state: Literal['PROVISIONAL', 'VALIDATED', 'REJECTED', 'DEPRECATED'] = ...) -> dict[str, Any]: ...
def provisional_threshold_record(value: _ThresholdValue, threshold_id: str, *, state: Literal['PROVISIONAL', 'VALIDATED', 'REJECTED', 'DEPRECATED'] = ...) -> dict[str, Any]: ...
