from typing import Any

"""
OI-59 Experiment 3: boundary-treatment redesign from Variant B baseline.
"""

OI59_BOUNDARY_TREATMENT_SCHEMA: Final[str] = ...
OI59_BOUNDARY_TREATMENT_REPORT_FILENAME: Final[str] = ...
OI59_BOUNDARY_TREATMENT_DIAGNOSTIC_FILENAME: Final[str] = ...
def build_oi59_boundary_treatment_report(*, fixture_path: Path, fixture_summary_path: Path, fixture_metadata_path: Path, config_path: Path, experiment2_report_path: Path, output_dir: Path, baseline_handoff_path: Path | None = ...) -> dict[str, Any]: ...
