from typing import Any

"""
Guardrails for Phase II-0B scaffold emitters vs governed RG-09 lanes.
"""

GOVERNED_LANE_ENV: Final[str] = ...
class ScaffoldEmitterForbiddenError(RuntimeError):
    ...
def assert_scaffold_emitter_allowed(*, emitter_name: str) -> None: ...
def governed_lane_context() -> Generator[None, None, None]: ...
