from typing import Any

"""
Deterministic run identity and seed hooks for Phase II ML emissions (non-promotable).

**Canonical run naming:** ``run_id`` strings MUST come only from :func:`derive_run_id` /
:func:`build_run_identity`. Emitters (task manifest, meta validity, execution assumptions, and
:func:`phase2_artifact_contract.emit_phase2_artifacts`) all use ``build_run_identity(seed)``; do not
fork SHA256 or string formatting for run identity elsewhere.

**Determinism:** :func:`derive_run_id` is pure: ``SHA256(RUN_ID_SALT + UTF-8 decimal seed)``,
formatted as ``run.sha256:<64-hex>``. Same integer ``seed`` always yields the same ``run_id``.
Distinct seeds are expected to yield distinct ``run_id`` values (not formally collision-free, but
salted and practically unique for 31-bit scaffold seeds).

**Governed seed lineage:** Phase II governed artifacts carry a root seed and namespace-derived
lineage. Artifact timestamps come from the run context; seed helpers never read wall-clock time.
"""

RUN_IDENTITY_SCHEMA: Final[str] = ...
SEED_LINEAGE_SCHEMA: Final[str] = ...
RUN_ID_SALT: Final[bytes] = ...
DERIVED_SEED_MESSAGE_PREFIX: Final[str] = ...
ALLOWED_SEED_NAMESPACES: Final[frozenset[str]] = ...
class Phase2ScaffoldRunIdentity:
    seed: int = ...
    run_id: str = ...
    def to_block(self: Any) -> dict[str, Any]: ...
def derive_run_id(seed: int) -> str: ...
def scaffold_int_seed_from_content_tag(tag: str) -> int: ...
def build_run_identity(seed: int) -> Phase2ScaffoldRunIdentity: ...
class Phase2DerivedSeed:
    namespace: str = ...
    context_string: str = ...
    derived_seed_hex: str = ...
    uint64_seed: int = ...
    def to_block(self: Any) -> dict[str, Any]: ...
class Phase2SeedLineage:
    run_seed_root: str = ...
    derived_seeds: tuple[Phase2DerivedSeed, ...] = ...
    def to_block(self: Any) -> dict[str, Any]: ...
def run_seed_root_from_int(seed: int) -> str: ...
def derive_phase2_seed(*, run_seed_root: str, namespace: str, context_string: str) -> Phase2DerivedSeed: ...
def build_seed_lineage(*, run_seed_root: str, derivations: tuple[tuple[str, str], ...]) -> Phase2SeedLineage: ...
