from typing import Any

"""
MLC-2 governed MetaTask builder and episode construction helpers.

Canonical path resolution
-------------------------

The governing documents name ``py/meta/task_generator.py``.  This repo's
Python root is ``pysrc/``; therefore the governed in-repo path is
``pysrc/meta/task_generator.py``.

This module owns construction-time admissibility only.  It slices candidate
episodes, enforces PIT and leakage geometry, computes derived identity fields,
and calls :class:`pysrc.meta.task.MetaTask` exactly once for valid episodes.
Curriculum, replay priority, and holdout sampling policy live in
``pysrc/meta/curriculum.py``.
"""

LOG: Any
Frequency: Any
class DataViewLike(Protocol):
    def as_of(self: Any, symbols: Sequence[str], fields: Sequence[str], knowledge_date: date) -> pd.DataFrame: ...
class EpisodeConstructionError(DataPreconditionError):
    ...
class TaskGeneratorConfig:
    episode_timestamps: Sequence[datetime | date | str | pd.Timestamp] = ...
    symbols: tuple[str, ...] = ...
    fields: tuple[str, ...] = ...
    n_support: int = ...
    n_query: int = ...
    purge_window: int | None = ...
    embargo_window: int | None = ...
    frequency: Frequency = ...
    bar_interval: pd.Timedelta = ...
    encoder_input: EncoderInputContract | None = ...
def build_meta_task(data_view: DataViewLike, regime_label: RegimeLabelRecord, signal_ids: list[str], signal_mask: NDArray[np.bool_], signal_set_version: int, encoder: ContextEncoderProtocol, horizon: int, config: TaskGeneratorConfig) -> MetaTask: ...
