from typing import Any

"""
Scaffold and governed task-manifest emitters.
"""

SCHEMA_VERSION: Final[str] = ...
GOVERNED_SCHEMA_VERSION: Final[str] = ...
CONTENT_HASH_ALGORITHM: Final[str] = ...
CONTENT_HASH_CANONICALIZATION: Final[str] = ...
class TaskManifestTaskInput:
    regime_id: str = ...
    regime_class: str = ...
    t0: str = ...
    t1: str = ...
    signal_ids_hash: str = ...
    signal_set_version: str = ...
    support_last_timestamp: str = ...
    pit_boundary: str | None = ...
    signal_ids: tuple[str, ...] | None = ...
    signal_mask: tuple[bool, ...] | None = ...
    active_k: int | None = ...
class TaskManifestReport:
    document: dict[str, Any] = ...
    content_hash: str = ...
def compute_task_id(*, regime_id: str, t0: str, t1: str, signal_ids_hash: str) -> str: ...
def resolve_pit_boundary(*, support_last_timestamp: str, pit_boundary: str | None) -> str: ...
def build_task_record(task: TaskManifestTaskInput) -> dict[str, Any]: ...
def build_task_manifest_document(*, tasks: Sequence[TaskManifestTaskInput], run_identity: Phase2ScaffoldRunIdentity, schema_version: str = ..., include_non_promotable: bool = ...) -> dict[str, Any]: ...
def emit_task_manifest(output_path: Path, *, tasks: Sequence[TaskManifestTaskInput], seed: int) -> dict[str, Any]: ...
def emit_task_manifest_from_mapping(output_path: Path, *, tasks: Sequence[Mapping[str, Any]], seed: int) -> dict[str, Any]: ...
def recompute_task_manifest_content_hash_from_document(document: Mapping[str, Any]) -> str: ...
def emit_governed_task_manifest(tasks: Sequence[MetaTask | object], config: TaskManifestConfig) -> TaskManifestReport: ...
