from typing import Any

"""
Config surface for governed task-manifest emission.
"""

DEFAULT_OUTPUT_DIR: Any
class TaskManifestConfig:
    run_id: str = ...
    signal_set_version: str | int = ...
    schema_version: str = ...
    output_dir: str = ...
    def with_updates(self: Any, **changes: Unpack[_TaskManifestConfigUpdates]) -> TaskManifestConfig: ...
