from typing import Any

"""
MLC-0 · Promotable canonical :class:`MetaTask` dataclass.

This is the **promotable** MetaTask surface for Phase II (MLC-0).  The
non-promotable II-0C pilot scaffold lives in
``pysrc/meta_learning/task_generator.py`` and exists only as a reference
fixture — governed paths must depend on :class:`MetaTask` from this module.

Canonical path resolution (MLC-0 Step 1)
----------------------------------------

``MetaLearningCore.md`` §5.5 specifies ``py/meta/task.py``.  This repo uses
``pysrc/`` as the Python source root (see ``pyproject.toml`` ``packages =
[{ include = "pysrc" }, ...]``), therefore the canonical path in-repo is
``pysrc/meta/task.py``.  Directory discovery result recorded here per the
brief's Step 1 instruction.

Schema authority
----------------

Fields follow ``MetaLearningCore.md`` §2.1 and
``MetaLearningArchitectureVision.md`` §4.1 for the frozen v2.0 schema.
``regime_embedding`` is ``Optional[np.ndarray]``; MLC-0 keeps it ``None``
until MLC-1 (context encoder) is online.

Construction discipline
-----------------------

This module does **not** define ``build_meta_task`` — that is MLC-2
(``task_generator.py``).  Direct construction is permitted but
:meth:`MetaTask.__post_init__` enforces the full schema invariants so
that any accidental direct-construction path raises immediately rather
than producing a silently malformed task.
"""

META_TASK_SCHEMA_VERSION: str = ...
class MetaTask:
    task_id: str = ...
    regime_id: str = ...
    regime_class: str = ...
    t0: str = ...
    t1: str = ...
    pit_boundary: str = ...
    support_set: tuple[str, ...] = ...
    query_set: tuple[str, ...] = ...
    signal_ids: tuple[str, ...] = ...
    signal_mask: tuple[bool, ...] = ...
    signal_set_version: str = ...
    signal_ids_hash: str = ...
    horizon: int = ...
    active_k: int = ...
    regime_embedding: Optional[NDArray[np.floating[Any]]] = ...
    def has_regime_embedding(self: Any) -> bool: ...
    def as_record(self: Any) -> dict[str, Any]: ...
