from typing import Any

"""
MLN-07 threshold identity, state, and enforcement (ThresholdGovernanceRegister).

Canonical register: ``threshold_register.mln07.v1.json`` alongside this module.

**Enforced today**
- :func:`resolve_threshold` — single governed lookup; raises on unknown, malformed, REJECTED,
  DEPRECATED, and on PROVISIONAL when ``gate_critical=True``.
- :func:`preflight_threshold_references` — batch audit for governed runs.
- :func:`preflight_configured_thresholds` — config-layer WARN/FAIL audit for anonymous threshold use.
- :func:`warn_hardcoded_threshold` — non-gate numeric threshold without ID (audit WARN).
- :func:`require_gate_threshold_id` — gate path must pass a non-empty ``threshold_id``.

**Still manual / unwired**
- MLN-06 orchestrator wiring remains library-only per MLN-07 brief scope.
- Non-RG-09 governed consumers still need to migrate from anonymous literals to ``threshold_id``.
- ``maybe_preflight_rg09_harness_gate_thresholds`` remains as an environment-gated compatibility shim.
"""

REGISTER_FILENAME: Final[str] = ...
THRESHOLD_STATES: Final[frozenset[str]] = ...
REQUIRED_RECORD_FIELDS: Final[tuple[str, ...]] = ...
class ThresholdGovernanceError(RuntimeError):
    def __init__(self: Any, message: str, *, details: dict[str, Any] | None = ...) -> None: ...
class ThresholdAuditSeverity(str, Enum):
    WARN: Any
    FAIL: Any
class ThresholdAuditFinding:
    severity: ThresholdAuditSeverity = ...
    code: str = ...
    message: str = ...
    details: dict[str, Any] = ...
class ThresholdPreflightReport:
    findings: tuple[ThresholdAuditFinding, ...] = ...
    passed: bool = ...
class ThresholdRecord:
    threshold_id: str = ...
    name: str = ...
    governing_surface: str = ...
    consumer_surface: str = ...
    state: str = ...
    current_expression: str = ...
    evidence_required: str = ...
    evidence_location: str = ...
    authority: str = ...
    gate_critical: bool = ...
    supersedes: str | None = ...
    superseded_by: str | None = ...
    last_reviewed: str = ...
class ConfiguredThresholdSpec:
    field_name: str = ...
    gate_critical: bool = ...
def default_register_path() -> Path: ...
def load_threshold_register(path: Path | None = ...) -> dict[str, ThresholdRecord]: ...
def clear_threshold_register_cache() -> None: ...
def resolve_threshold(threshold_id: str, *, consumer: str, gate_critical: bool, register_path: Path | None = ...) -> ThresholdRecord: ...
def require_gate_threshold_id(threshold_id: str | None, *, consumer: str) -> str: ...
def warn_hardcoded_threshold(*, consumer: str, detail: str) -> None: ...
def preflight_configured_thresholds(raw_config: Mapping[str, Any], *, consumer: str, field_specs: Mapping[str, ConfiguredThresholdSpec], register_path: Path | None = ...) -> ThresholdPreflightReport: ...
def preflight_threshold_references(refs: Sequence[tuple[str, bool]], *, consumer: str, register_path: Path | None = ...) -> ThresholdPreflightReport: ...
def preflight_report_to_json(report: ThresholdPreflightReport) -> dict[str, Any]: ...
RG09_HARNESS_GATE_PREFLIGHT_IDS: Final[tuple[str, ...]] = ...
def maybe_preflight_rg09_harness_gate_thresholds(*, consumer: str = ...) -> None: ...
