from typing import Any

"""
WS-1 bounded baseline comparison harness — frozen configuration (II-C evidence lane).
"""

W1EvidenceSanityMode: Any
class W1BaselineConfigError(ValueError):
    ...
class W1EvidenceSanityConfig:
    min_std_query_targets: float = ...
    min_std_support_targets: float = ...
    min_std_incumbent_preds_per_fold: float = ...
    min_std_challenger_preds_per_fold: float = ...
    min_distinct_query_target_values: int = ...
    min_distinct_support_target_values: int = ...
    min_fold_query_target_variance: float = ...
    require_heterogeneous_task_windows: bool = ...
    require_fold_metrics_non_degenerate: bool = ...
    min_abs_gross_ic: float = ...
    min_abs_net_sharpe: float = ...
    min_turnover: float = ...
    is_fixture_smoke_profile: bool = ...
    def fixture_smoke(cls: Any) -> W1EvidenceSanityConfig: ...
class W1BaselineConfig:
    baseline_id: str = ...
    n_walk_forward_folds: int = ...
    fold_length_bars: int = ...
    warmup_bars: int = ...
    regime_classes: tuple[str, ...] = ...
    min_tasks_per_class: int = ...
    spread_bps: float = ...
    slippage_bps: float = ...
    borrow_rate_ann: float = ...
    artifact_dir: str = ...
    report_filename: str = ...
    example_filename: str = ...
    random_seed: int = ...
    schema_version: str = ...
    evidence_sanity: W1EvidenceSanityConfig = ...
    evidence_sanity_mode: W1EvidenceSanityMode = ...
    min_unique_eval_tasks_per_fold: int = ...
    min_unique_train_tasks_before_fold: int = ...
