from typing import Any

"""
WS-1 bounded baseline harness — frozen result types (II-C evidence lane).
"""

W1EvidenceLane: Any
class W1FoldResult:
    fold_index: int = ...
    fold_start: str = ...
    fold_end: str = ...
    net_sharpe: float = ...
    gross_ic: float = ...
    crisis_ic: float | None = ...
    max_drawdown: float = ...
    turnover: float = ...
    n_query_rows_scored: int = ...
    n_unique_tasks_scored: int = ...
    regime_breakdown: dict[str, float | None] = ...
class W1AggregateMetrics:
    mean_net_sharpe: float = ...
    mean_net_sharpe_normal_null_p: float | None = ...
    mean_gross_ic: float = ...
    mean_crisis_ic: float | None = ...
    mean_max_drawdown: float = ...
    mean_turnover: float = ...
    n_folds_with_crisis: int = ...
class W1CostAssumptions:
    spread_bps: float = ...
    slippage_bps: float = ...
    borrow_rate_ann: float = ...
class W1ThresholdReference:
    id: str = ...
    state: str = ...
    current_expression: str = ...
class W1EvidenceSource:
    market_data_source: str = ...
    label_source: str = ...
    target_source: str = ...
    challenger_source: str = ...
    real_market_data_evidence: bool = ...
    w1_gate_closure_eligible: bool = ...
    pit_heterogeneity_governance_acknowledged: bool = ...
    def as_dict(self: Any) -> dict[str, Any]: ...
class W1ComparisonFingerprints:
    data_fingerprint: str = ...
    splits_fingerprint: str = ...
    cost_assumptions_fingerprint: str = ...
class W1BaselineResult:
    schema_version: str = ...
    baseline_id: str = ...
    run_timestamp_utc: str = ...
    n_folds: int = ...
    fold_results: tuple[W1FoldResult, ...] = ...
    aggregate: W1AggregateMetrics = ...
    cost_assumptions: W1CostAssumptions = ...
    threshold_references: tuple[W1ThresholdReference, ...] = ...
    gate_ii_posture: str = ...
    promotion_note: str = ...
    content_hash: dict[str, str] = ...
    evidence_lane: W1EvidenceLane = ...
    row_level_fold_results: tuple[W1FoldResult, ...] | None = ...
    row_level_aggregate: W1AggregateMetrics | None = ...
    challenger_aggregate: W1AggregateMetrics | None = ...
    challenger_fold_results: tuple[W1FoldResult, ...] | None = ...
    challenger_row_level_aggregate: W1AggregateMetrics | None = ...
    challenger_row_level_fold_results: tuple[W1FoldResult, ...] | None = ...
    incumbent_model_config: dict[str, Any] | None = ...
    evidence_source: W1EvidenceSource | None = ...
    target_provenance: dict[str, Any] | None = ...
    comparison_fingerprints: W1ComparisonFingerprints | None = ...
    pit_boundary_policy: str | None = ...
    heterogeneous_task_pits_supported: bool | None = ...
    challenger_surface_summary: dict[str, Any] | None = ...
    challenger_surface_content_hash: str | None = ...
    evidence_sanity_report: dict[str, Any] | None = ...
