from typing import Any

"""
WS-1 governed JSON emission, content hashing, and synthetic pool I/O (II-C evidence lane).

This module is the **supported** surface for artifact helpers and the default synthetic
task pool builder. The compute kernel lives in :mod:`pysrc.meta.w1_baseline_runner`
(``run_w1_baseline_evidence`` only).
"""

def build_w1_synthetic_task_pool(n_tasks: int, cfg: W1BaselineConfig) -> tuple[MetaTask, ...]: ...
def bind_w1_content_hash_from_body(body: dict[str, Any]) -> dict[str, str]: ...
def w1_baseline_result_to_document(result: W1BaselineResult) -> dict[str, Any]: ...
def recompute_w1_content_hash_from_document(doc: Mapping[str, Any]) -> str: ...
def emit_w1_baseline_report_json(path: Path, result: W1BaselineResult) -> None: ...
def emit_w1_baseline_example_json(path: Path, result: W1BaselineResult) -> None: ...
