from typing import Any

"""
Governed XGBoost incumbent baseline for WS-1 real-data lane (MLC / II-C).

Regime conditioning uses **Level-2** ``regime_class`` only (one-hot features), not compositional
``regime_id`` (Architecture Vision §4.2).  Features are task-derived scalars plus the one-hot
vector — **no** encoder imports and **no** ``regime_embedding`` consumption.
"""

class XGBoostIncumbentConfig:
    random_state: int = ...
    n_estimators: int = ...
    max_depth: int = ...
    learning_rate: float = ...
    tree_method: str = ...
class XGBoostIncumbentBaseline:
    def __init__(self: Any, cfg: XGBoostIncumbentConfig | None = ...) -> None: ...
    def fit_for_training_tasks(self: Any, tasks: Sequence[MetaTask], *, rng_seed: int, training_targets: Sequence[float] | None = ...) -> None: ...
    def predict_scores(self: Any, task: MetaTask, *, fold_index: int, rng_seed: int, use_hash_score_jitter: bool = ...) -> NDArray[np.float64]: ...
    def describe(self: Any) -> dict[str, Any]: ...
def challenger_proxy_scores_for_tasks(tasks: Sequence[MetaTask], *, fold_index: int, rng_seed: int) -> NDArray[np.float64]: ...
