from typing import Any

"""
Canonical W1 meta-allocator challenger prediction surface (governed real lane).

W1 consumes this artifact only — not trainer internals. Validation is strict and
import-light (no XGBoost / Reptile).
"""

W1_CHALLENGER_SURFACE_SCHEMA_VERSION: Any
KNOWN_LEAKAGE_POLICIES: frozenset[str] = ...
class W1ChallengerSurfaceValidationError(Exception):
    def __init__(self: Any, message: str, *, details: dict[str, Any] | None = ...) -> None: ...
class W1ChallengerPrediction:
    task_id: str = ...
    fold_index: int = ...
    query_scores: tuple[float, ...] = ...
    prediction_time_utc: str = ...
    pit_boundary: str = ...
class W1ChallengerSurface:
    schema_version: str = ...
    source: str = ...
    model_family: str = ...
    predictions: tuple[W1ChallengerPrediction, ...] = ...
    task_pool_hash: str = ...
    data_fingerprint: str = ...
    splits_fingerprint: str = ...
    cost_assumptions_fingerprint: str = ...
    signal_set_version: str = ...
    created_at_utc: str = ...
    leakage_policy: str = ...
    uses_query_labels: bool = ...
    uses_xgboost_outputs: bool = ...
    uses_post_query_metrics: bool = ...
    model_state_hash: str | None = ...
    governed_checkpoint_lineage_verified: bool = ...
class W1FoldPlan:
    warmup_bars: int = ...
    fold_length_bars: int = ...
    n_walk_forward_folds: int = ...
    train_task_ids_by_fold: tuple[tuple[str, ...], ...] = ...
    task_ids_by_fold: tuple[tuple[str, ...], ...] = ...
def derive_w1_fold_plan(sorted_tasks: Sequence[MetaTask], config: W1BaselineConfig) -> W1FoldPlan: ...
def valid_learned_model_state_hash(h: str | None) -> bool: ...
def w1_challenger_surface_closure_eligible(surface: W1ChallengerSurface) -> bool: ...
def validate_w1_challenger_surface(surface: W1ChallengerSurface, *, expected_task_ids_by_fold: Mapping[int, tuple[str, ...]], expected_query_lengths: Mapping[str, int], task_pool_hash: str, data_fingerprint: str, splits_fingerprint: str, cost_assumptions_fingerprint: str, signal_set_version: str) -> None: ...
def challenger_mean_query_scores_for_tasks(surface: W1ChallengerSurface, tasks: Sequence[MetaTask], fold_index: int) -> NDArray[np.float64]: ...
def w1_challenger_surface_summary_dict(surface: W1ChallengerSurface) -> dict[str, Any]: ...
def w1_challenger_surface_to_canonical_dict(surface: W1ChallengerSurface) -> dict[str, Any]: ...
