from typing import Any

"""
W1 governed-real pre-closure evidence sanity (targets, preds, windows, optional fold metrics).
"""

class W1FoldSanityDiag:
    fold_index: int = ...
    query_target_variance: float = ...
    std_incumbent_preds: float = ...
    std_challenger_preds: float | None = ...
def w1_evidence_sanity_pool_target_stats(tasks: Sequence[MetaTask], task_query_targets: Mapping[str, float], task_support_targets: Mapping[str, float]) -> dict[str, float | int]: ...
def w1_evidence_sanity_per_fold_pred_rows(fold_diags: Sequence[W1FoldSanityDiag]) -> list[dict[str, float | int | None]]: ...
def w1_evidence_sanity_closure_ok(*, tasks: Sequence[MetaTask], task_query_targets: Mapping[str, float], task_support_targets: Mapping[str, float], fold_diags: Sequence[W1FoldSanityDiag], fold_results_inc: Sequence[W1FoldResult], fold_results_ch: Sequence[W1FoldResult] | None, cfg: W1EvidenceSanityConfig) -> tuple[bool, tuple[str, ...]]: ...
