from typing import Any

"""
Point-in-time CSV-backed :class:`DataViewLike` for W1 governed historical fixtures.
"""

class W1GovernedCsvDataView:
    symbol: str = ...
    def from_csv(cls: Any, path: Path, *, symbol: str = ...) -> W1GovernedCsvDataView: ...
    def snapshot_sha256(self: Any) -> str: ...
    def as_of(self: Any, symbols: Sequence[str], fields: Sequence[str], knowledge_date: date) -> pd.DataFrame: ...
