from typing import Any

"""
Governed linear W1 meta-head trainer (7-d features, support economic targets, shared curriculum gates).

Training labels are **support-window mean log return net of costs** from
:attr:`pysrc.meta.w1_real_task_pool.W1RealTaskPoolOutcome.task_support_mean_log_return_net`
(or an equivalent caller-supplied mapping). Missing or non-finite targets for any sampled task
→ :class:`W1GovernedMetaHeadTrainFailure` (**INSUFFICIENT** — no substitutes).

Curriculum batching reuses :func:`pysrc.meta.reptile_trainer.prepare_governed_curriculum_batch`
(governance mins, crisis floor) with the same semantics as :class:`pysrc.meta.reptile_trainer.ReptileTrainer`.
"""

TRAINED_BY_W1_GOVERNED_META_HEAD_V1: Final[str] = ...
class W1GovernedMetaHeadTrainConfig:
    outer_lr: float = ...
    n_gradient_steps: int = ...
class W1GovernedMetaHeadTrainSuccess:
    weights: NDArray[np.float64] = ...
    tasks: tuple[MetaTask, ...] = ...
    trainer_config_hash: str = ...
    model_state_hash: str = ...
    training_run_id: str = ...
    final_mse: float = ...
    batch_counts: dict[str, Any] = ...
    code_version: str = ...
class W1GovernedMetaHeadTrainFailure:
    reasons: tuple[str, ...] = ...
    batch_counts: dict[str, Any] | None = ...
def derive_w1_governed_meta_head_trainer_config_hash(head_cfg: W1GovernedMetaHeadTrainConfig, *, reptile_config: ReptileTrainerConfig, batch_size: int) -> str: ...
def derive_w1_governed_meta_head_model_state_hash(weights: NDArray[np.float64]) -> str: ...
def fit_w1_governed_meta_head(*, sampler: Any, reptile_config: ReptileTrainerConfig, support_targets_by_task_id: Mapping[str, float], head_cfg: W1GovernedMetaHeadTrainConfig, seed: int) -> W1GovernedMetaHeadTrainSuccess | W1GovernedMetaHeadTrainFailure: ...
