from typing import Any

"""
Governed real MetaTask pool builder for WS-1 W1 evidence (MLC-2 / MLN-02).

Every task is produced exclusively via :func:`pysrc.meta.task_generator.build_meta_task`.
Crisis Level-2 labels follow MLN-02-AMD-01 (``vol_hi`` AND ``severity_flag``); BOCPD state
feeds ``regime_id`` only.  Named GFC / COVID holdout windows are excluded from the pool
and declared for artifact emission.
"""

LOG: Any
W1RealPoolEvidenceMode: Any
class W1RealPoolBuildError(DataPreconditionError):
    ...
def w1_meta_tasks_as_manifest_inputs(tasks: Sequence[MetaTask]) -> tuple[TaskManifestTaskInput, ...]: ...
class UniverseResolver(Protocol):
    ...
class W1RealPoolConfig:
    data_view: DataViewLike = ...
    encoder: ContextEncoderProtocol = ...
    labeler: RegimeLabeler = ...
    bocpd_config: BOCPDConfig = ...
    universe_resolver: UniverseResolver = ...
    signal_set_version: int = ...
    construction_seed: int = ...
    start_ts: str = ...
    end_ts: str = ...
    universe_id: str = ...
    symbols: tuple[str, ...] = ...
    regime_label_source: Literal['emitted_bocpd', 'labeler_from_dataview'] = ...
    registry_jsonl_path: Path | None = ...
    bucket_minimums: Mapping[str, int] = ...
    gfc_holdout_start: str = ...
    gfc_holdout_end: str = ...
    covid_holdout_start: str = ...
    covid_holdout_end: str = ...
    calendar_origin: datetime = ...
    episode_stride_days: int = ...
    fields: tuple[str, ...] = ...
    spread_bps: float = ...
    slippage_bps: float = ...
    borrow_rate_ann: float = ...
    max_calendar_bars: int | None = ...
    evidence_mode: W1RealPoolEvidenceMode = ...
    test_fixture_log_returns: NDArray[np.float64] | None = ...
class W1RealTaskPoolOutcome:
    tasks: tuple[MetaTask, ...] = ...
    task_pool_hash: str = ...
    diagnostics: dict[str, Any] = ...
    holdout_declaration: dict[str, Any] = ...
    registry: TaskRegistry = ...
    task_query_targets_net: tuple[tuple[str, float], ...] = ...
    task_support_mean_log_return_net: tuple[tuple[str, float], ...] = ...
    data_fingerprint: str | None = ...
def w1_support_mean_log_return_net_from_pool(outcome: W1RealTaskPoolOutcome) -> dict[str, float]: ...
def build_w1_real_task_pool(config: W1RealPoolConfig) -> W1RealTaskPoolOutcome: ...
