from typing import Any

"""
W2-S1 baseline-only dry run for the governed 8-instrument RG09 basket.
"""

LOG: Any
STATUS_PASS: Final[str] = ...
STATUS_FAIL: Final[str] = ...
STATUS_BLOCKED: Final[str] = ...
SIGNAL_FAMILY: Final[str] = ...
ASSET_CLASS: Final[str] = ...
ALERT_MISSING_BASELINE_SCORE: Final[str] = ...
ALERT_MISSING_QUERY_TARGET: Final[str] = ...
ALERT_TRAIN_EVAL_TIME_OVERLAP: Final[str] = ...
ALERT_TRAIN_EVAL_OPPORTUNITY_OVERLAP: Final[str] = ...
ALERT_MANY_TO_ONE_JOIN_EXPANSION: Final[str] = ...
ALERT_ONE_TO_MANY_JOIN_EXPANSION: Final[str] = ...
ALERT_DUPLICATE_OPPORTUNITY_ID: Final[str] = ...
ALERT_FINGERPRINT_MISMATCH: Final[str] = ...
ALERT_INSUFFICIENT_UNIQUE_TICKERS: Final[str] = ...
ALERT_INSUFFICIENT_EVAL_OPPORTUNITIES: Final[str] = ...
ALERT_INSUFFICIENT_REGIME_COVERAGE: Final[str] = ...
ALERT_PURGING_OR_EMBARGO_MISSING: Final[str] = ...
ALERT_MISSING_COST_FIELD: Final[str] = ...
ALERT_FEATURE_TIMESTAMP_AFTER_PIT_BOUNDARY: Final[str] = ...
ALERT_FEATURE_USES_QUERY_LABEL: Final[str] = ...
ALERT_LIGHTGBM_UNAVAILABLE: Final[str] = ...
class W2S1Config:
    output_dir: Path = ...
    design_dir: Path = ...
    fixture_path: Path = ...
    fixture_summary_path: Path = ...
    fixture_metadata_path: Path = ...
    multi_manifest_path: Path = ...
    download_manifest_path: Path = ...
    signal_family: str = ...
    asset_class: str = ...
    horizon_bars: int = ...
    support_return_bars: int = ...
    support_vol_bars: int = ...
    n_folds: int = ...
    embargo_days: int = ...
    spread_bps: float = ...
    slippage_bps: float = ...
    borrow_rate_ann: float = ...
    selection_k: int = ...
    top_k_grid: tuple[int, ...] = ...
    timestamp_utc: str = ...
    max_rebalance_dates: int | None = ...
    xgb_random_state: int = ...
    xgb_n_estimators: int = ...
    xgb_max_depth: int = ...
    xgb_learning_rate: float = ...
def run_w2_s1_baseline_only(cfg: W2S1Config | None = ...) -> dict[str, object]: ...
