from typing import Any

"""
Next-Gen Self-Evolving Strategy Adapter for pipeline_strategy.py

This adapter creates an autonomous strategy evolution system that:
- Monitors performance drift across multiple timeframes
- Automatically triggers reoptimization when drift is detected
- Manages ensemble of strategies with dynamic blending
- Implements online learning with rolling windows
- Provides adaptive parameter spaces that evolve over time
- Handles regime detection and strategy switching
"""

class DriftState:
    ref_mean: float = ...
    ref_std: float = ...
LOG: Any
class EvolutionEvent:
    timestamp: pd.Timestamp = ...
    event_type: str = ...
    strategy_name: str = ...
    old_params: Dict[str, Any] = ...
    new_params: Dict[str, Any] = ...
    performance_delta: float = ...
    metadata: Dict[str, Any] = ...
class EvolutionCallback(Protocol):
    def on_evolution_event(self: Any, event: EvolutionEvent) -> None: ...
class AdaptiveParameterSpace:
    def __init__(self: Any, base_space: Dict[str, Tuple[float, float]], adaptation_rate: float = ..., memory_length: int = ...) -> Any: ...
    def update(self: Any, params: Dict[str, Any], score: float) -> None: ...
    def evolve_space(self: Any) -> Dict[str, Tuple[float, float]]: ...
class MultiFrameDriftState:
    short_term: Optional[DriftState] = ...
    medium_term: Optional[DriftState] = ...
    long_term: Optional[DriftState] = ...
class MultiTimeframeDriftMonitor:
    def __init__(self: Any, short_window: int = ..., medium_window: int = ..., long_window: int = ..., sensitivity: float = ...) -> Any: ...
    def check_drift(self: Any, returns: pd.Series) -> Tuple[bool, Dict[str, bool]]: ...
class StrategyEnsemble:
    def __init__(self: Any, strategies: List[Tuple[str, Dict[str, Any]]], rebalance_frequency: int = ...) -> Any: ...
    def update_performance(self: Any, strategy_name: str, score: float) -> None: ...
    def should_rebalance(self: Any) -> bool: ...
    def rebalance_weights(self: Any) -> Dict[str, float]: ...
class SelfEvolvingAdapter:
    def __init__(self: Any, strategies: List[Tuple[str, str, Dict[str, Tuple[float, float]]]], ctx: StrategyContext, prices: pd.DataFrame, evolution_frequency: int = ..., optimization_trials: int = ..., min_history_for_evolution: int = ..., backtest_cfg: Optional[BacktestConfig] = ..., callbacks: Optional[List[EvolutionCallback]] = ...) -> Any: ...
    def generate_trade_intent(self: Any) -> TradeIntent: ...
    def get_evolution_summary(self: Any) -> Dict[str, Any]: ...
    def force_evolution(self: Any, strategy_name: Optional[str] = ...) -> None: ...
class LoggingEvolutionCallback:
    def on_evolution_event(self: Any, event: EvolutionEvent) -> None: ...
class FileEvolutionCallback:
    def __init__(self: Any, filepath: Union[str, Path]) -> Any: ...
    def on_evolution_event(self: Any, event: EvolutionEvent) -> None: ...
def create_evolving_system(price_data: pd.DataFrame) -> SelfEvolvingAdapter: ...
