from typing import Any

LOG: Any
DISABLE_CACHE: Any
DISABLE_NUMBA: Any
def clear_strategy_cache() -> None: ...
class RSIStrategy(PipelineStrategy):
    def __init__(self: Any, rsi_window: int = ..., upper: float = ..., lower: float = ..., neutral_zone: bool = ..., clip: float = ..., zero_on_any_nan: bool = ..., **kwargs: Any) -> None: ...
    def features_plan(self: Any) -> FeaturePlan: ...
    def generate_signal(self: Any, features: pd.DataFrame) -> pd.Series: ...
class MACDStrategy(PipelineStrategy):
    def __init__(self: Any, fast: int = ..., slow: int = ..., signal: int = ..., use_histogram: bool = ..., clip: float = ..., **kwargs: Any) -> None: ...
    def features_plan(self: Any) -> FeaturePlan: ...
    def generate_signal(self: Any, features: pd.DataFrame) -> pd.Series: ...
class BollingerBandsStrategy(PipelineStrategy):
    def __init__(self: Any, period: int = ..., num_std: float = ..., mode: Literal['reversion', 'breakout'] = ..., clip: float = ..., **kwargs: Any) -> None: ...
    def features_plan(self: Any) -> FeaturePlan: ...
    def generate_signal(self: Any, features: pd.DataFrame) -> pd.Series: ...
class MeanReversionStrategy(PipelineStrategy):
    def __init__(self: Any, period: int = ..., entry_threshold: float = ..., exit_threshold: float = ..., clip: float = ..., **kwargs: Any) -> None: ...
    def features_plan(self: Any) -> FeaturePlan: ...
    def generate_signal(self: Any, features: pd.DataFrame) -> pd.Series: ...
class MovingAverageCrossoverStrategy(PipelineStrategy):
    def __init__(self: Any, short: int = ..., long: int = ..., ma_type: Literal['sma', 'ema'] = ..., use_momentum: bool = ..., clip: float = ..., price_col: Optional[str] = ..., **kwargs: Any) -> None: ...
    def features_plan(self: Any) -> FeaturePlan: ...
    def generate_signal(self: Any, features: pd.DataFrame) -> pd.Series: ...
class EnsemblePipelineStrategy(PipelineStrategy):
    ADAPTIVE_UPDATE_INTERVAL: Final[int] = ...
    MAX_FAILURES: Final[int] = ...
    MIN_WEIGHT_FLOOR: Final[float] = ...
    def __init__(self: Any, strategy_specs: List[Tuple[str, dict]], weights: Optional[List[float]] = ..., combination_method: Literal['weighted', 'majority'] = ..., adaptive_weights: bool = ..., performance_window: int = ..., **kwargs: Any) -> None: ...
    def features_plan(self: Any) -> FeaturePlan: ...
    def generate_signal(self: Any, features: pd.DataFrame) -> pd.Series: ...
def create_ensemble(ctx_or_configs: Any, strategy_configs: Optional[List[dict]] = ..., weights: Optional[List[float]] = ..., combination_method: Literal['weighted', 'majority'] = ..., adaptive: bool = ...) -> EnsemblePipelineStrategy: ...
