from typing import Any

"""
Pipeline strategy IR, feature materialization, and strategy registry.

Stages (Programming Guidelines §3.6): specification → ``FeaturePlan`` IR →
materialization (``materialize_features``) → signal / trade intent → downstream
artifacts. Point-in-time and provenance enter through ``StrategyContext.pit_provenance``
(§4.3). The imperative shell coordinates I/O and caching; deterministic transforms
live in the functional core paths behind ``feature_op`` / graph ops (§4.1).

See ``docs/Programming Guidelines.md`` v3.0 for the normative engineering model.
"""

OptunaTrial: Any
LOG: Any
class PipelineError(Exception):
    ...
class ValidationError(PipelineError):
    ...
class MaterializationError(PipelineError):
    ...
class TradeIntent:
    weights: Union[pd.Series, pd.DataFrame] = ...
    raw: Mapping[str, object] = ...
    diagnostics: Mapping[str, object] = ...
SignalOutput: Any
class SignalEnvelope(Protocol):
    def signal(self: Any) -> SignalOutput: ...
StrategySignal: Any
class StrategyContext:
    prices: Union[pd.Series, pd.DataFrame] = ...
    features: Optional[Union[pd.DataFrame, PolarsDataFrame]] = ...
    timestamps: Optional[pd.Index] = ...
    asset_names: Optional[List[str]] = ...
    backend: str = ...
    cache_dir: Union[str, Path] = ...
    random_state: int = ...
    pit_provenance: PitMeta | None = ...
    def validate(self: Any) -> 'StrategyContext': ...
class RegimeDetector(Protocol):
    def gate(self: Any, features: Union[pd.DataFrame, PolarsDataFrame]) -> Union[pd.Series, PolarsSeries, float, int]: ...
class RiskManager(Protocol):
    def clamp(self: Any, weights: Union[pd.Series, pd.DataFrame], prices: Union[pd.Series, pd.DataFrame], **kwargs: Any) -> Union[pd.Series, pd.DataFrame]: ...
class PositionSizer(Protocol):
    def size(self: Any, signal: Union[pd.Series, pd.DataFrame], **kwargs: Any) -> Union[pd.Series, pd.DataFrame]: ...
class FeatureStep:
    op: str = ...
    inputs: Tuple[str, ...] = ...
    args: Tuple[Any, ...] = ...
    kwargs: Mapping[str, Any] = ...
    out: str = ...
FEATURE_OP_REGISTRY_VERSION: Final[str] = ...
def feature_op_registry_version() -> str: ...
class FeaturePlan:
    steps: Tuple[FeatureStep, ...] = ...
    def from_steps(cls: Any, steps: Sequence[FeatureStep]) -> FeaturePlan: ...
    def signature(self: Any) -> str: ...
def feature_op(name: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def op_pct_change(df: Union[pd.DataFrame, PolarsDataFrame], col: str, periods: int = ..., out: Optional[str] = ...) -> Union[pd.DataFrame, PolarsDataFrame]: ...
def op_roll_mean(df: Union[pd.DataFrame, PolarsDataFrame], col: str, window: int, minp: Optional[int] = ..., out: Optional[str] = ...) -> Union[pd.DataFrame, PolarsDataFrame]: ...
def op_roll_std(df: Union[pd.DataFrame, PolarsDataFrame], col: str, window: int, minp: Optional[int] = ..., out: Optional[str] = ...) -> Union[pd.DataFrame, PolarsDataFrame]: ...
def op_ema(df: Union[pd.DataFrame, PolarsDataFrame], col: str, span: int, adjust: bool = ..., out: Optional[str] = ...) -> Union[pd.DataFrame, PolarsDataFrame]: ...
def op_zscore(df: Union[pd.DataFrame, PolarsDataFrame], col: str, window: int, minp: Optional[int] = ..., out: Optional[str] = ...) -> Union[pd.DataFrame, PolarsDataFrame]: ...
def materialize_features(ctx: StrategyContext, plan: FeaturePlan, price_col: Optional[str] = ...) -> Union[pd.DataFrame, PolarsDataFrame]: ...
class StrategySpec:
    name: str = ...
    params: Mapping[str, Any] = ...
class StrategyRegistry:
    def register(cls: Any, name: str, strat_cls: 'type[PipelineStrategy]') -> None: ...
    def get(cls: Any, name: str) -> 'type[PipelineStrategy]': ...
    def clear_for_test(cls: Any) -> None: ...
class PipelineStrategy:
    regime: Optional[RegimeDetector] = ...
    risk: Optional[RiskManager] = ...
    sizer: Optional[PositionSizer] = ...
    def __init__(self: Any, **params: Any) -> None: ...
    def features_plan(self: Any) -> FeaturePlan: ...
    def generate_signal(self: Any, features: Union[pd.DataFrame, PolarsDataFrame]) -> StrategySignal: ...
    def generate_trade_intent(self: Any, ctx: StrategyContext) -> TradeIntent: ...
class BacktestConfig:
    cost_per_unit_turnover: float = ...
    leverage_cap: float = ...
    initial_nav: float = ...
def backtest_portfolio(prices: pd.DataFrame, weights: pd.DataFrame, cfg: BacktestConfig) -> pd.DataFrame: ...
class SweepResult:
    params: Mapping[str, Any] = ...
    score: float = ...
    details: Mapping[str, Any] = ...
def parameter_sweep(strategy_cls: type['PipelineStrategy'], param_grid: Mapping[str, Sequence[Any]], ctx: 'StrategyContext', *, prices: Optional[pd.DataFrame] = ..., backtest_cfg: Optional['BacktestConfig'] = ..., n_jobs: int = ...) -> List['SweepResult']: ...
def optuna_tune(strategy_cls: type['PipelineStrategy'], sampler_spec: Mapping[str, Tuple[float, float]], ctx: 'StrategyContext', *, prices: Optional[pd.DataFrame] = ..., backtest_cfg: Optional['BacktestConfig'] = ..., n_trials: int = ...) -> List['SweepResult']: ...
class DriftState:
    ref_mean: float = ...
    ref_std: float = ...
def detect_drift(series: pd.Series, st: Optional[DriftState], threshold: float = ..., sensitivity: float = ...) -> Tuple[DriftState, bool]: ...
class ChampionChallenger:
    strategy_cls: type[PipelineStrategy] = ...
    ctx: StrategyContext = ...
    prices: pd.DataFrame = ...
    backtest_cfg: BacktestConfig = ...
    champion_params: Dict[str, Any] = ...
    history: List[Tuple[str, Dict[str, Any], float]] = ...
    def evaluate(self: Any, params: Mapping[str, Any]) -> float: ...
    def step(self: Any, challenger_params: Mapping[str, Any], improvement: float = ...) -> Dict[str, Any]: ...
class NullRegime:
    def gate(self: Any, features: Union[pd.DataFrame, PolarsDataFrame]) -> int: ...
class LinearSizer:
    def __init__(self: Any, scale: float = ..., clip: float = ...) -> Any: ...
    def size(self: Any, signal: Union[pd.Series, pd.DataFrame], **_: Any) -> Union[pd.Series, pd.DataFrame]: ...
class TurnoverLimiterRisk:
    def __init__(self: Any, max_turnover: float = ...) -> Any: ...
    def clamp(self: Any, weights: Union[pd.Series, pd.DataFrame], prices: Union[pd.Series, pd.DataFrame], **_: Any) -> Union[pd.Series, pd.DataFrame]: ...
class BlendSpec:
    parts: List[Tuple[float, PipelineStrategy]] = ...
    def normalize(self: Any) -> None: ...
def blend(ctx: StrategyContext, spec: BlendSpec) -> TradeIntent: ...
class LegacyBaseStrategy(PipelineStrategy):
    def __init__(self: Any, legacy_impl: Any, **params: Any) -> None: ...
    def features_plan(self: Any) -> FeaturePlan: ...
    def generate_signal(self: Any, features: Union[pd.DataFrame, PolarsDataFrame]) -> Union[pd.Series, pd.DataFrame]: ...
