from typing import Any

logger: Any
Backend: Any
class PlanSpec:
    ops: List[Dict[str, Any]] = ...
    target: Optional[Dict[str, Any]] = ...
    sequence: Optional[Dict[str, Any]] = ...
    scaling: Optional[Dict[str, Any]] = ...
    meta: Optional[Dict[str, Any]] = ...
def merge_specs(*specs: PlanSpec) -> PlanSpec: ...
class ModelRegistry:
    def register(cls: Any, name: str, obj: Any) -> None: ...
    def get(cls: Any, name: str) -> Any: ...
    def clear(cls: Any) -> None: ...
def resolve_models_in_ops(ops: List[Dict[str, Any]]) -> List[Dict[str, Any]]: ...
class Plan:
    ops: List[str] = ...
    params: Dict[str, List[Dict[str, Any]]] = ...
    group_by: List[str] = ...
    version: str = ...
def get_executor(backend: Backend = ...) -> Any: ...
def run(df: Any, plan: Union[Plan, Dict[str, Any]], *, backend: Backend = ..., optimize: bool | None = ..., pressure: str | None = ..., **_ignored: Any) -> Any: ...
def stream(plan: Plan, *, backend: Backend = ...) -> Any: ...
class PreprocessorBuilder:
    def __init__(self: Any, backend: Backend = ...) -> Any: ...
    def add_op(self: Any, op_symbol: str, **params: Any) -> 'PreprocessorBuilder': ...
    def set_group_by(self: Any, cols: List[str]) -> 'PreprocessorBuilder': ...
    def set_backend(self: Any, backend: Backend) -> 'PreprocessorBuilder': ...
    def from_dict(self: Any, cfg: Dict[str, Any]) -> 'PreprocessorBuilder': ...
    def build_plan(self: Any) -> Plan: ...
    def build_runner(self: Any) -> Callable[[Any], Any]: ...
    def add_dsl_op(self: Any, op_symbol: str, backend_hint: str = ..., **params: Any) -> 'PreprocessorBuilder': ...
    def add_sequence(self: Any, *ops: Union[str, Dict[str, Any]]) -> 'PreprocessorBuilder': ...
    def add_parallel(self: Any, *builders: 'PreprocessorBuilder') -> 'PreprocessorBuilder': ...
    def add_transform(self: Any, transform_name: str, **params: Any) -> 'PreprocessorBuilder': ...
