from typing import Any

"""
Time-series aware train/test splitting with purge and embargo windows.

This module implements Marcos López de Prado's purge and embargo methodology
for preventing information leakage in financial time-series cross-validation.

Purge Window: Gap between train and test sets to remove overlapping observations.
    - Removes training samples whose labels overlap with test period
    - Prevents look-ahead bias from label windows spanning train/test boundary
    - Applies to BOTH walk-forward and k-fold splitters

Embargo Window: Gap after test set where no training data is used.
    - Prevents information from test period leaking into future training folds
    - Only applies to PurgedKFold where training data exists on BOTH sides of test
    - NOT applicable to walk-forward (TimeSeriesSplitter) since train always precedes test

Reference: López de Prado, M. (2018). Advances in Financial Machine Learning.
"""

SPLITS_SCHEMA_VERSION: Any
class SplitBoundary:
    fold_id: int = ...
    train_start: datetime = ...
    train_end: datetime = ...
    test_start: datetime = ...
    test_end: datetime = ...
    train_count: int = ...
    test_count: int = ...
    purged_count: int = ...
    embargoed_count: int = ...
    non_contiguous_train: bool = ...
    def to_dict(self: Any) -> dict: ...
class SplitResult:
    train_df: pl.DataFrame = ...
    test_df: pl.DataFrame = ...
    boundary: SplitBoundary = ...
    def train_indices(self: Any) -> list[int]: ...
    def test_indices(self: Any) -> list[int]: ...
    def assert_no_leakage(self: Any, timestamp_col: str = ..., key_cols: list[str] = ...) -> None: ...
class SplitsManifest:
    schema_version: str = ...
    split_method: str = ...
    timestamp_column: str = ...
    n_splits: int = ...
    purge_window: int = ...
    embargo_window: int = ...
    min_train_size: int = ...
    test_size: int = ...
    total_rows: int = ...
    time_range_start: Optional[str] = ...
    time_range_end: Optional[str] = ...
    splits: list[dict] = ...
    warnings: list[str] = ...
    def to_dict(self: Any) -> dict: ...
    def to_json(self: Any, path: Path) -> None: ...
    def from_json(cls: Any, path: Path) -> 'SplitsManifest': ...
class TimeSeriesSplitter:
    def __init__(self: Any, n_splits: int = ..., test_size: int = ..., min_train_size: int = ..., purge_window_days: int = ..., timestamp_col: str = ...) -> Any: ...
    def split(self: Any, df: pl.DataFrame) -> Iterator[SplitResult]: ...
    def get_manifest(self: Any, df: pl.DataFrame) -> SplitsManifest: ...
class PurgedKFold:
    def __init__(self: Any, n_splits: int = ..., purge_window_days: int = ..., embargo_window_days: int = ..., timestamp_col: str = ...) -> Any: ...
    def split(self: Any, df: pl.DataFrame) -> Iterator[SplitResult]: ...
def validate_no_leakage(train_df: pl.DataFrame, test_df: pl.DataFrame, timestamp_col: str = ..., purge_window_days: int = ..., embargo_window_days: int = ..., key_cols: list[str] = ...) -> dict: ...
def create_splits_manifest(df: pl.DataFrame, splitter: Union[TimeSeriesSplitter, PurgedKFold], output_path: Optional[Path] = ...) -> SplitsManifest: ...
