from typing import Any

"""
Policy loading and gate_policy_hash computation.

Per spec §11.2, gate_policy_hash is computed over:
- Normalized YAML policy text
- Schema hashes for all schema files

This ensures policy hash changes whenever:
- Threshold values change
- Required artifacts change
- Schema files change
- Comparability locks change
"""

class PolicyConfig:
    schema_version: str = ...
    score_policy_version: str = ...
    required_artifacts: dict[str, list[str]] = ...
    comparability: dict[str, list[str]] = ...
    thresholds: dict[str, Any] = ...
    gate_policy_hash: str = ...
    raw_data: dict[str, Any] = ...
def load_policy(policy_path: Path, schemas_dir: Path) -> PolicyConfig: ...
