from typing import Any

F: Any
torch: Any = ...
pl: Any = ...
dd: Any = ...
cudf: Any = ...
cp: Any = ...
NS: Any
def validate_dataframe(df: Any, *, required_cols: Optional[Sequence[str]] = ..., allow_lazy: bool = ...) -> None: ...
def lazy_validate_ohlcv(df: Any) -> bool: ...
def ensure_numeric(df: Any, cols: Iterable[str]) -> None: ...
class SeriesLike(Protocol):
    def is_empty(self: Any) -> bool: ...
    def null_count(self: Any) -> int: ...
    def len(self: Any) -> int: ...
class DataFrameLike(Protocol):
    def is_empty(self: Any) -> bool: ...
    def columns(self: Any) -> List[str]: ...
    def schema(self: Any) -> dict[str, Any]: ...
class TensorLike(Protocol):
    def ndim(self: Any) -> int: ...
    def numel(self: Any) -> int: ...
    def is_floating_point(self: Any) -> bool: ...
    def is_complex(self: Any) -> bool: ...
    def isnan(self: Any) -> 'TensorLike': ...
    def isinf(self: Any) -> 'TensorLike': ...
    def any(self: Any) -> bool: ...
class Validator(ABC):
    def validate(self: Any, data: Any) -> None: ...
def register_validator(data_type: type[Any]) -> Callable[[F], F]: ...
ValidatorCallable: Any
def compose_validators(*validators: ValidatorCallable) -> ValidatorCallable: ...
def all_of(validators: List[ValidatorCallable]) -> ValidatorCallable: ...
def any_of(validators: List[ValidatorCallable]) -> ValidatorCallable: ...
def validate_series(series: Any, name: str = ...) -> None: ...
def validate_ohlcv(df: Any) -> None: ...
def validate_stream_chunk(chunk: Any) -> None: ...
def validate_data_for_training(df: Any) -> None: ...
def validate_symbol(symbol: Any) -> None: ...
def validate_date(date: Any) -> None: ...
def validate_tensor(tensor: Any, *, ndim: Optional[int] = ..., min_dims: Optional[int] = ..., name: str = ...) -> None: ...
class CustomSeriesValidator(Validator):
    def __init__(self: Any, min_length: int = ...) -> Any: ...
    def validate(self: Any, data: pd.Series) -> None: ...
def validate_file_data(data: Any, format: str) -> None: ...
