from typing import Any

"""
Combinatorial Purged Cross-Validation (CPCV).

Generates all C(N, k) train/test splits from N groups, with purging and
embargo applied at each split boundary to prevent leakage.

Distinct from py/preprocessor/splits.py (which handles ML train/test
purge/embargo). This module is for combinatorial backtest validation —
evaluating every possible combination of train/test paths so that
performance distribution is computed over all paths, not just one.

Reference:
    López de Prado (2018) "Advances in Financial Machine Learning",
    Chapter 12 — Combinatorial Purged Cross-Validation.
"""

LOG: Any
pl: Any
class CPCVError(BaseError):
    ...
class CPCVDataError(CPCVError):
    ...
class CPCVSplit:
    split_index: int = ...
    train_indices: np.ndarray = ...
    test_indices: np.ndarray = ...
    test_group_ids: List[int] = ...
    n_train: int = ...
    n_test: int = ...
class CPCVConfig:
    n_splits: int = ...
    n_test_splits: int = ...
    purge_periods: int = ...
    embargo_periods: int = ...
    min_train_size: int = ...
    def n_combinations(self: Any) -> int: ...
class CPCVSplitter:
    def __init__(self: Any, config: Optional[CPCVConfig] = ...) -> None: ...
    def split(self: Any, data: Any, *, return_splits_only: bool = ...) -> Generator[CPCVSplit, None, None]: ...
    def n_splits_total(self: Any, n_obs: int) -> int: ...
def cpcv_splits(data: Any, n_splits: int = ..., n_test_splits: int = ..., purge_periods: int = ..., embargo_periods: int = ..., min_train_size: int = ...) -> List[CPCVSplit]: ...
