from typing import Any

"""
py/backtesting/validation/statistical/min_trl.py

Standalone public API for the Minimum Track Record Length (minTRL)
calculation.  The core formula lives in dsr.py; this module re-exports
it under a stable name and adds a typed result wrapper so callers can
rely on attribute access rather than dict key lookups.

Reference: Bailey & López de Prado (2014), equation (13).
"""

class MinTRLResult:
    years_needed: float = ...
    years_available: float = ...
    observed_sr: float = ...
    target_confidence: float = ...
    gate_result: str = ...
    def from_dict(cls: Any, d: dict[str, Any]) -> MinTRLResult: ...
def compute_min_trl(returns: Any, *, target_confidence: float = ..., benchmark_sr: float = ..., periods_per_year: int = ...) -> MinTRLResult: ...
