from typing import Any

class PBOError(Exception):
    ...
class PBODataError(PBOError):
    ...
class PBOComputationError(PBOError):
    ...
class PBOConfig:
    warn_threshold: float = ...
    fail_threshold: float = ...
    min_trials: int = ...
    min_paths: int = ...
    include_diagnostics: bool = ...
    score_basis: str = ...
    def validate(self: Any) -> None: ...
def compute_pbo_from_matrices(in_sample_scores: Any, out_of_sample_scores: Any, *, config: PBOConfig | None = ..., score_higher_is_better: bool = ...) -> dict[str, Any]: ...
def compute_pbo_from_records(records: Any, *, config: PBOConfig | None = ..., score_higher_is_better: bool = ...) -> dict[str, Any]: ...
def compute_pbo_from_path_pairs(path_pairs: Any, *, config: PBOConfig | None = ..., score_higher_is_better: bool = ...) -> dict[str, Any]: ...
def compute_pbo(data: Any, *, mode: str = ..., config: PBOConfig | None = ..., score_higher_is_better: bool = ..., out_of_sample_scores: Any | None = ...) -> dict[str, Any]: ...
