from typing import Any

"""
Approvals: record and enforce human-in-the-loop gates before promotion.
"""

class ApprovalRecord:
    job_id: str = ...
    candidate_id: str = ...
    approved: bool = ...
    approver_id: str = ...
    approved_at: datetime = ...
    notes: str = ...
def require_approval(job_id: str, candidate_id: str, context: dict[str, object]) -> ApprovalRecord: ...
