from typing import Any

"""
CandidateStore: atomic persistence for in-flight candidate trial results.
"""

class CandidateStore:
    def __init__(self: Any) -> None: ...
    def save(self: Any, candidate_id: str, result: dict[str, Any]) -> None: ...
    def load(self: Any, candidate_id: str) -> dict[str, Any] | None: ...
    def all_ids(self: Any) -> list[str]: ...
