from typing import Any

pl: Any = ...
mlflow: _MlflowLike | Any = ...
class StatisticalComputationError(StatisticalTestError):
    ...
class StatisticalDataError(StatisticalTestError):
    ...
class StatisticalBackendError(StatisticalTestError):
    ...
def register_test(name: str | None = ...) -> Callable[[type[StatTest]], type[StatTest]]: ...
class StatTest(ABC):
    def run(self: Any, data: Any, **kwargs: Any) -> dict[str, Any]: ...
class StatTestFactory:
    def get_test(cls: Any, test_name: str) -> StatTest: ...
    def run_test(cls: Any, test_name: str, data: Any, **kwargs: Any) -> dict[str, Any]: ...
class GrangercausalityTest(StatTest):
    def run(self: Any, data: Any, *, maxlag: int | str = ..., significance_level: float = ..., verbose: bool = ..., **_: Any) -> dict[str, Any]: ...
class JohansencointegrationTest(StatTest):
    def run(self: Any, data: Any, *, det_order: int = ..., k_ar_diff: int | str = ..., significance_level: float = ..., **_: Any) -> dict[str, Any]: ...
class AdfTest(StatTest):
    def run(self: Any, data: Any, *, significance_level: float = ..., regression: str = ..., autolag: str | None = ..., maxlag: int | None = ..., **_: Any) -> dict[str, Any]: ...
class KpssTest(StatTest):
    def run(self: Any, data: Any, *, significance_level: float = ..., nlags: int | str = ..., regression: str = ..., **_: Any) -> dict[str, Any]: ...
class LjungboxTest(StatTest):
    def run(self: Any, data: Any, *, lags: int | Sequence[int] | str | None = ..., significance_level: float = ..., model_df: int = ..., **_: Any) -> dict[str, Any]: ...
def run_tests(tests: list[str | Mapping[str, Any]], data: Any, parallel: bool = ..., max_workers: int | None = ...) -> dict[str, dict[str, Any]]: ...
def adf_test(series: Any, **kwargs: Any) -> dict[str, Any]: ...
def kpss_test(series: Any, **kwargs: Any) -> dict[str, Any]: ...
def ljung_box_test(series: Any, **kwargs: Any) -> dict[str, Any]: ...
def granger_causality_test(x: Any, y: Any, **kwargs: Any) -> dict[str, Any]: ...
def johansen_cointegration_test(data: Any, **kwargs: Any) -> dict[str, Any]: ...
