from typing import Any

class ParityLanguageResult:
    language: str = ...
    success: bool = ...
    suites: tuple[str, ...] = ...
    toolchain: str = ...
    details: dict[str, Any] = ...
def build_matrix_report(results: list[ParityLanguageResult]) -> dict[str, Any]: ...
def build_python_language_result() -> ParityLanguageResult: ...
def build_language_report(result: ParityLanguageResult) -> dict[str, Any]: ...
def load_language_report(path: Path) -> ParityLanguageResult: ...
def aggregate_report_paths(paths: list[Path]) -> dict[str, Any]: ...
def main() -> int: ...
