from typing import Any

ADR007_SUITES: tuple[str, ...] = ...
class ReplayResult:
    suite: str = ...
    case_id: str = ...
    expected_output: str = ...
    actual_output: str = ...
    def success(self: Any) -> bool: ...
def python_toolchain() -> str: ...
def case_by_id(suite: str, case_id: str) -> GoldenCase: ...
def expected_output_for_case(suite: str, case: GoldenCase) -> str: ...
def replay_case(suite: str, case: GoldenCase) -> str: ...
def replay_suite(suite: str) -> tuple[ReplayResult, ...]: ...
def replay_all_suites() -> tuple[ReplayResult, ...]: ...
def replay_summary() -> dict[str, Any]: ...
