from typing import Any

class CanonicalFrameCIStatus(str, Enum):
    UNCERTIFIED: Any
    PYTHON_ONLY_D2: Any
    CROSSLANG_D2_CERTIFIED: Any
    CROSSLANG_D3_CERTIFIED: Any
class CanonicalFrameCIEvidence:
    python_certified: bool = ...
    golden_vectors_present: bool = ...
    cross_language_certified: bool = ...
    d3_primitives_promoted: tuple[str, ...] = ...
    notes: tuple[str, ...] = ...
    def status(self: Any) -> CanonicalFrameCIStatus: ...
    def to_dict(self: Any) -> dict[str, object]: ...
def load_canonical_frame_ci_evidence(path: Path | None = ...) -> CanonicalFrameCIEvidence: ...
CANONICAL_FRAME_CI_EVIDENCE: Any
CANONICAL_FRAME_CI_STATUS: Any
CANONICAL_FRAME_CI_STATUS_VALUE: Any
CANONICAL_FRAME_CI_EVIDENCE_DICT: Any
