from typing import Any

"""
py/ops/hashing/canonicalizer.py
════════════════════════════════════
Pre-hash canonicalization pipeline (ADR-007 v1.1 §3).

ALL canonicalization MUST occur before bytes are passed to any hash function.
No hash function in this system has knowledge of the data type being hashed.
The canonicalizer is the only place where data-type semantics are applied.

MODULE INVARIANTS (all must hold for every public method output)
  CANONICAL_UTF8        : strings → strict UTF-8, no BOM, no null terminator
  CANONICAL_BIG_ENDIAN  : all multi-byte integers and floats → big-endian
  IEEE754_NORMALIZED    : NaN → canonical quiet NaN, -0.0 → +0.0, ±Inf REJECTED
  NO_RUNTIME_LAYOUT_DEP : Arrow IPC, pickle, pandas internal repr → all BANNED

FLOAT ENCODING CONSTANTS
  FLOAT64_QUIET_NAN_BE : b'\x7f\xf8\x00\x00\x00\x00\x00\x00'
  FLOAT32_QUIET_NAN_BE : b'\x7f\xc0\x00\x00'
  FLOAT64_POS_ZERO_BE  : b'\x00\x00\x00\x00\x00\x00\x00\x00'
  FLOAT32_POS_ZERO_BE  : b'\x00\x00\x00\x00'

BANNED OPERATIONS (raise HashContractViolation if detected)
  - Passing bytes with native-endian representation
  - Passing Arrow IPC bytes
  - Hashing a pandas/polars object without going through canonicalize_dataframe()
  - Any float operation that flushes subnormals (caller must ensure no FTZ/DAZ)
"""

FLOAT64_QUIET_NAN_BE: bytes = ...
FLOAT32_QUIET_NAN_BE: bytes = ...
FLOAT64_POS_ZERO_BE: bytes = ...
FLOAT32_POS_ZERO_BE: bytes = ...
class Canonicalizer:
    def encode_string(self: Any, s: str) -> bytes: ...
    def encode_u64be(self: Any, n: int) -> bytes: ...
    def encode_u32be(self: Any, n: int) -> bytes: ...
    def encode_i16be(self: Any, n: int) -> bytes: ...
    def encode_i64be(self: Any, n: int) -> bytes: ...
    def normalize_float64(self: Any, v: float, *, tier: PersistenceTier = ...) -> bytes: ...
    def normalize_float64_array(self: Any, arr: np.ndarray, *, tier: PersistenceTier = ...) -> bytes: ...
    def canonicalize_json(self: Any, obj: Any) -> bytes: ...
    def canonicalize_dataframe(self: Any, df: 'pd.DataFrame', *, sort_key: list[str], namespace: str = ..., tier: PersistenceTier = ...) -> bytes: ...
    def build_composite_preimage(self: Any, namespace: str, *fields: bytes) -> bytes: ...
def canonicalize_json_bytes(obj: Any) -> bytes: ...
CANON: Canonicalizer = ...
