from typing import Any

"""
py/ops/hashing/envelope.py
══════════════════════════════
HashRef envelope: the mandatory wrapper for every persistent hash output.

ADR-007 v1.1 §6.1 — HashRef Envelope Schema
  Bare hex digests are BANNED in all persistent contexts.  Every hash that
  crosses a process boundary, enters a log, is written to disk, or is used
  for cross-session comparison MUST be represented as a HashRef.

FIELD CONTRACT
  domain               : e.g. "cas.v1", "attest.v1", "cache.v1"
  algo                 : AlgoId string, e.g. "b3-256", "jcs-sha256"
  algo_version         : pinned implementation version string
  purpose              : HashPurpose enum name as str (for logging / audit)
  canonicalizer_id     : "mm-canon" (locked)
  canonicalizer_version: "1.0" (locked at this revision)
  key_id               : UUID of the SipHash / HMAC key used; None for keyless
  digest               : hex-encoded, big-endian canonical bytes

KEY_ID SEMANTICS
  For keyed hash surfaces (SipHash-2-4, HMAC-SHA256), key_id is a
  non-nullable opaque UUID string.  Two HashRefs with the same digest but
  different key_ids MUST be treated as a hard REJECT, never a match.
"""

class HashRef:
    domain: str = ...
    algo: str = ...
    digest: str = ...
    purpose: str = ...
    algo_version: str = ...
    canonicalizer_id: str = ...
    canonicalizer_version: str = ...
    key_id: Optional[str] = ...
    def to_id_string(self: Any) -> str: ...
    def hex_digest(self: Any) -> str: ...
    def equality_check(self: Any, other: 'HashRef') -> bool: ...
    def to_dict(self: Any) -> dict[str, str | None]: ...
    def to_json(self: Any, *, indent: int | None = ...) -> str: ...
    def from_dict(cls: Any, data: dict[str, object]) -> 'HashRef': ...
    def from_json(cls: Any, s: str) -> 'HashRef': ...
    def parse(cls: Any, value: str) -> 'HashRef': ...
def make_cas_ref(digest_hex: str) -> HashRef: ...
def make_attest_ref(digest_hex: str) -> HashRef: ...
def make_merkle_ref(digest_hex: str) -> HashRef: ...
def make_cache_ref(digest_hex: str, *, purpose: HashPurpose, namespace: str = ...) -> HashRef: ...
def make_siphash_ref(digest_hex: str, *, purpose: HashPurpose, key_id: str) -> HashRef: ...
def make_hmac_ref(digest_hex: str, *, key_id: str) -> HashRef: ...
