from typing import Any

class EqualityEvidence:
    payload_bytes: bytes | None = ...
    aux_check: bytes | None = ...
    payload_length: int | None = ...
def requires_equality_fallback(purpose: HashPurpose) -> bool: ...
def assert_ref_compatibility(stored_ref: HashRef, observed_ref: HashRef) -> None: ...
def verify_payload_equality(stored_payload: bytes, observed_payload: bytes) -> bool: ...
def verify_aux_check(stored_aux_check: bytes, observed_aux_check: bytes) -> bool: ...
def verify_cache_hit(*, purpose: HashPurpose, stored_ref: HashRef, observed_ref: HashRef, stored_evidence: EqualityEvidence | None = ..., observed_evidence: EqualityEvidence | None = ...) -> bool: ...
def validate_evidence_policy(purpose: HashPurpose, persistence_tier: PersistenceTier, evidence: EqualityEvidence | None) -> None: ...
