from typing import Any

PREIMAGE_NAMESPACE_ENCODING: Final[str] = ...
PREIMAGE_LENGTH_BYTES: Final[int] = ...
class PreimagePart:
    payload: bytes = ...
    label: str | None = ...
class CompositePreimage:
    purpose: HashPurpose = ...
    namespace: str = ...
    encoded: bytes = ...
    part_count: int = ...
def assert_preimage_invariant_enabled() -> None: ...
def make_part(payload: bytes, *, label: str | None = ...) -> PreimagePart: ...
def encode_namespace(namespace: str) -> bytes: ...
def encode_length_prefix(length: int) -> bytes: ...
def build_composite_preimage(namespace: str, *parts: bytes) -> bytes: ...
def compose_for_purpose(purpose: HashPurpose, namespace: str, *parts: bytes) -> CompositePreimage: ...
