from typing import Any

"""
Risk domain service.

Typed contract for risk measurement and limit validation.
Integrates with portfolio service for exposure calculation.
"""

class RiskMetrics:
    var_95: Decimal = ...
    cvar_95: Decimal = ...
    max_drawdown: Decimal = ...
    beta: Decimal = ...
    volatility: Decimal = ...
class RiskLimit:
    metric: str = ...
    threshold: Decimal = ...
    hard: bool = ...
class RiskService(ABC):
    def calculate(self: Any, portfolio: PortfolioSnapshot, *, lookback: pd.Timedelta | None = ...) -> RiskMetrics: ...
    def validate_limits(self: Any, portfolio: PortfolioSnapshot, limits: Sequence[RiskLimit], *, as_of: pd.Timestamp | None = ...) -> Mapping[str, bool]: ...
    def exposure(self: Any, portfolio: PortfolioSnapshot, *, by_sector: bool = ..., by_factor: bool = ...) -> pd.DataFrame: ...
