from typing import Any

"""
Task-validity diagnostic for governed run bundles.
"""

DIAGNOSTIC_VERSION: Any
TASK_VALIDITY_INPUTS: Any
SCHEMA_RELATIVE_PATH: Any
JsonScalar: TypeAlias = ...
JsonValue: TypeAlias = ...
JsonObject: TypeAlias = ...
class TaskValidityCheck:
    check_id: str = ...
    check_name: str = ...
    passed: bool = ...
    evidence: JsonObject = ...
    def to_json_dict(self: Any) -> JsonObject: ...
class TaskValidityReport:
    bundle_hash: str = ...
    checks: tuple[TaskValidityCheck, ...] = ...
    all_pass: bool = ...
    diagnostic_version: str = ...
    timestamp: str = ...
    def to_json_dict(self: Any) -> JsonObject: ...
def validate_task(bundle_path: Path) -> TaskValidityReport: ...
def check_task_non_exchangeability(bundle_path: Path) -> TaskValidityCheck: ...
def check_leakage_geometry(bundle_path: Path) -> TaskValidityCheck: ...
def check_episode_construction_validity(bundle_path: Path) -> TaskValidityCheck: ...
