from typing import Any

def set_logging_level(level: Literal['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']) -> None: ...
def set_perf_flags(precision_flags: Optional[Dict[str, Union[bool, str]]] = ...) -> None: ...
def seed_everything(seed: int = ..., *, deterministic: bool = ..., warn_only: bool = ..., precision_flags: Optional[Dict[str, Union[bool, str]]] = ..., return_generator: bool = ...) -> Optional[torch.Generator]: ...
def init_weights(module: nn.Module, mode: Literal['xavier_uniform', 'xavier_normal', 'kaiming_uniform', 'kaiming_normal', 'orthogonal', 'trunc_normal'] = ..., generator: Optional[torch.Generator] = ...) -> None: ...
def get_device(preferred_idx: Optional[int] = ...) -> torch.device: ...
def autocast(enabled: bool = ..., dtype: torch.dtype = ..., device_type: Optional[Literal['cuda', 'cpu', 'mps']] = ...) -> Iterator[None]: ...
