from typing import Any

"""
Backtesting public API.

Typed contracts for backtest execution, result retrieval,
and analysis with deterministic outcomes and artifact tracking.
"""

class BacktestSpec:
    strategy_id: str = ...
    start_date: str = ...
    end_date: str = ...
    initial_capital: Decimal = ...
    config_overrides: Mapping[str, Any] | None = ...
class BacktestResult:
    spec: BacktestSpec = ...
    equity_curve: pd.Series = ...
    trades: pd.DataFrame = ...
    metrics: Mapping[str, float] = ...
    artifact_path: Path = ...
class BacktestAPI(ABC):
    def run(self: Any, spec: BacktestSpec) -> BacktestResult: ...
    def load(self: Any, run_id: str) -> BacktestResult: ...
    def compare(self: Any, results: Sequence[BacktestResult], *, benchmark: str | None = ...) -> pd.DataFrame: ...
