from typing import Any

"""
Simple backtest engine - SMA crossover strategy.
"""

class BacktestResult:
    total_return: float = ...
    sharpe_ratio: float = ...
    max_drawdown: float = ...
    win_rate: float = ...
    num_trades: int = ...
    def to_dict(self: Any) -> dict: ...
def add_signals(df: pl.DataFrame, fast_col: str, slow_col: str) -> pl.DataFrame: ...
def add_strategy_returns(df: pl.DataFrame) -> pl.DataFrame: ...
def compute_metrics(df: pl.DataFrame) -> BacktestResult: ...
def run_backtest(df: pl.DataFrame, fast_sma: int = ..., slow_sma: int = ...) -> BacktestResult: ...
