from typing import Any

"""
Portfolio domain service.

Typed contract for portfolio construction and rebalancing operations.
Integrates with risk service for constraint validation.
"""

class Position:
    symbol: str = ...
    quantity: Decimal = ...
    entry_price: Decimal = ...
class PortfolioSnapshot:
    timestamp: pd.Timestamp = ...
    positions: Mapping[str, Position] = ...
    cash: Decimal = ...
    base_currency: str = ...
class ConstraintValidator(Protocol):
    def validate(self: Any, snapshot: PortfolioSnapshot, proposed: Mapping[str, Decimal]) -> bool: ...
class PortfolioService(ABC):
    def construct(self: Any, signals: pd.DataFrame, capital: Decimal, *, as_of: pd.Timestamp | None = ...) -> PortfolioSnapshot: ...
    def rebalance(self: Any, current: PortfolioSnapshot, target_weights: Mapping[str, Decimal], *, constraints: Sequence[ConstraintValidator] | None = ...) -> PortfolioSnapshot: ...
