from typing import Any

"""
Determinism tier checks: enforce that IR objects carry a valid determinism marker.
"""

VALID_TIERS: frozenset[str] = ...
class DeterminismViolationError(ValueError):
    ...
def validate_tier(meta: IRMetadata) -> IRMetadata: ...
def assert_tier_not_downgraded(current: Literal['d0', 'd1', 'd2', 'd3'], proposed: Literal['d0', 'd1', 'd2', 'd3']) -> None: ...
