from typing import Any

"""
Point-in-time (PIT) boundary checks: ensure no future data leaks into training windows.
"""

class PITViolationError(ValueError):
    ...
def validate_fold_pit(fold: FoldBoundary, as_of: datetime) -> FoldBoundary: ...
def validate_no_leakage(fold: FoldBoundary) -> FoldBoundary: ...
def validate_task_pit(task_ir: TaskIR, as_of: datetime) -> TaskIR: ...
