from typing import Any

"""
Parses broker-specific configs from pipeline_config.yaml.
"""

logger: Any
class BrokerConfig(BaseModel):
    host: str = ...
    port: int = ...
    client_id: int = ...
    account: Optional[str] = ...
    timeout: float = ...
    retries: int = ...
    def validate_port(cls: Any, v: int) -> int: ...
    def validate_account(cls: Any, v: Optional[str]) -> Optional[str]: ...
def load_broker_config(config_path: str = ..., section: str = ...) -> BrokerConfig: ...
