from typing import Any

"""
Provides shared utilities (retry, normalization, logging).
"""

def retry_async(retries: int = ..., backoff_factor: float = ..., exceptions: tuple[type[BaseException], ...] = ..., jitter: float = ...) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def normalize_dataframe(df: Any, schema: Optional[dict[str, pl.DataType]] = ..., engine: str = ...) -> pl.DataFrame: ...
def ensure_lazy(df: Any, *, schema: Optional[dict[str, pl.DataType]] = ...) -> pl.LazyFrame: ...
def setup_logger(name: str, level: int = ..., fmt: str = ...) -> logging.Logger: ...
