from typing import Any

class BacktestSuiteRunner:
    config: dict[str, Any] = ...
    def execute(self: Any, suite_plan: BacktestSuitePlan) -> RunBundleRef: ...
    def run(self: Any, *args: Any, **kwargs: Any) -> RunBundleRef: ...
