from typing import Any

T: Any
class HashAlgorithm(Enum):
    XXHASH: Any
    BLAKE3: Any
    SIPHASH: Any
    SHA256: Any
def hash_bytes(data: bytes, algo: HashAlgorithm = ...) -> str: ...
def hash_config(cfg_obj: Any, algo: HashAlgorithm = ...) -> str: ...
def hash_dataframe_deterministic(df: Any, cols: Any = ..., algo: HashAlgorithm = ...) -> str: ...
def versioned_key(*parts: str, version: str = ...) -> str: ...
class CompressionLevel(Enum):
    NONE: Any
    FAST: Any
    HIGH: Any
class CompressionStrategy:
    small_threshold: int = ...
    fast_threshold: int = ...
    def compress(self: Any, data: bytes, level: CompressionLevel = ...) -> Tuple[bytes, CompressionLevel]: ...
    def decompress(self: Any, data: bytes, level: CompressionLevel) -> bytes: ...
class CacheEntry:
    value: Any = ...
    expiry: float = ...
    version: int = ...
    access_count: int = ...
    last_access: float = ...
    compression: CompressionLevel = ...
class CacheMetrics:
    hits: int = ...
    misses: int = ...
    evictions: int = ...
    sets: int = ...
    total_latency_ns: int = ...
    def hit_rate(self: Any) -> float: ...
    def avg_latency_us(self: Any) -> float: ...
class AdaptiveTTLManager:
    def __init__(self: Any, base_ttl: float = ...) -> Any: ...
    def get_ttl(self: Any, key: Any, volatility: float = ...) -> float: ...
    def update_volatility(self: Any, volatility: float) -> Any: ...
class EnhancedCacheManager:
    def __init__(self: Any, max_size: int = ..., ttl: Optional[float] = ..., eviction_policy: str = ..., enable_compression: bool = ..., enable_metrics: bool = ...) -> Any: ...
    def get(self: Any, key: Any, version: int = ...) -> Optional[Any]: ...
    def set(self: Any, key: Any, value: Any, ttl: Optional[float] = ..., version: int = ..., volatility: float = ...) -> Any: ...
    def invalidate(self: Any, key: Any) -> Any: ...
    def invalidate_pattern(self: Any, prefix: str) -> Any: ...
    async def get_async(self: Any, key: Any, version: int = ...) -> Optional[Any]: ...
    async def set_async(self: Any, key: Any, value: Any, **kwargs: Any) -> Any: ...
class DistributedCacheCoordinator:
    CAS_SCRIPT: Any
    def __init__(self: Any, redis_client: Any = ...) -> Any: ...
    async def cas_update(self: Any, key: str, value: Any, timestamp: float) -> bool: ...
    async def invalidate_broadcast(self: Any, channel: str, key: str) -> None: ...
def enhanced_cache(max_size: int = ..., ttl: Optional[float] = ..., key_fn: Optional[Callable] = ..., version: str = ..., enable_metrics: bool = ...) -> Any: ...
class PersistentCache:
    def __init__(self: Any, cache_dir: str = ..., enable_compression: bool = ...) -> Any: ...
    def exists(self: Any, key: str) -> bool: ...
    def save_df(self: Any, key: str, df: Any, version: str = ...) -> Any: ...
    def load_df(self: Any, key: str, expected_version: Optional[str] = ...) -> Any: ...
    def invalidate(self: Any, key: str) -> Any: ...
