from typing import Any

class MultiTierCacheAdapter:
    def __init__(self: Any, client: MultiTierClient) -> Any: ...
    def exists(self: Any, key: str) -> bool: ...
    def save_npz(self: Any, key: str, data: Any) -> None: ...
    def load_npz(self: Any, key: str) -> Optional[Any]: ...
    def save_json(self: Any, key: str, data: Any) -> None: ...
    def load_json(self: Any, key: str) -> Optional[Any]: ...
    def save_df(self: Any, key: str, df: Any, **kwargs: Any) -> None: ...
    def load_df(self: Any, key: str, **kwargs: Any) -> Optional[Any]: ...
