from typing import Any

psutil: Any
pynvml: Any
def maybe_mem_info(_ctx: Any = ...) -> Dict[str, Any]: ...
def resolve_workers(val: Union[int, str]) -> int: ...
def call_with_timeout(fn: Callable[[], Any], timeout_s: Optional[int]) -> Any: ...
def stage_with_guard(name: str, fn: Callable[[], Any], *, timeout_s: Optional[int] = ..., run_cfg: Mapping[str, Any], run_id: Optional[str], metrics: Dict[str, Any], logger: Any, ConfigError: type, DataPrepError: type, get_metrics_fn: Callable) -> Any: ...
def adaptive_map(fn: Callable, items: Iterator[Any], kind: str = ..., max_workers: int = ...) -> Iterator[Any]: ...
