from typing import Any

"""
Hashing Contract - Single Source of Truth

This module is the ONLY place where content hashing logic should live.
All other modules must import from here.

See: docs/decisions/hashing_contract.md for rationale and rules.
"""

class HashingContractViolation(Exception):
    ...
class HashRef:
    domain: str = ...
    algo: str = ...
    hex_digest: str = ...
    def parse(cls: Any, value: str) -> 'HashRef': ...
def to_gate_content_hash(attest: HashRef) -> str: ...
class QuantizationPolicy(str, Enum):
    Q_NONE: Any
    Q_ROUND8: Any
    Q_ROUND6: Any
    Q_INT: Any
HASH_EXCLUSIONS: Final[frozenset[str]] = ...
class CodeIdentity:
    commit_sha: str = ...
    is_dirty: bool = ...
    dirty_patch_hash: bytes | None = ...
    def to_hash_input(self: Any) -> bytes: ...
class DataManifestEntry:
    symbol: str = ...
    date_start: date = ...
    date_end: date = ...
    vendor: str = ...
    vendor_snapshot_id: str | None = ...
    schema_version: str = ...
class DataManifest:
    entries: tuple[DataManifestEntry, ...] = ...
class HashingContract:
    def hash_for_identity(data: bytes) -> bytes: ...
    def hash_for_dedup(data: bytes) -> bytes: ...
    def hash_sha256(data: bytes) -> bytes: ...
    def format_float(cls: Any, value: float, policy: QuantizationPolicy) -> str: ...
    def check_banned_values(cls: Any, obj: Any, path: str = ...) -> None: ...
    def strip_exclusions(cls: Any, obj: dict[str, Any]) -> dict[str, Any]: ...
    def apply_quantization(cls: Any, obj: dict[str, Any], policies: dict[str, QuantizationPolicy]) -> dict[str, Any]: ...
    def canonicalize_json(cls: Any, obj: dict[str, Any]) -> str: ...
    def compute_content_hash(cls: Any, artifact: dict[str, Any], quantization_policies: dict[str, QuantizationPolicy] | None = ...) -> bytes: ...
    def compute_plan_hash(cls: Any, strategy_id: str, hyperparams: dict[str, Any], feature_config: dict[str, Any], code_hash: bytes, env_hash: bytes, data_version_hash: bytes, hyperparam_policies: dict[str, QuantizationPolicy] | None = ...) -> bytes: ...
    def get_code_identity(cls: Any) -> CodeIdentity: ...
    def compute_env_hash(cls: Any, lockfile_hash: bytes, cuda_version: str | None = ..., cudnn_version: str | None = ..., tensorrt_version: str | None = ..., blas_backend: str | None = ..., blas_version: str | None = ...) -> bytes: ...
    def compute_data_version_hash(cls: Any, manifest: DataManifest) -> bytes: ...
hash_for_identity: Any
hash_for_dedup: Any
compute_content_hash: Any
compute_plan_hash: Any
get_code_identity: Any
compute_env_hash: Any
compute_data_version_hash: Any
