from typing import Any

HAVE_INFLUX: Any
REDACT_KEYS_DEFAULT: Any
class RedactFilter(logging.Filter):
    def __init__(self: Any, keys: Iterable[str] = ...) -> Any: ...
    def filter(self: Any, record: logging.LogRecord) -> bool: ...
def redact_processor(_: Any, __: Any, event_dict: Dict[str, Any]) -> Dict[str, Any]: ...
def redact_sensitive_info(keys: Iterable[str]) -> Any: ...
def timestamp_processor(_: Any, __: Any, event_dict: Dict[str, Any]) -> Dict[str, Any]: ...
def safe_filter_by_level(logger: Optional[logging.Logger], level: str, event_dict: Dict[str, Any]) -> Dict[str, Any]: ...
class JSONFormatter(logging.Formatter):
    def format(self: Any, record: logging.LogRecord) -> str: ...
class KVFormatter(logging.Formatter):
    def format(self: Any, record: logging.LogRecord) -> str: ...
class LogRecorder:
    def __init__(self: Any, logger_name: Optional[str] = ...) -> Any: ...
    def has_message(self: Any, substring: str, level: Optional[int] = ...) -> bool: ...
class BoundLogger(_BaseBoundLogger):
    def __init__(self: Any, logger: logging.Logger, processors: Optional[list] = ..., context: Optional[Dict[str, Any]] = ...) -> Any: ...
    def name(self: Any) -> str: ...
    def setLevel(self: Any, level: Any) -> None: ...
    def bind(self: Any, **context: Any) -> 'BoundLogger': ...
    def debug(self: Any, msg: str, *a: Any, **k: Any) -> None: ...
    def info(self: Any, msg: str, *a: Any, **k: Any) -> None: ...
    def warning(self: Any, msg: str, *a: Any, **k: Any) -> None: ...
    def error(self: Any, msg: str, *a: Any, **k: Any) -> None: ...
    def critical(self: Any, msg: str, *a: Any, **k: Any) -> None: ...
    def exception(self: Any, msg: str, *a: Any, **k: Any) -> None: ...
    def DEBUG(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def INFO(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def WARNING(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def ERROR(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def CRITICAL(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def EXCEPTION(self: Any, *args: Any, **kwargs: Any) -> None: ...
def build_console_handler(cfg: Mapping[str, Any]) -> logging.Handler: ...
def build_file_handler(cfg: Mapping[str, Any]) -> logging.Handler: ...
def build_syslog_handler(cfg: Mapping[str, Any]) -> logging.Handler: ...
def build_http_handler(cfg: Mapping[str, Any]) -> logging.Handler: ...
def build_influx_handler(cfg: Mapping[str, Any]) -> logging.Handler: ...
def configure_logger(config: Optional[Union[dict, str]] = ..., **legacy_kwargs: Any) -> Optional[BoundLogger]: ...
def get_logger(name: Optional[str] = ...) -> BoundLogger: ...
def log_drift_warning(*args: Any, **kwargs: Any) -> None: ...
class InfluxDBHandler(logging.Handler):
    def __init__(self: Any, client: Optional[Any], bucket: str, org: str) -> Any: ...
    def emit(self: Any, record: logging.LogRecord) -> None: ...
    def handleError(self: Any, record: logging.LogRecord) -> None: ...
