from typing import Any

"""
Multi-tier caching client with L1→L2→L3→L4 read-through and write-back.
Implements singleflight, TTL jitter, and distributed coordination.
"""

redis: Any
REDIS_AVAILABLE: Any
T: Any
def version_to_int(version_str: str) -> int: ...
class Call:
    future: Union[Future, asyncio.Future] = ...
    start_time: float = ...
    is_async: bool = ...
class Singleflight:
    def __init__(self: Any) -> Any: ...
    def do(self: Any, key: Any, fn: Callable[[], T]) -> Tuple[T, bool]: ...
    async def do_async(self: Any, key: Any, fn: Callable) -> Tuple[T, bool]: ...
class L2Cache:
    def get(self: Any, key: str) -> Optional[Any]: ...
    def set(self: Any, key: str, value: Any, ttl: Optional[float] = ...) -> Any: ...
    def invalidate(self: Any, key: str) -> Any: ...
class PlasmaL2Cache(L2Cache):
    def __init__(self: Any, plasma_path: str = ...) -> Any: ...
    def get(self: Any, key: str) -> Optional[Any]: ...
    def set(self: Any, key: str, value: Any, ttl: Optional[float] = ...) -> Any: ...
    def invalidate(self: Any, key: str) -> Any: ...
class MemfdL2Cache(L2Cache):
    def __init__(self: Any, cache_dir: str = ...) -> Any: ...
    def get(self: Any, key: str) -> Optional[Any]: ...
    def set(self: Any, key: str, value: Any, ttl: float | None = ...) -> None: ...
    def invalidate(self: Any, key: str) -> Any: ...
class L3Cache:
    def __init__(self: Any, redis_client: Any = ..., key_prefix: str = ...) -> Any: ...
    def get(self: Any, key: str) -> Optional[Any]: ...
    def set(self: Any, key: str, value: Any, ttl: Optional[float] = ...) -> Any: ...
    def invalidate(self: Any, key: str) -> Any: ...
    def publish_invalidation(self: Any, channel: str, key: str) -> Any: ...
class TierMetrics:
    tier_name: str = ...
    hits: int = ...
    misses: int = ...
    sets: int = ...
    promotions: int = ...
    latency_ns: int = ...
    def hit_rate(self: Any) -> float: ...
    def avg_latency_us(self: Any) -> float: ...
class MultiTierMetrics:
    def __init__(self: Any) -> Any: ...
    def summary(self: Any) -> Dict[str, Any]: ...
class InvalidationListener:
    def __init__(self: Any, redis_client: Any, channel: str, callback: Callable[[str], None]) -> Any: ...
    def start(self: Any) -> Any: ...
    def stop(self: Any) -> Any: ...
class MultiTierClient:
    def __init__(self: Any, l1_size: int = ..., l1_ttl: Optional[float] = ..., l2_type: str = ..., l2_path: Optional[str] = ..., redis_client: Any = ..., l3_key_prefix: str = ..., l4_cache_dir: str = ..., enable_singleflight: bool = ..., ttl_jitter: float = ..., check_l4_on_miss: bool = ..., enable_invalidation_listener: bool = ...) -> Any: ...
    def get(self: Any, key: str, version: int = ...) -> Optional[Any]: ...
    def set(self: Any, key: str, value: Any, ttl: Optional[float] = ..., version: int = ..., write_through: bool = ..., persist_to_l4: bool = ...) -> Any: ...
    def compute_or_get(self: Any, key: str, compute_fn: Callable[[], T], ttl: Optional[float] = ..., version: int = ..., persist_to_l4: bool = ...) -> T: ...
    async def compute_or_get_async(self: Any, key: str, compute_fn: Callable, ttl: Optional[float] = ..., version: int = ..., persist_to_l4: bool = ...) -> T: ...
    def invalidate(self: Any, key: str, broadcast: bool = ...) -> Any: ...
    def invalidate_pattern(self: Any, prefix: str, broadcast: bool = ...) -> Any: ...
    def close(self: Any) -> Any: ...
def multi_tier_cache(ttl: Optional[float] = ..., version: str = ..., persist_large_objects: bool = ..., key_fn: Optional[Callable[[Callable[..., Any], Tuple[Any, ...], Dict[str, Any]], str]] = ..., redis_client: Any = ..., l2_type: str = ..., check_l4_on_miss: bool = ...) -> Any: ...
class PrometheusExporter:
    def __init__(self: Any, client: MultiTierClient) -> Any: ...
    def export(self: Any) -> str: ...
