from typing import Any

"""
Observability SDK - Golden Reference Library

This module is the ONLY sanctioned interface for telemetry.
Direct OpenTelemetry, Prometheus, or logging calls outside this module are FORBIDDEN.

Enforcement: Ruff rule + pre-commit hook (see pyproject.toml)

See: docs/decisions/artifact_registry_decisions.md §4 for rationale.
"""

P: Any
T: Any
logger: Any
class Lane(str, Enum):
    A: Any
    B: Any
class Component(str, Enum):
    PREPROCESSOR: Any
    INFERENCE: Any
    STRATEGY: Any
    CACHE: Any
    REGISTRY: Any
    ORCHESTRATION: Any
class ErrorType(str, Enum):
    VALIDATION: Any
    TIMEOUT: Any
    RESOURCE: Any
    DETERMINISM: Any
    CONTRACT: Any
    INFRASTRUCTURE: Any
    UNKNOWN: Any
class CacheTier(str, Enum):
    L1: Any
    L2: Any
    L3: Any
    L4: Any
class SpanContext:
    run_id: str = ...
    lane: Lane = ...
    strategy_id: str = ...
    plan_hash: str | None = ...
    fold_id: str | None = ...
    worker_id: str | None = ...
class ObservabilitySDK:
    service_name: str = ...
    ALLOWED_METRIC_LABELS: Final[frozenset[str]] = ...
    HIGH_CARD_FIELDS: Final[frozenset[str]] = ...
    def set_build_info(self: Any, version: str, commit_sha: str, python_version: str) -> None: ...
    def span(self: Any, name: str, ctx: SpanContext, kind: SpanKind = ..., attributes: dict[str, Any] | None = ...) -> Generator[Span, None, None]: ...
    def record_inference_latency(self: Any, latency_ms: float, lane: Lane, component: Component = ...) -> None: ...
    def record_cache_access(self: Any, tier: CacheTier, operation: str, hit: bool) -> None: ...
    def record_artifact_registered(self: Any, lane: Lane, artifact_type: str) -> None: ...
    def record_error(self: Any, error_type: ErrorType, component: Component, ctx: SpanContext | None = ..., exception: Exception | None = ...) -> None: ...
    def time_it(self: Any, name: str, component: Component) -> Callable[[Callable[P, T]], Callable[P, T]]: ...
def get_sdk() -> ObservabilitySDK: ...
def span(name: str, ctx: SpanContext, kind: SpanKind = ..., attributes: dict[str, Any] | None = ...) -> contextmanager: ...
def time_it(name: str, component: Component) -> Callable[[Callable[P, T]], Callable[P, T]]: ...
def record_artifact_registered(lane: Lane, artifact_type: str) -> None: ...
def record_cache_access(tier: CacheTier, operation: str, hit: bool) -> None: ...
def record_inference_latency(latency_ms: float, lane: Lane, component: Component = ...) -> None: ...
def record_error(error_type: ErrorType, component: Component, ctx: SpanContext | None = ..., exception: Exception | None = ...) -> None: ...
