from typing import Any

"""
Next-Gen Observability Module (v2) for Trading & ML Systems

Key upgrades vs v1:
- Correct API usage: proper TraceContext propagator import; Status/StatusCode
- Metrics Views: delta temporality + exponential (or explicit) histograms; real exemplars
- Hot-path safety: bounded non-blocking ring buffers + background flushers; drop/queue-depth meta-metrics
- Adaptive behaviors: head-based adaptive tracer sampler; AdaptiveThreshold wired to HTTP latency w/ anomaly metrics
- Exporter hardening: endpoint allow-list, timeouts, and circuit breaker with graceful degrade
- PII performance: fast-path allowlist + compiled regex; redaction map only where needed
- Safer tracing API: no span-link mutation; guard use_span when span is None
- Integrations: minimal sklearn/torch/xgboost wrappers; Kafka hooks retained; ASGI middleware enriched
- Hybrid metadata: resource attrs for colo/region/instance
"""

class ObservabilityError(Exception):
    ...
class ExporterEgressError(ObservabilityError):
    ...
class ExporterTransientError(ObservabilityError):
    ...
class MetricsEmitError(ObservabilityError):
    ...
class PiiRedactionError(ObservabilityError):
    ...
class TracingInitError(ObservabilityError):
    ...
TraceBasedExemplarFilter: Any
ExponentialBucketHistogramAggregation: Any
ExplicitBucketHistogramAggregation: Any
class NoOpMetricsManager:
    def __init__(self: Any, *_a: Any, **_k: Any) -> Any: ...
    def counter(self: Any, *_a: Any, **_k: Any) -> Any: ...
    def histogram(self: Any, *_a: Any, **_k: Any) -> Any: ...
    def record_counter(self: Any, *_a: Any, **_k: Any) -> Any: ...
    def record_histogram(self: Any, *_a: Any, **_k: Any) -> Any: ...
    def shutdown(self: Any) -> Any: ...
class NoOpTracingManager:
    def __init__(self: Any, *_a: Any, **_k: Any) -> Any: ...
    def set_sample_rate(self: Any, *_a: Any, **_k: Any) -> Any: ...
    def start_span(self: Any, *_a: Any, **_k: Any) -> Any: ...
    def start_span_with_links(self: Any, *_a: Any, **_k: Any) -> Any: ...
    def inject_context(self: Any, carrier: Dict[str, str]) -> Any: ...
    def extract_context(self: Any, carrier: Dict[str, str]) -> Any: ...
T: Any
F: Any
def set_tenant(tenant_id: str) -> None: ...
def get_tenant() -> str: ...
def set_strategy(strategy_id: str) -> None: ...
def get_strategy() -> str: ...
class CircuitBreaker:
    def __init__(self: Any, fail_threshold: int = ..., reset_after_sec: int = ...) -> None: ...
    def on_success(self: Any) -> None: ...
    def on_failure(self: Any) -> None: ...
    def is_open(self: Any) -> bool: ...
class CardinalityLimiter:
    def __init__(self: Any, max_keys_per_label: int = ...) -> None: ...
    def sanitize(self: Any, label_key: str, label_value: str) -> str: ...
    def overflow_count(self: Any) -> int: ...
    def stats(self: Any) -> Dict[str, Any]: ...
class PIIRedactor:
    DEFAULT_PATTERNS: Any
    def __init__(self: Any, patterns: Optional[Dict[str, str]] = ..., fast_keys_allowlist: Optional[Iterable[str]] = ...) -> None: ...
    def redact_text(self: Any, text: str) -> str: ...
    def redact_dict(self: Any, data: Dict[str, Any]) -> Dict[str, Any]: ...
class BoundedEventQueue:
    def __init__(self: Any, maxsize: int = ...) -> None: ...
    def put_nowait(self: Any, ev: _Event) -> bool: ...
    def get_batch(self: Any, n: int = ...) -> List[_Event]: ...
    def dropped(self: Any) -> int: ...
    def size(self: Any) -> int: ...
class MetricConfig:
    prometheus_port: int = ...
    otlp_endpoint: Optional[str] = ...
    export_interval_millis: int = ...
    delta_temporality: bool = ...
    enable_exemplars: bool = ...
    buffered_emit: bool = ...
    queue_max_events: int = ...
    flush_every_ms: int = ...
    labels_max_keys_per_label: int = ...
    endpoint_allowlist: Tuple[str, ...] = ...
    exporter_timeout_sec: float = ...
    breaker_fail_threshold: int = ...
    breaker_reset_seconds: int = ...
class SafeOTLPMetricExporter(_OTLPMetricExporter if _OTLPMetricExporter is not None else object):
    def __init__(self: Any, allowlist: Tuple[str, ...], breaker: CircuitBreaker, timeout: float, *args: Any, **kwargs: Any) -> Any: ...
    def export(self: Any, metrics_data: Any) -> Any: ...
class MetricsManager:
    def __init__(self: Any, service_name: str = ..., config: Optional[MetricConfig] = ...) -> None: ...
    def counter(self: Any, name: str, description: str = ..., unit: str = ...) -> Any: ...
    def histogram(self: Any, name: str, description: str = ..., unit: str = ...) -> Any: ...
    def record_counter(self: Any, counter: Any, value: float = ..., labels: Optional[Dict[str, str]] = ...) -> Any: ...
    def record_histogram(self: Any, histogram: Any, value: float, labels: Optional[Dict[str, str]] = ...) -> Any: ...
    def shutdown(self: Any) -> None: ...
class TracingConfig:
    otlp_endpoint: Optional[str] = ...
    sample_rate: float = ...
    max_queue_size: int = ...
    max_export_batch_size: int = ...
    schedule_delay_millis: int = ...
    enable_console_export: bool = ...
    endpoint_allowlist: Tuple[str, ...] = ...
    exporter_timeout_sec: float = ...
class SafeOTLPSpanExporter(_OTLPSpanExporter if _OTLPSpanExporter is not None else object):
    def __init__(self: Any, allowlist: Tuple[str, ...], breaker: CircuitBreaker, timeout: float, *args: Any, **kwargs: Any) -> Any: ...
    def export(self: Any, spans: Any) -> Any: ...
class AdaptiveRatioSampler(Sampler):
    def __init__(self: Any, initial_rate: float) -> None: ...
    def should_sample(self: Any, parent_context: Any, trace_id: Any, name: Any, kind: Any, attributes: Any, links: Any) -> Any: ...
    def get_description(self: Any) -> str: ...
    def set_rate(self: Any, new_rate: float) -> None: ...
class PiiRedactionSpanProcessor(_SpanProcessorBase):
    def __init__(self: Any) -> Any: ...
    def on_start(self: Any, span: Span, parent_context: Optional[context.Context] = ...) -> None: ...
    def on_end(self: Any, span: Span) -> None: ...
    def shutdown(self: Any) -> None: ...
    def force_flush(self: Any, timeout_millis: int = ...) -> bool: ...
class TracingManager:
    def __init__(self: Any, service_name: str = ..., config: Optional[TracingConfig] = ...) -> None: ...
    def set_sample_rate(self: Any, rate: float) -> None: ...
    def start_span(self: Any, name: str, kind: Any = ..., attributes: Optional[Dict[str, Any]] = ..., links: Optional[List[Link]] = ...) -> Span: ...
    def start_span_with_links(self: Any, name: str, linked_spans: Iterable[Span], **kwargs: Any) -> Span: ...
    def inject_context(self: Any, carrier: Dict[str, str]) -> Dict[str, str]: ...
    def extract_context(self: Any, carrier: Dict[str, str]) -> Any: ...
class TraceEnrichedLogger:
    def __init__(self: Any, base_logger: Any, service_name: str) -> None: ...
    def info(self: Any, msg: str, **kwargs: Any) -> Any: ...
    def error(self: Any, msg: str, **kwargs: Any) -> Any: ...
    def warning(self: Any, msg: str, **kwargs: Any) -> Any: ...
    def debug(self: Any, msg: str, **kwargs: Any) -> Any: ...
class LoggingManager:
    def __init__(self: Any, service_name: str = ..., mm_config: Optional[Dict[str, Any]] = ...) -> None: ...
    def get_logger(self: Any) -> Any: ...
class AdaptiveThreshold:
    def __init__(self: Any, alpha: float = ..., sensitivity: float = ..., window_size: int = ...) -> None: ...
    def update(self: Any, value: float) -> bool: ...
    def threshold(self: Any) -> float: ...
class SLOBurnRate:
    def __init__(self: Any, minutes: Iterable[int] = ...) -> None: ...
    def record(self: Any, ok: bool) -> None: ...
    def burn_rates(self: Any, slo_error_budget: float) -> Dict[int, float]: ...
def instrument(name: Optional[str] = ..., labels: Optional[Dict[str, str]] = ..., record_exceptions: bool = ..., measure_latency: bool = ...) -> Callable[[F], F]: ...
class FastAPIMiddleware:
    def __init__(self: Any, app: Any, service_name: str = ..., slo_error_budget: float = ...) -> None: ...
class KafkaInstrumentor:
    def __init__(self: Any) -> None: ...
    def inject_context(self: Any, headers: Dict[str, bytes]) -> Dict[str, bytes]: ...
    def extract_context(self: Any, headers: Dict[str, bytes]) -> Any: ...
    def instrument_producer(self: Any, producer: Any) -> Any: ...
    def instrument_consumer(self: Any, consumer: Any) -> Any: ...
def register_cache_hit_rate_gauges(cache_client: Any, metric_name: str = ...) -> None: ...
def register_cache_hit_rate_gauges_for(func_or_client: Any, metric_name: str = ...) -> None: ...
def get_metrics() -> Optional[MetricsManager]: ...
def get_tracing() -> Optional[TracingManager]: ...
def get_logging() -> Optional[LoggingManager]: ...
def get_logger() -> Any: ...
def init_observability(service_name: str = ..., metrics_config: Optional[MetricConfig] = ..., tracing_config: Optional[TracingConfig] = ..., enable_metrics: bool = ..., enable_tracing: bool = ..., enable_logging: bool = ...) -> Any: ...
