from typing import Any

class BorrowInterestConfig:
    borrow_interest_bps: float = ...
class BorrowInterestModel:
    def __init__(self: Any, config: BorrowInterestConfig | None = ...) -> None: ...
    def to_execution_assumptions(self: Any) -> dict[str, float]: ...
