from typing import Any

class FeeModelConfig:
    commission_bps: float = ...
class FlatFeeCostModel:
    def __init__(self: Any, config: FeeModelConfig | None = ...) -> None: ...
    def estimate(self: Any, fills: list[dict[str, Any]], ctx: dict[str, Any]) -> CostEstimate: ...
    def to_execution_assumptions(self: Any) -> dict[str, Any]: ...
