from typing import Any

class FillModelConfig:
    fill_ratio: float = ...
class IdentityFillModel:
    def __init__(self: Any, config: FillModelConfig | None = ...) -> None: ...
    def simulate(self: Any, orders: list[dict[str, Any]], ctx: dict[str, Any]) -> list[dict[str, Any]]: ...
    def to_execution_assumptions(self: Any) -> dict[str, Any]: ...
