from typing import Any

class LatencyModelConfig:
    latency_ms: int = ...
class LatencyModel:
    def __init__(self: Any, config: LatencyModelConfig | None = ...) -> None: ...
    def to_execution_assumptions(self: Any) -> dict[str, int]: ...
