from typing import Any

class LiquidityModelConfig:
    max_participation_rate: float = ...
class LiquidityModel:
    def __init__(self: Any, config: LiquidityModelConfig | None = ...) -> None: ...
    def to_execution_assumptions(self: Any) -> dict[str, float]: ...
