from typing import Any

class SlippageModelConfig:
    slippage_bps: float = ...
class SlippageModel:
    def __init__(self: Any, config: SlippageModelConfig | None = ...) -> None: ...
    def to_execution_assumptions(self: Any) -> dict[str, float]: ...
