from typing import Any

def ensure_pydantic() -> Any: ...
def ensure_polars() -> Any: ...
def ensure_influxdb_client() -> Any: ...
BaseModel: Any
Field: Any
ValidationError: Any
ConfigDict: Any
model_validator: Any
logger: Any
BASE: Path = ...
DEFAULT_CONFIG_PATH: Path = ...
DEFAULT_SCHEMA_PATH: Path = ...
CONFIG_PATH: Optional[Path] = ...
SCHEMA_PATH: Optional[Path] = ...
class Section(BaseModel):
    model_config: Any
    def validate_section(self: Any) -> None: ...
class CSVSource(_PolarsMixin, _CSVSourceModel):
    def to_polars(self: Any, **read_kwargs: Any) -> Any: ...
class InfluxSource(_PolarsMixin, _InfluxSourceModel):
    def to_polars(self: Any, **read_kwargs: Any) -> Any: ...
DataSource: Any
class RSI(Section):
    enabled: bool = ...
    window: int = ...
    fillna_method: str = ...
    def validate_section(self: Any) -> None: ...
class MACD(Section):
    enabled: bool = ...
    fast_period: int = ...
    slow_period: int = ...
    signal_period: int = ...
    fillna_method: str = ...
    def validate_section(self: Any) -> None: ...
class ATR(Section):
    enabled: bool = ...
    window: int = ...
    fillna_method: str = ...
class Bollinger(Section):
    enabled: bool = ...
    window: int = ...
    std_dev: float = ...
    fillna_method: str = ...
class VWAP(Section):
    enabled: bool = ...
    reset_period: str = ...
    fillna_method: str = ...
class TechnicalIndicators(Section):
    rsi: Optional[RSI] = ...
    macd: Optional[MACD] = ...
    atr: Optional[ATR] = ...
    vwap: Optional[VWAP] = ...
    bollinger_bands: Optional[Bollinger] = ...
    extra_indicators: Dict[str, Dict[str, Any]] = ...
    def validate_section(self: Any) -> None: ...
class Clip(Section):
    min: float = ...
    max: float = ...
class Normalization(Section):
    method: str = ...
    rolling_window: int = ...
    clip_extremes: Clip = ...
    def validate_section(self: Any) -> None: ...
class Calendar(Section):
    enabled: bool = ...
    day_of_week: bool = ...
    holidays: List[str] = ...
    timezones: List[str] = ...
    def is_holiday(self: Any, dt: Any) -> bool: ...
class Sentiment(Section):
    enabled: bool = ...
    source: str = ...
    sentiment_model: str = ...
class ESGNormalized(Section):
    enabled: bool = ...
    method: str = ...
class CustomFeatures(Section):
    sentiment: Optional[Sentiment] = ...
    esg_normalized: Optional[ESGNormalized] = ...
class Preprocessing(Section):
    technical_indicators: TechnicalIndicators = ...
    normalization: Normalization = ...
    custom_features: CustomFeatures = ...
    calendar_features: Calendar = ...
    steps: List[Dict[str, Any]] = ...
    step_macros: Dict[str, Dict[str, Any]] = ...
    def validate_section(self: Any) -> None: ...
    def expand_macros(self: Any) -> None: ...
class CleaningCombo(Section):
    name: str = ...
    when: Optional[Dict[str, Any]] = ...
    steps: List[Dict[str, Any]] = ...
    order: Dict[str, Dict[str, List[str]]] = ...
    determinism_tier: str = ...
    governance_mode: str = ...
    seed_lineage: str = ...
    pit_boundary: str = ...
    metadata: Dict[str, Any] = ...
class Cleaning(Section):
    combos: List[CleaningCombo] = ...
    use: Optional[str] = ...
    determinism_tier: str = ...
    governance_mode: str = ...
    seed_lineage: str = ...
    pit_boundary: str = ...
    missing_values: Dict[str, Any] = ...
    outliers: Dict[str, Any] = ...
    denoising: Dict[str, Any] = ...
class Streaming(Section):
    batch_size: int = ...
    update_interval_seconds: int = ...
    buffer_size: int = ...
    max_latency_ms: int = ...
    buffer_retention_seconds: int = ...
    event_triggers: Dict[str, str] = ...
    priority_queue: str = ...
    failure_recovery: Dict[str, Any] = ...
    sync_interval_seconds: int = ...
class RetryPolicy(Section):
    max_attempts: int = ...
    initial_backoff_seconds: int = ...
    max_backoff_seconds: int = ...
    retry_strategy: str = ...
class ValidationThresholds(Section):
    max_missing_ratio: float = ...
    max_outlier_ratio: float = ...
class Fallback(Section):
    twitter: str = ...
    esg: str = ...
    data_source: str = ...
class Alerting(Section):
    enabled: bool = ...
    channel: str = ...
    critical_failures: List[str] = ...
    alert_severity: List[str] = ...
class ErrorHandling(Section):
    retry_policy: RetryPolicy = ...
    validation_thresholds: ValidationThresholds = ...
    fallback: Fallback = ...
    alerting: Alerting = ...
    fallback_timeout_seconds: int = ...
class ModelArchitecture(Section):
    num_layers: int = ...
    hidden_size: int = ...
    dropout: float = ...
class Model(Section):
    model_type: str = ...
    architecture: ModelArchitecture = ...
    sequence_length: int = ...
    prediction_horizon: int = ...
    feature_list: List[str] = ...
    training_device: str = ...
    model_checkpoint: Dict[str, int] = ...
    feature_importance: Dict[str, str] = ...
    onnx_export: Dict[str, Any] = ...
class FileOutput(Section):
    enabled: bool = ...
    path: str = ...
    rotation: str = ...
class InfluxDBOutput(Section):
    enabled: bool = ...
    host: str = ...
    port: int = ...
    token: str = ...
    org: str = ...
    bucket: str = ...
class Outputs(Section):
    console: bool = ...
    file: FileOutput = ...
    influxdb: InfluxDBOutput = ...
class MetricAggregation(Section):
    aggregation_window_seconds: int = ...
class DashboardConfig(Section):
    grafana_url: str = ...
class Logging(Section):
    level: str = ...
    outputs: Outputs = ...
    metrics_report_interval_seconds: int = ...
    custom_metrics: List[str] = ...
    model_metrics: List[str] = ...
    metric_aggregation: MetricAggregation = ...
    log_sampling_rate: float = ...
    dashboard_config: DashboardConfig = ...
class Encryption(Section):
    at_rest: bool = ...
    in_transit: bool = ...
    encryption_algorithm: str = ...
class Credentials(Section):
    twitter_api_key: Optional[str] = ...
    esg_api_key: Optional[str] = ...
    fred_api_key: Optional[str] = ...
    bloomberg_api_key: Optional[str] = ...
    weather_api_key: Optional[str] = ...
    alpha_vantage_api_key: Optional[str] = ...
    def validate_secrets(self: Any) -> 'Credentials': ...
class DataAnonymization(Section):
    anonymize_pii: bool = ...
class Compliance(Section):
    audit_log: bool = ...
    retention_days: int = ...
    audit_frequency_days: int = ...
    data_anonymization: DataAnonymization = ...
class Security(Section):
    encryption: Encryption = ...
    key_management: str = ...
    credentials: Credentials = ...
    compliance: Compliance = ...
class RiskManagement(Section):
    stop_loss: float = ...
    max_drawdown: float = ...
class DateRange(Section):
    start: str = ...
    end: str = ...
class PositionSizing(Section):
    method: str = ...
class Backtesting(Section):
    initial_capital: float = ...
    transaction_cost_rate: float = ...
    slippage_rate: float = ...
    strategy_list: List[str] = ...
    risk_management: RiskManagement = ...
    date_range: DateRange = ...
    performance_metrics: List[str] = ...
    position_sizing: PositionSizing = ...
    benchmark_index: str = ...
    backtest_frequency: str = ...
class DistributedProcessing(Section):
    framework: str = ...
    num_workers: int = ...
    memory_per_worker: str = ...
    cluster_type: str = ...
    min_rows_for_distributed: int = ...
class InteractiveBrokers(Section):
    host: str = ...
    port: int = ...
    client_id: int = ...
    subscription_topics: List[str] = ...
    api_key: str = ...
    endpoint: str = ...
    connection_timeout_seconds: int = ...
    priority: int = ...
    what_to_show: str = ...
    use_rth: bool = ...
    format_date: int = ...
class Alpaca(Section):
    api_key: Optional[str] = ...
    secret_key: str = ...
    endpoint: str = ...
class RealTimeMarketData(Section):
    interactive_brokers: Optional[InteractiveBrokers] = ...
    alpaca: Optional[Alpaca] = ...
class RateLimit(Section):
    per_minute: Optional[int] = ...
    max_calls_per_window: Optional[int] = ...
    window_seconds: Optional[int] = ...
class ExternalAPISource(Section):
    base_url: str = ...
    api_key: Optional[str] = ...
    authentication_type: Optional[str] = ...
    endpoints: Dict[str, str] = ...
    default_params: Dict[str, str] = ...
    rate_limit: Optional[RateLimit] = ...
    timeout_seconds: int = ...
    cache_duration_hours: int = ...
    data_resolution: Optional[str] = ...
    def validate_section(self: Any) -> None: ...
class Twitter(Section):
    base_url: str = ...
    bearer_token: str = ...
    authentication_type: str = ...
    endpoints: Dict[str, str] = ...
    default_params: Dict[str, Any] = ...
    rate_limit: RateLimit = ...
    retry_after_header: str = ...
    timeout_seconds: int = ...
    cache_duration_hours: int = ...
    data_resolution: str = ...
    api_key: Optional[str] = ...
class ESG(Section):
    base_url: str = ...
    api_key: str = ...
    authentication_type: str = ...
    endpoints: Dict[str, str] = ...
    default_params: Dict[str, str] = ...
    timeout_seconds: int = ...
    cache_duration_hours: int = ...
    data_resolution: str = ...
class FRED(ExternalAPISource):
    ...
class Bloomberg(ExternalAPISource):
    ...
class Weather(ExternalAPISource):
    ...
class AlternativeData(Section):
    twitter: Optional[Twitter] = ...
    alpaca: Optional[Alpaca] = ...
    esg: Optional[ESG] = ...
    fred: Optional[FRED] = ...
    bloomberg: Optional[Bloomberg] = ...
    weather: Optional[Weather] = ...
class AnomalyDetection(Section):
    enabled: bool = ...
    method: Optional[str] = ...
    params: Optional[Dict[str, Any]] = ...
class PipelineConfig(BaseModel):
    model_config: Any
    version: str = ...
    schema_uri: str = ...
    data_source: DataSource = ...
    preprocessing: Preprocessing = ...
    cleaning: Cleaning = ...
    streaming: Streaming = ...
    error_handling: ErrorHandling = ...
    model: Model = ...
    logging: Logging = ...
    security: Security = ...
    backtesting: Backtesting = ...
    distributed_processing: DistributedProcessing = ...
    alternative_data: AlternativeData = ...
    market_data_sources: List[Dict[str, Any]] = ...
    real_time_market_data: RealTimeMarketData = ...
    anomaly_detection: AnomalyDetection = ...
    includes: List[str] = ...
    profiles: Dict[str, Dict[str, Any]] = ...
    active_profiles: List[str] = ...
    list_merge_strategy: str = ...
    def merged(self: Any, *overlays: Mapping[str, Any], list_strategy: Optional[str] = ...) -> 'PipelineConfig': ...
    def with_profile(self: Any, *profile_names: str) -> 'PipelineConfig': ...
def load_config(path: Optional[Path] = ..., schema_path: Optional[Path] = ..., *, apply_env: bool = ..., env_prefix: str = ..., list_strategy: str = ...) -> PipelineConfig: ...
def get_config(path: Optional[Path] = ...) -> PipelineConfig: ...
def reload_config(path: Optional[Path] = ...) -> PipelineConfig: ...
def reset_config_cache() -> None: ...
def get_runtime_config() -> PipelineConfig: ...
def get_dataset(**kwargs: Any) -> Any: ...
def validate_runtime_requirements(conf: Optional[PipelineConfig] = ...) -> List[str]: ...
