from typing import Any

"""
Pipeline configuration with observability.

This module adds:
- Prometheus metrics for config load latency and errors
- Re-exports all config models and functions

All configuration logic lives in pysrc.pipeline.pipeline_config.loader.
"""

logger: Any
def load_config(path: Optional[Path] = ..., schema_path: Optional[Path] = ..., *, apply_env: bool = ..., env_prefix: str = ..., list_strategy: str = ...) -> PipelineConfig: ...
def get_config(path: Optional[Path] = ...) -> PipelineConfig: ...
def reload_config(path: Optional[Path] = ...) -> PipelineConfig: ...
def reset_config_cache() -> None: ...
def get_runtime_config() -> PipelineConfig: ...
def get_dataset(**kwargs: Any) -> Any: ...
def validate_runtime_requirements(conf: Optional[PipelineConfig] = ...) -> List[str]: ...
def get_config_singleton() -> Any: ...
