from typing import Any

"""
Simple deterministic baselines for W2-SU v0.
"""

def evaluate_static_equal_weight_signal_ensemble(panel: pd.DataFrame) -> dict[str, object]: ...
def evaluate_rolling_ic_weighted_ensemble(panel: pd.DataFrame) -> dict[str, object]: ...
def evaluate_best_historical_signal(panel: pd.DataFrame) -> dict[str, object]: ...
def evaluate_simple_regime_conditioned_gate(panel: pd.DataFrame, config: SignalUsabilityConfig) -> dict[str, object]: ...
