from typing import Any

"""
Immutable configuration for the W2-SU signal-usability surface.
"""

class SignalUsabilityConfig:
    horizon: int = ...
    utility_floor: float = ...
    cost_per_turnover_unit: float = ...
    min_recent_window: int = ...
    recent_ic_window: int = ...
    recent_hit_rate_window: int = ...
    decay_window: int = ...
    output_dir: Path = ...
    schema_version: str = ...
    seed: int = ...
    timestamp_utc: str = ...
    minimum_eligible_rows: int = ...
    minimum_admissible_dates: int = ...
    minimum_real_instruments: int = ...
    data_mode: Literal['real', 'fixture', 'synthetic'] = ...
    data_source_id: str = ...
    as_of_policy: str = ...
    requested_universe: tuple[str, ...] = ...
    train_fraction: float = ...
    validation_fraction: float = ...
    test_fraction: float = ...
    regime_gate_min_mean_utility: float = ...
    regime_gate_unseen_policy: Literal['abstain'] = ...
    min_coverage_for_support: float = ...
    xgboost_probability_threshold: float | None = ...
    xgboost_n_estimators: int = ...
    xgboost_max_depth: int = ...
    xgboost_learning_rate: float = ...
