from typing import Any

"""
Runner for the W2-SU signal-usability diagnostic lane.
"""

class SignalUsabilityRunResult:
    panel: pd.DataFrame = ...
    missing_signal_reasons: dict[str, str] = ...
    baselines: dict[str, dict[str, object]] = ...
    models: dict[str, dict[str, object]] = ...
    metrics: dict[str, object] = ...
    report: dict[str, object] = ...
    report_path: Path = ...
def load_signal_usability_market_data(path: Path) -> pd.DataFrame: ...
def build_default_signal_usability_market_data() -> pd.DataFrame: ...
def run_signal_usability_diagnostic(*, market_data: pd.DataFrame, config: SignalUsabilityConfig) -> SignalUsabilityRunResult: ...
def interpret_learnability(*, classification: dict[str, str], baselines: dict[str, dict[str, object]], metrics: dict[str, object], config: SignalUsabilityConfig) -> dict[str, str]: ...
def run_default_signal_usability_diagnostic(*, output_dir: Path | None = ..., seed: int = ..., timestamp_utc: str = ...) -> SignalUsabilityRunResult: ...
