from typing import Any

"""
Manual weak-signal set for W2-SU v0.
"""

SignalRole: Any
SignalComputer: Any
class SignalDefinition:
    signal_id: str = ...
    signal_role: SignalRole = ...
    label_eligible: bool = ...
    required_columns: tuple[str, ...] = ...
    computer: SignalComputer = ...
def signal_definitions() -> tuple[SignalDefinition, ...]: ...
