from typing import Any

"""
Alerts: structured alert emission for drift, gate failure, and system events.
"""

class AlertSeverity(str, Enum):
    INFO: Any
    WARNING: Any
    CRITICAL: Any
class Alert:
    severity: AlertSeverity = ...
    title: str = ...
    job_id: str = ...
    details: dict[str, Any] = ...
    emitted_at: datetime = ...
def emit_alert(alert: Alert) -> None: ...
