from typing import Any

"""
DashboardConfig: declarative configuration for Grafana/internal dashboard exports.
"""

class DashboardPanel:
    title: str = ...
    metric: str = ...
    panel_type: str = ...
    unit: str = ...
class DashboardConfig:
    job_id: str = ...
    title: str = ...
    panels: tuple[DashboardPanel, ...] = ...
    refresh_seconds: int = ...
    grafana_url: str = ...
