from typing import Any

"""
DriftMonitor: tracks feature and prediction drift for live strategies.
"""

class DriftReport:
    job_id: str = ...
    feature_hash: str = ...
    drift_score: float = ...
    threshold: float = ...
    is_drifting: bool = ...
    observed_at: datetime = ...
    details: dict[str, float] = ...
class DriftMonitor:
    def __init__(self: Any, job_id: str, threshold: float) -> None: ...
    def observe(self: Any, drift_score: float, feature_hash: str, now: datetime, details: dict[str, float] | None = ...) -> DriftReport: ...
