from typing import Any

"""
LatencyMonitor: records and reports inference/execution latency histograms.
"""

class LatencyReport:
    p50_ms: float = ...
    p95_ms: float = ...
    p99_ms: float = ...
    max_ms: float = ...
class LatencyMonitor:
    def __init__(self: Any) -> None: ...
    def record(self: Any, latency_ms: float) -> None: ...
    def report(self: Any) -> LatencyReport: ...
