from typing import Any

"""
SlippageMonitor: tracks execution slippage between signal and fill prices.
"""

class SlippageReport:
    mean_bps: float = ...
    max_bps: float = ...
    p95_bps: float = ...
class SlippageMonitor:
    def report(self: Any, signal_prices: pd.Series, fill_prices: pd.Series) -> SlippageReport: ...
