from typing import Any

"""
ThroughputMonitor: tracks trial and task throughput rates.
"""

class ThroughputReport:
    trials_per_second: float = ...
    tasks_per_second: float = ...
    observation_seconds: float = ...
class ThroughputMonitor:
    def __init__(self: Any) -> None: ...
    def record_trial(self: Any, n: int = ...) -> None: ...
    def record_task(self: Any, n: int = ...) -> None: ...
    def report(self: Any) -> ThroughputReport: ...
