from typing import Any

"""
Tracing: lightweight span-based instrumentation for the tuning pipeline.
"""

class Span:
    name: str = ...
    start_ns: int = ...
    end_ns: int | None = ...
    tags: dict[str, Any] = ...
    def finish(self: Any) -> None: ...
    def duration_ms(self: Any) -> float | None: ...
def trace(name: str, tags: dict[str, Any] | None = ...) -> Generator[Span, None, None]: ...
