from typing import Any

class CapabilityFacts:
    has_cudf: bool = ...
    has_polars_gpu: bool = ...
    backend: str = ...
    def to_payload(self: Any) -> dict[str, Any]: ...
class ExecutionEvidence:
    events: tuple[str, ...] = ...
    metrics: Mapping[str, Any] = ...
    def to_payload(self: Any) -> dict[str, Any]: ...
class GovernedExecutionSpec:
    plan: PreprocessingPlan = ...
    state: PreprocessingStateManifest = ...
    capabilities: CapabilityFacts = ...
    governance: GovernanceDecision = ...
    actual_materialization: str = ...
    schema_signature: str = ...
    evidence: ExecutionEvidence = ...
    attempted_retry: bool = ...
class GovernedExecutionCacheKey:
    value: str = ...
    def from_inputs(cls: Any, *, plan: PreprocessingPlan, state: PreprocessingStateManifest, capabilities: CapabilityFacts, governance: GovernanceDecision) -> 'GovernedExecutionCacheKey': ...
def reject_if_governance_required(*, governed: bool, fallback_name: str) -> None: ...
def validate_governed_execution(spec: GovernedExecutionSpec) -> GovernedExecutionSpec: ...
