from typing import Any

class MaterializationSpec:
    format: str = ...
    schema_signature: str = ...
    partial_allowed: bool = ...
class CanonicalOp:
    name: str = ...
    params: Mapping[str, Any] = ...
    provides: tuple[str, ...] = ...
    requires: tuple[str, ...] = ...
    def to_payload(self: Any) -> dict[str, Any]: ...
class PreprocessingPlan:
    version: str = ...
    ops: tuple[CanonicalOp, ...] = ...
    group_by: tuple[str, ...] = ...
    materialization: MaterializationSpec = ...
    metadata: Mapping[str, Any] = ...
    def to_payload(self: Any) -> dict[str, Any]: ...
    def plan_id(self: Any) -> HashRef: ...
