from typing import Any

CURRENT_PREPROCESSING_SCHEMA_VERSION: Any
class FitStateArtifact:
    name: str = ...
    payload: Mapping[str, Any] = ...
    def to_payload(self: Any) -> dict[str, Any]: ...
class PreprocessingStateManifest:
    schema_version: str = ...
    plan_version: str = ...
    artifacts: tuple[FitStateArtifact, ...] = ...
    lineage: Mapping[str, Any] = ...
    def to_payload(self: Any) -> dict[str, Any]: ...
    def state_id(self: Any) -> HashRef: ...
