from typing import Any

class Order:
    order_id: int = ...
    action: str = ...
    total_quantity: float = ...
    order_type: str = ...
    lmt_price: Optional[float] = ...
    aux_price: Optional[float] = ...
    tif: str = ...
    account: Optional[str] = ...
    symbol: Optional[str] = ...
    solicited: bool = ...
    extra: Dict[str, Any] = ...
    def market(cls: Any, symbol: str, qty: float) -> 'Order': ...
class Position:
    account: str = ...
    symbol: str = ...
    position: float = ...
    avg_cost: float = ...
    model_code: Optional[str] = ...
    extra: Dict[str, Any] = ...
PositionSchema: SchemaDict = ...
HistoricalSchema: SchemaDict = ...
class OrderExecutor(Protocol):
    def submit(self: Any, order: Order) -> str: ...
    def submit_batch(self: Any, orders: List[Order]) -> List[str]: ...
    def cancel(self: Any, order_id: str) -> None: ...
    def status(self: Any, order_id: str) -> str: ...
class PositionService(Protocol):
    def get_positions(self: Any) -> List[Position]: ...
    def get_positions_as_polars(self: Any) -> pl.DataFrame: ...
class MarketDataProvider(Protocol):
    def get_price(self: Any, symbol: str) -> float: ...
    def get_prices(self: Any, symbols: List[str]) -> Dict[str, float]: ...
    def get_historical(self: Any, symbol: str, start: str, end: str, interval: str = ..., lazy: bool = ...) -> pl.LazyFrame | pl.DataFrame: ...
    def get_historical_batch(self: Any, symbols: List[str], start: str, end: str, interval: str = ..., lazy: bool = ...) -> Dict[str, pl.LazyFrame | pl.DataFrame]: ...
    def map_over(self: Any, symbols: List[str], fn: Callable[[str], pl.LazyFrame], combine: Callable[[List[pl.LazyFrame]], pl.LazyFrame] = ...) -> pl.LazyFrame: ...
    async def stream_realtime(self: Any, symbol: str, interval: float = ...) -> AsyncIterator[pl.DataFrame]: ...
class AsyncMarketDataProvider(MarketDataProvider, Protocol):
    async def get_price_async(self: Any, symbol: str) -> float: ...
    async def get_prices_async(self: Any, symbols: List[str]) -> Dict[str, float]: ...
class EconomicDataProvider(Protocol):
    def get_indicator(self: Any, indicator: str, start: str, end: str) -> pl.LazyFrame: ...
T_co: Any
class ProviderFactory(ABC, Generic[T_co]):
    def register(cls: Any, provider_type: str) -> Callable[[Type['ProviderFactory']], Type['ProviderFactory']]: ...
    def load_entry_points(cls: Any, group: str = ...) -> int: ...
    def create(cls: Type['ProviderFactory[T_co]'], provider_type: str, config: Dict[str, Any], **kwargs: Any) -> T_co: ...
    def build_provider(self: Any, config: Dict[str, Any], **kwargs: Any) -> T_co: ...
class RiskManager:
    def validate(self: Any, order: Any) -> Any: ...
class PositionSizer:
    def size(self: Any, symbol: str, signal: float, price: float) -> float: ...
class AbstractAPIDataManager:
    registry: Dict[str, Type[Any]] = ...
    def register(cls: Any, source_type: str) -> Any: ...
    def __init__(self: Any, config: Dict[str, Any]) -> Any: ...
    def add_source(self: Any, source_type: str, source: Any) -> Any: ...
    async def load_data(self: Any, query: Union[str, List[str]], source_name: Optional[str] = ...) -> Union[pl.LazyFrame, Dict[str, Union[pl.LazyFrame, Exception]]]: ...
