from typing import Any

"""
py/backtesting/contracts/bundle.py

Typed dataclasses for the Appendix C run-bundle schema (v1.0.0).
These mirror the JSON files written by BundleWriter so that downstream
consumers (gate.py, report.py) can work with typed objects instead of
raw dicts.
"""

BUNDLE_SCHEMA_VERSION: Any
class PlanRecord:
    schema_version: str = ...
    plan_hash: str = ...
    as_of_time: str = ...
    config_hash: str = ...
    config: dict[str, Any] = ...
class EnvFingerprintRecord:
    schema_version: str = ...
    python_version: str = ...
    platform: str = ...
    git_sha: str = ...
    deps: dict[str, str] = ...
class DatasetManifestRecord:
    schema_version: str = ...
    dataset_id: str = ...
    symbols: list[str] = ...
    row_count: int = ...
    time_range: dict[str, str] = ...
    pit_compliant: bool = ...
    knowledge_time_column: str = ...
    content_hash: str | None = ...
    download_timestamp: str | None = ...
    content_hash_expected: str | None = ...
class PreprocessingReportRecord:
    schema_version: str = ...
    steps: list[dict[str, Any]] = ...
    timings: dict[str, float] = ...
    warnings: list[str] = ...
class SplitRecord:
    train_start: str = ...
    train_end: str = ...
    test_start: str = ...
    test_end: str = ...
    fold: int = ...
class SplitsManifestRecord:
    schema_version: str = ...
    split_method: str = ...
    purge_window: int = ...
    embargo_window: int = ...
    splits: list[dict[str, Any]] = ...
class RunBundle:
    plan: PlanRecord = ...
    env_fingerprint: EnvFingerprintRecord = ...
    dataset_manifest: DatasetManifestRecord = ...
    preprocessing_report: PreprocessingReportRecord = ...
    splits_manifest: SplitsManifestRecord = ...
