from typing import Any

class BacktestingContractError(RuntimeError):
    ...
class DeterminismTierMissingError(BacktestingContractError):
    ...
class PitUnsafeInputError(BacktestingContractError):
    ...
class OptionalDependencyMissingError(BacktestingContractError):
    ...
class NotImplementedLaneError(BacktestingContractError):
    ...
class UnknownIdError(BacktestingContractError):
    component_kind: str = ...
    requested_id: str = ...
    available_ids: tuple[str, ...] = ...
    hint: str = ...
