from typing import Any

class DeterminismTier(str, Enum):
    D0: Any
    D1: Any
    D2: Any
    D3: Any
class EngineConfig:
    lane: str = ...
    bar_frequency: str = ...
    params: dict[str, Any] = ...
class BacktestPlan:
    engine_id: str = ...
    execution_model_id: str = ...
    cost_model_id: str = ...
    ledger_id: str = ...
    validator_ids: list[str] = ...
    determinism: DeterminismTier = ...
    seed: int = ...
    pit_required: bool = ...
    engine_config: EngineConfig | None = ...
    run_id: str | None = ...
