from typing import Any

class AsOfView(Protocol):
    def as_of(self: Any, ts: datetime) -> MarketSlice: ...
    def pit_meta(self: Any) -> PitMeta | None: ...
class BacktestArtifactStore(Protocol):
    def put_json(self: Any, role: str, payload: dict[str, Any]) -> Any: ...
    def put_bytes(self: Any, role: str, payload: bytes, media_type: str) -> Any: ...
    def get_json(self: Any, ref: Any) -> dict[str, Any]: ...
class BacktestEngine(Protocol):
    def run(self: Any, plan: BacktestPlan, data: Any, store: BacktestArtifactStore) -> BacktestResult: ...
class ExecutionModel(Protocol):
    def simulate(self: Any, orders: list[dict[str, Any]], ctx: dict[str, Any]) -> list[dict[str, Any]]: ...
class CostModel(Protocol):
    def estimate(self: Any, fills: list[dict[str, Any]], ctx: dict[str, Any]) -> CostEstimate: ...
class Ledger(Protocol):
    def apply(self: Any, fills: list[dict[str, Any]], corporate_actions: list[dict[str, Any]] | None) -> LedgerSnapshot: ...
class BacktestValidator(Protocol):
    def validate(self: Any, result: BacktestResult, ctx: dict[str, Any], store: BacktestArtifactStore) -> ValidationReport: ...
class BacktestSuiteOrchestrator(Protocol):
    def execute(self: Any, suite_plan: Any) -> RunBundleRef: ...
