from typing import Any

Factory: Any
def register_engine(component_id: str, factory: Factory) -> None: ...
def resolve_engine(component_id: str) -> Any: ...
def list_engines() -> list[str]: ...
def register_execution_model(component_id: str, factory: Factory) -> None: ...
def resolve_execution_model(component_id: str) -> Any: ...
def list_execution_models() -> list[str]: ...
def register_cost_model(component_id: str, factory: Factory) -> None: ...
def resolve_cost_model(component_id: str) -> Any: ...
def list_cost_models() -> list[str]: ...
def register_ledger(component_id: str, factory: Factory) -> None: ...
def resolve_ledger(component_id: str) -> Any: ...
def list_ledgers() -> list[str]: ...
def register_validator(component_id: str, factory: Factory) -> None: ...
def resolve_validator(component_id: str) -> Any: ...
def list_validators() -> list[str]: ...
def register_store(component_id: str, factory: Factory) -> None: ...
def resolve_store(component_id: str) -> Any: ...
def list_stores() -> list[str]: ...
