from typing import Any

class ValidationStatus(str, Enum):
    PASS: Any
    WARN: Any
    FAIL: Any
class ArtifactRef:
    role: str = ...
    path: str = ...
    cas: str | None = ...
    attest: str | None = ...
class RunBundleRef:
    bundle_path: str = ...
    run_id: str | None = ...
    manifest_ref: ArtifactRef | None = ...
class PitMeta:
    as_of: str | None = ...
    source: str | None = ...
    knowledge_cutoff: str | None = ...
class MarketSlice:
    as_of: str = ...
    prices: list[dict[str, Any]] = ...
    features: list[dict[str, Any]] = ...
    metadata: dict[str, Any] = ...
    pit_meta: PitMeta | None = ...
class Fill:
    symbol: str = ...
    quantity: float = ...
    price: float = ...
    side: str = ...
    timestamp: str = ...
class CostEstimate:
    total_cost: float = ...
    components: dict[str, float] = ...
class LedgerPosition:
    symbol: str = ...
    quantity: float = ...
    average_price: float = ...
class LedgerSnapshot:
    timestamp: str = ...
    cash: float = ...
    positions: list[LedgerPosition] = ...
    metadata: dict[str, Any] = ...
class BacktestResult:
    metrics: dict[str, float] = ...
    artifacts: dict[str, ArtifactRef] = ...
    warnings: list[str] = ...
    errors: list[str] = ...
    fills: list[Fill] = ...
    ledger: LedgerSnapshot | None = ...
class ValidationReport:
    status: ValidationStatus = ...
    reason_code: str = ...
    message: str = ...
    artifacts: dict[str, ArtifactRef] = ...
class MarketDataPoint:
    symbol: str = ...
    timestamp: str = ...
    value: float = ...
    field_name: str = ...
def to_primitive(value: Any) -> Any: ...
