from typing import Any

"""
ContextFeatures: typed feature vector describing a tuning job's search context.
"""

class ContextFeatures:
    n_dimensions: int = ...
    n_continuous: int = ...
    n_discrete: int = ...
    n_categorical: int = ...
    budget_trials: int = ...
    n_symbols: int = ...
    n_folds: int = ...
    has_prior_experiments: bool = ...
