from typing import Any

"""
Prior distributions over hyperparameters informed by past experiments.
"""

class HParamPrior:
    name: str = ...
    mean: float = ...
    std: float = ...
    weight: float = ...
class SearchPrior:
    space_hash: str = ...
    priors: tuple[HParamPrior, ...] = ...
def uniform_prior(name: str, low: float, high: float) -> HParamPrior: ...
