from typing import Any

"""
Pure regime-label projection onto task fold boundaries.
"""

class RegimeSegment:
    label: str = ...
    start: datetime = ...
    end: datetime = ...
def project_regime(fold_start: datetime, fold_end: datetime, segments: tuple[RegimeSegment, ...]) -> str: ...
