from typing import Any

"""
TaskManifest: immutable ordered record of all TaskIRs in a job.
"""

class TaskManifest:
    job_id: str = ...
    tasks: tuple[TaskIR, ...] = ...
    spec_hash: str = ...
    def n_tasks(self: Any) -> int: ...
    def by_id(self: Any, task_id: str) -> TaskIR: ...
