from typing import Any

logger: Any
class GpuCapabilities:
    has_cuda: bool = ...
    has_rmm: bool = ...
    has_cudf: bool = ...
    has_polars_gpu: bool = ...
    has_nvtabular: bool = ...
    has_kvikio: bool = ...
    device_count: int = ...
    compute_capability: Optional[str] = ...
def capabilities() -> GpuCapabilities: ...
def init_rmm_pool(pool_size: Optional[int] = ..., managed_memory: bool = ..., async_alloc: bool = ..., logging: bool = ..., release_threshold: Optional[int] = ...) -> None: ...
class StreamFactory:
    def create(non_blocking: bool = ...) -> Any: ...
class StreamPool:
    def __init__(self: Any, size: int = ..., non_blocking: bool = ...) -> Any: ...
    def lease(self: Any) -> Any: ...
def pinned_array(shape: Any, dtype: Any = ...) -> Any: ...
def device_synchronize() -> Any: ...
def maybe_stream(stream: Any) -> Any: ...
