from typing import Any

class OOMRetry(Exception):
    def __init__(self: Any, message: Any = ..., retry_hint: Any = ...) -> Any: ...
class UnsupportedAST(Exception):
    ...
class SchemaMismatch(Exception):
    def __init__(self: Any, message: Any, details: Any = ...) -> Any: ...
