from typing import Any

def register_expr(name: str, builder: Callable[..., Any]) -> None: ...
class Expr:
    def __init__(self: Any, func: Callable[[Any], Any]) -> None: ...
class ExprFactory:
    registry: Dict[str, Callable[..., Any]] = ...
    def register(cls: Any, name: str, builder: Callable[..., Any]) -> None: ...
    def build(cls: Any, name: str, **kwargs: Any) -> Any: ...
def safe_div_builder(eps: float = ..., backend: str = ...) -> Callable[[Any, Any], Any]: ...
def zscore_builder(col: str, mean: Optional[Any] = ..., std: Optional[Any] = ..., backend: str = ...) -> Callable[[Any], Any]: ...
def bollinger_builder(col: str, window: int = ..., num_std: float = ..., backend: str = ...) -> Callable[[Any], Any]: ...
