from typing import Any

logger: Any
cudf: Any
polars: Any
NVCOMP_CODECS: Any
Frame: Any
class ParquetOptions:
    columns: Optional[list[str]] = ...
    compression: Optional[Literal['snappy', 'zstd', 'lz4', 'none']] = ...
    filters: Optional[Any] = ...
    engine: Optional[Literal['cudf', 'polars']] = ...
def read_parquet_gpu(path: Union[str, list[str]], opts: Optional[ParquetOptions] = ...) -> Frame: ...
def write_parquet_gpu(df: Frame, path: str, opts: Optional[ParquetOptions] = ..., **kwargs: Any) -> None: ...
