from typing import Any

logger: Any
NVTX_ENABLED: Any
def range_ctx(message: str, color: Optional[int] = ...) -> Any: ...
def nvtx_range(message: str, color: Optional[int] = ...) -> Any: ...
class nvtx_plan:
    def __init__(self: Any, name: str, color: Optional[int] = ...) -> Any: ...
