from typing import Any

logger: Any
class PlanSegment:
    ops: list[Callable] = ...
    spec: Optional[Spec] = ...
    estimated_cost: float = ...
def estimate_compute_cost(op: Callable, backend: str) -> float: ...
def score_segment(segment: PlanSegment, sample_data: Any, backend: Optional[str] = ...) -> float: ...
class HeuristicPlanner:
    metrics: Dict[str, float] = ...
    def select_plan(self: Any, segments: list[PlanSegment], sample_data: Any) -> list[PlanSegment]: ...
    def optimize(self: Any, segments: list[PlanSegment], sample_data: Any) -> list[PlanSegment]: ...
