from typing import Any

logger: Any
class Spec(ABC, Hashable):
    def to_backend_spec(self: Any, backend: str) -> Any: ...
    def validate(self: Any) -> None: ...
class WindowSpec(Spec):
    partition_by: Optional[list[str]] = ...
    order_by: Optional[list[str]] = ...
    preceding: Optional[int] = ...
    following: Optional[int] = ...
    min_periods: int = ...
    def validate(self: Any) -> None: ...
    def to_backend_spec(self: Any, backend: str) -> Any: ...
class GroupSpec(Spec):
    by: list[str] = ...
    as_index: bool = ...
    sort: bool = ...
    def validate(self: Any) -> None: ...
    def to_backend_spec(self: Any, backend: str) -> Any: ...
class SpecFactory:
    registry: Dict[str, Callable[..., Spec]] = ...
    def register(cls: Any, name: str, builder: Callable[..., Spec]) -> Any: ...
    def build(cls: Any, name: str, **kwargs: Any) -> Spec: ...
    def compose(cls: Any, *specs: Spec) -> Spec: ...
def profile_spec(func: Callable) -> Callable: ...
