from typing import Any

logger: Any
class TorchBatch:
    tensors: Dict[str, 'torch.Tensor'] = ...
    lengths: Optional['torch.Tensor'] = ...
    meta: Dict[str, Any] = ...
class BackendBridge(ABC):
    def to_torch(self: Any, df: Any, cols: Sequence[str], dtypes: Optional[Dict[str, 'torch.dtype']], include_lengths: bool) -> TorchBatch: ...
class CuDFBridge(BackendBridge):
    def to_torch(self: Any, df: Any, cols: Sequence[str], dtypes: Optional[Dict[str, 'torch.dtype']], include_lengths: bool) -> TorchBatch: ...
class PolarsBridge(BackendBridge):
    def to_torch(self: Any, df: Any, cols: Sequence[str], dtypes: Optional[Dict[str, 'torch.dtype']], include_lengths: bool) -> TorchBatch: ...
def bridge_factory(df: Any) -> BackendBridge: ...
def profile_evolve(func: Callable) -> Callable: ...
def to_torch_batch(df: Any, cols: Sequence[str], dtypes: Optional[Dict[str, 'torch.dtype']] = ..., include_lengths: bool = ...) -> TorchBatch: ...
def set_amp_precision(precision: str = ...) -> Any: ...
def seed_everything(seed: int = ...) -> Any: ...
