from typing import Any

logger: Any
class Transform(ABC):
    def __init__(self: Any, fn: Callable[[Any], Any], backend: Optional[str] = ...) -> Any: ...
    def apply(self: Any, df: Any) -> Any: ...
    def validate(self: Any, df: Any) -> None: ...
class CompositeTransform(Transform):
    def __init__(self: Any, fn: Callable[[Any], Any], backend: Optional[str] = ...) -> Any: ...
    def validate(self: Any, df: Any) -> None: ...
def profile_transform(func: Callable) -> Callable: ...
class NormalizeTransform(Transform):
    def __init__(self: Any, col: str, mean: Optional[float] = ..., std: Optional[float] = ...) -> Any: ...
    def apply(self: Any, df: Any) -> Any: ...
    def validate(self: Any, df: Any) -> None: ...
class BollingerTransform(Transform):
    def __init__(self: Any, col: str, window: int = ..., num_std: float = ..., output_cols: Optional[List[str]] = ...) -> Any: ...
    def apply(self: Any, df: Any) -> Any: ...
    def validate(self: Any, df: Any) -> None: ...
class LogTransform(Transform):
    def __init__(self: Any, col: str, base: float = ..., eps: float = ...) -> Any: ...
    def apply(self: Any, df: Any) -> Any: ...
    def validate(self: Any, df: Any) -> None: ...
class MinMaxScaleTransform(Transform):
    def __init__(self: Any, col: str, min_val: Optional[float] = ..., max_val: Optional[float] = ..., eps: float = ...) -> Any: ...
    def apply(self: Any, df: Any) -> Any: ...
    def validate(self: Any, df: Any) -> None: ...
class ToTorchTransform(Transform):
    def __init__(self: Any, cols: List[str], dtypes: Optional[Dict[str, Any]] = ..., include_lengths: bool = ...) -> Any: ...
    def validate(self: Any, df: Any) -> None: ...
class TransformFactory:
    def register(cls: Any, name: str, builder: Callable[..., Transform]) -> Any: ...
    def build(cls: Any, name: str, **kwargs: Any) -> Transform: ...
    def compose(cls: Any, *names: str, **kwargs: Any) -> Transform: ...
    def auto_register_from_exprs(cls: Any) -> Any: ...
def feature_engineer_chain(cols: List[str]) -> Transform: ...
