from typing import Any

logger: Any
class Validator(ABC):
    def validate(self: Any, obj: Any) -> None: ...
class SchemaValidator(Validator):
    def __init__(self: Any, expected: Mapping[str, str], strict: bool = ...) -> Any: ...
    def validate(self: Any, df: Any) -> None: ...
class PlanValidator(Validator):
    def validate(self: Any, graph: Dict[Any, Sequence[Any]]) -> None: ...
class ValidatorFactory:
    def schema(expected: Mapping[str, str], strict: bool = ...) -> Validator: ...
    def plan() -> Validator: ...
def schema_checks(df: Any, expected: Mapping[str, str], strict: bool = ...) -> None: ...
def plan_checks(graph: Dict[Any, Sequence[Any]]) -> None: ...
